// SPDX-License-Identifier: MIT

//go:build amd64 && !purego

package gammonnet

import (
	"os"
	"regexp"
	"strings"
	"testing"
)

// The generated assembly is read back and checked, because two of its
// properties are invariants rather than preferences and neither shows up as a
// wrong answer in a benchmark.
func TestGeneratedKernelHasNoFMAAndNoFramePointer(t *testing.T) {
	raw, err := os.ReadFile("kernel_avx2_amd64.s")
	if err != nil {
		t.Fatalf("generated kernel: %v", err)
	}
	asm := string(raw)

	if !strings.Contains(asm, "Code generated by command") {
		t.Fatal("kernel_avx2_amd64.s has lost its generated-file header; it is produced by _asm, not edited")
	}

	// 1. No FMA (ADR-0024): a different answer that the gold suites' 1e-6
	// would not notice.
	if fma := regexp.MustCompile(`(?m)^\s*V?FMADD\w*`).FindString(asm); fma != "" {
		t.Errorf("the kernel emits %q: no fused multiply-add, ever (ADR-0024)", strings.TrimSpace(fma))
	}

	// 2. No BP: the runtime walks the frame pointer on a preemption signal,
	// and avo reaches for it when the tile runs out of registers — a crash
	// elsewhere, once every few runs.
	if bp := regexp.MustCompile(`(?m)^\s*\w+\s+.*\bBP\b`).FindString(asm); bp != "" {
		t.Errorf("the kernel touches BP (%q): the tile is too wide for the free registers, "+
			"and clobbering the frame pointer crashes the runtime intermittently",
			strings.TrimSpace(bp))
	}
}
