// SPDX-License-Identifier: MIT

//go:build !amd64 || purego

package gammonnet

// acceleratedKernels is empty on every architecture without a generated
// kernel, so those builds run the pure-Go path — correct, simply not
// accelerated.
//
// arm64 is the notable one. ADR-0024 called for a NEON twin generated by avo
// alongside the AVX2 one; avo generates x86 only (it has no arm64 back end at
// v0.6.0), so F1 ships AVX2 plus the Go fallback and leaves arm64 on the
// fallback. That is a follow-up, not an oversight: writing Plan 9 arm64
// assembly by hand and shipping it unverified on a machine this project does
// not build on is precisely the silent-wrong-answer failure #133 asks to
// avoid. The seam is here; a NEON kernel plugs into it by returning one more
// entry.
func acceleratedKernels() []denseKernel { return nil }
