// Code generated by command: go run main.go -out ../kernel_avx2_amd64.s -stubs ../kernel_avx2_amd64.go -pkg gammonnet. DO NOT EDIT.

//go:build amd64 && !purego

package gammonnet

// denseAVX2ReLU évalue une couche dense sur un lot de 8 positions et applique ReLU.
//
// Les activations sont feature-major (act[j*8+n]), les poids row-major
// [outDim][in]. Chaque voie n accumule sur j croissant en float32,
// multiplication et addition séparées — jamais de FMA (ADR-0024).
//
//go:noescape
func denseAVX2ReLU(w *float32, bias *float32, act *float32, out *float32, in int, outDim int)

// denseAVX2Linear évalue une couche dense sur un lot de 8 positions, sans activation.
//
// Même contrat arithmétique que denseAVX2ReLU : voie par position,
// somme sur j croissant, VMULPS puis VADDPS séparés, jamais de FMA.
//
//go:noescape
func denseAVX2Linear(w *float32, bias *float32, act *float32, out *float32, in int, outDim int)
