// Code generated by command: go run main.go -out ../kernel_avx2_amd64.s -stubs ../kernel_avx2_amd64.go -pkg gammonnet. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

// func denseAVX2ReLU(w *float32, bias *float32, act *float32, out *float32, in int, outDim int)
// Requires: AVX
TEXT ·denseAVX2ReLU(SB), NOSPLIT, $0-48
	MOVQ   w+0(FP), AX
	MOVQ   bias+8(FP), CX
	MOVQ   act+16(FP), DX
	MOVQ   out+24(FP), BX
	MOVQ   in+32(FP), SI
	MOVQ   outDim+40(FP), DI
	SHLQ   $0x02, SI
	VXORPS Y0, Y0, Y0

tileloop:
	CMPQ         DI, $0x00000006
	JL           tailhead
	VBROADCASTSS (CX), Y1
	VBROADCASTSS 4(CX), Y3
	VBROADCASTSS 8(CX), Y4
	VBROADCASTSS 12(CX), Y5
	VBROADCASTSS 16(CX), Y6
	VBROADCASTSS 20(CX), Y7
	MOVQ         AX, R8
	MOVQ         R8, R9
	ADDQ         SI, R9
	MOVQ         R9, R10
	ADDQ         SI, R10
	MOVQ         R10, R11
	ADDQ         SI, R11
	MOVQ         R11, R12
	ADDQ         SI, R12
	MOVQ         R12, R13
	ADDQ         SI, R13
	XORQ         R14, R14

tilej:
	VMOVUPS      (DX)(R14*8), Y8
	VBROADCASTSS (R8)(R14*1), Y2
	VMULPS       Y8, Y2, Y2
	VADDPS       Y2, Y1, Y1
	VBROADCASTSS (R9)(R14*1), Y2
	VMULPS       Y8, Y2, Y2
	VADDPS       Y2, Y3, Y3
	VBROADCASTSS (R10)(R14*1), Y2
	VMULPS       Y8, Y2, Y2
	VADDPS       Y2, Y4, Y4
	VBROADCASTSS (R11)(R14*1), Y2
	VMULPS       Y8, Y2, Y2
	VADDPS       Y2, Y5, Y5
	VBROADCASTSS (R12)(R14*1), Y2
	VMULPS       Y8, Y2, Y2
	VADDPS       Y2, Y6, Y6
	VBROADCASTSS (R13)(R14*1), Y2
	VMULPS       Y8, Y2, Y2
	VADDPS       Y2, Y7, Y7
	ADDQ         $0x04, R14
	CMPQ         R14, SI
	JL           tilej
	VMAXPS       Y0, Y1, Y1
	VMOVUPS      Y1, (BX)
	VMAXPS       Y0, Y3, Y3
	VMOVUPS      Y3, 32(BX)
	VMAXPS       Y0, Y4, Y4
	VMOVUPS      Y4, 64(BX)
	VMAXPS       Y0, Y5, Y5
	VMOVUPS      Y5, 96(BX)
	VMAXPS       Y0, Y6, Y6
	VMOVUPS      Y6, 128(BX)
	VMAXPS       Y0, Y7, Y7
	VMOVUPS      Y7, 160(BX)
	ADDQ         SI, AX
	ADDQ         SI, AX
	ADDQ         SI, AX
	ADDQ         SI, AX
	ADDQ         SI, AX
	ADDQ         SI, AX
	ADDQ         $0x18, CX
	ADDQ         $0x000000c0, BX
	SUBQ         $0x06, DI
	JMP          tileloop

tailhead:
tailloop:
	CMPQ         DI, $0x00000000
	JLE          done
	VBROADCASTSS (CX), Y1
	MOVQ         AX, R8
	XORQ         R14, R14

tailj:
	VMOVUPS      (DX)(R14*8), Y8
	VBROADCASTSS (R8)(R14*1), Y2
	VMULPS       Y8, Y2, Y2
	VADDPS       Y2, Y1, Y1
	ADDQ         $0x04, R14
	CMPQ         R14, SI
	JL           tailj
	VMAXPS       Y0, Y1, Y1
	VMOVUPS      Y1, (BX)
	ADDQ         SI, AX
	ADDQ         $0x04, CX
	ADDQ         $0x20, BX
	DECQ         DI
	JMP          tailloop

done:
	VZEROUPPER
	RET

// func denseAVX2Linear(w *float32, bias *float32, act *float32, out *float32, in int, outDim int)
// Requires: AVX
TEXT ·denseAVX2Linear(SB), NOSPLIT, $0-48
	MOVQ   w+0(FP), AX
	MOVQ   bias+8(FP), CX
	MOVQ   act+16(FP), DX
	MOVQ   out+24(FP), BX
	MOVQ   in+32(FP), SI
	MOVQ   outDim+40(FP), DI
	SHLQ   $0x02, SI
	VXORPS Y0, Y0, Y0

tileloop:
	CMPQ         DI, $0x00000006
	JL           tailhead
	VBROADCASTSS (CX), Y0
	VBROADCASTSS 4(CX), Y2
	VBROADCASTSS 8(CX), Y3
	VBROADCASTSS 12(CX), Y4
	VBROADCASTSS 16(CX), Y5
	VBROADCASTSS 20(CX), Y6
	MOVQ         AX, R8
	MOVQ         R8, R9
	ADDQ         SI, R9
	MOVQ         R9, R10
	ADDQ         SI, R10
	MOVQ         R10, R11
	ADDQ         SI, R11
	MOVQ         R11, R12
	ADDQ         SI, R12
	MOVQ         R12, R13
	ADDQ         SI, R13
	XORQ         R14, R14

tilej:
	VMOVUPS      (DX)(R14*8), Y7
	VBROADCASTSS (R8)(R14*1), Y1
	VMULPS       Y7, Y1, Y1
	VADDPS       Y1, Y0, Y0
	VBROADCASTSS (R9)(R14*1), Y1
	VMULPS       Y7, Y1, Y1
	VADDPS       Y1, Y2, Y2
	VBROADCASTSS (R10)(R14*1), Y1
	VMULPS       Y7, Y1, Y1
	VADDPS       Y1, Y3, Y3
	VBROADCASTSS (R11)(R14*1), Y1
	VMULPS       Y7, Y1, Y1
	VADDPS       Y1, Y4, Y4
	VBROADCASTSS (R12)(R14*1), Y1
	VMULPS       Y7, Y1, Y1
	VADDPS       Y1, Y5, Y5
	VBROADCASTSS (R13)(R14*1), Y1
	VMULPS       Y7, Y1, Y1
	VADDPS       Y1, Y6, Y6
	ADDQ         $0x04, R14
	CMPQ         R14, SI
	JL           tilej
	VMOVUPS      Y0, (BX)
	VMOVUPS      Y2, 32(BX)
	VMOVUPS      Y3, 64(BX)
	VMOVUPS      Y4, 96(BX)
	VMOVUPS      Y5, 128(BX)
	VMOVUPS      Y6, 160(BX)
	ADDQ         SI, AX
	ADDQ         SI, AX
	ADDQ         SI, AX
	ADDQ         SI, AX
	ADDQ         SI, AX
	ADDQ         SI, AX
	ADDQ         $0x18, CX
	ADDQ         $0x000000c0, BX
	SUBQ         $0x06, DI
	JMP          tileloop

tailhead:
tailloop:
	CMPQ         DI, $0x00000000
	JLE          done
	VBROADCASTSS (CX), Y0
	MOVQ         AX, R8
	XORQ         R14, R14

tailj:
	VMOVUPS      (DX)(R14*8), Y7
	VBROADCASTSS (R8)(R14*1), Y1
	VMULPS       Y7, Y1, Y1
	VADDPS       Y1, Y0, Y0
	ADDQ         $0x04, R14
	CMPQ         R14, SI
	JL           tailj
	VMOVUPS      Y0, (BX)
	ADDQ         SI, AX
	ADDQ         $0x04, CX
	ADDQ         $0x20, BX
	DECQ         DI
	JMP          tailloop

done:
	VZEROUPPER
	RET
