// SPDX-License-Identifier: MIT

package gammonnet

import (
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"errors"
	"fmt"
	"math"
	"os"
	"testing"
)

// testdata/policy_reference.bin is gammonNet's reference corpus for the
// policy (GNPL v1, upstream docs/specs/politique-spec.md §8), copied verbatim
// from gammonNet commit dfccb28 (data/policy_reference.bin, generated by
// tools/policy_corpus.py, seed 20261005). Its sidecar policy_reference.json
// names the weights it was generated with: the SHA-256 of the two embedded
// here. A copy that drifts from upstream would turn the test into a
// comparison of this port with itself, so the digest is pinned.
const (
	policyCorpusPath   = "testdata/policy_reference.bin"
	policyCorpusSHA256 = "fe96a3a4dd5ac9f850f65e111b4dabe98806f0d45bfd92d69a0b8b91e158493f"
	policyRecordSize   = 160
)

var policyLevelNames = [3]string{"instant", "normal", "thorough"}

type policyCase struct {
	level string
	in    PolicyDecision
	rc    int32
	want  PolicyAction
}

func readPolicyPosition(b []byte) Position {
	var p Position
	for i := 0; i < NumPoints; i++ {
		p.Points[i] = int8(b[i])
	}
	p.Bar = [2]uint8{b[24], b[25]}
	p.Off = [2]uint8{b[26], b[27]}
	p.Turn = b[28]
	return p
}

func readPolicyCorpus(t *testing.T) []policyCase {
	t.Helper()
	raw, err := os.ReadFile(policyCorpusPath)
	if err != nil {
		t.Fatal(err)
	}
	sum := sha256.Sum256(raw)
	if got := hex.EncodeToString(sum[:]); got != policyCorpusSHA256 {
		t.Fatalf("policy corpus digest %s, want upstream's %s", got, policyCorpusSHA256)
	}
	le := binary.LittleEndian
	if string(raw[0:4]) != "GNPL" || le.Uint32(raw[4:]) != 1 || le.Uint32(raw[12:]) != policyRecordSize {
		t.Fatalf("not a GNPL v1 corpus")
	}
	count := int(le.Uint32(raw[8:]))
	if len(raw) != 16+count*policyRecordSize {
		t.Fatalf("corpus holds %d bytes for %d records", len(raw), count)
	}
	i32 := func(b []byte, off int) int32 { return int32(le.Uint32(b[off:])) }
	cases := make([]policyCase, count)
	for n := range cases {
		r := raw[16+n*policyRecordSize : 16+(n+1)*policyRecordSize]
		c := &cases[n]
		c.level = policyLevelNames[i32(r, 32)]
		c.in = PolicyDecision{
			Position:     readPolicyPosition(r[0:29]),
			Pending:      Pending(i32(r, 36)),
			D1:           int(i32(r, 40)),
			D2:           int(i32(r, 44)),
			Cube:         int(i32(r, 48)),
			CubeOwner:    CubeOwner(i32(r, 52)),
			Jacoby:       i32(r, 56) != 0,
			UseMatch:     i32(r, 60) != 0,
			AwayOnRoll:   int(i32(r, 64)),
			AwayOpponent: int(i32(r, 68)),
			Crawford:     i32(r, 72) != 0,
			ResignValue:  int(i32(r, 76)),
		}
		c.rc = i32(r, 80)
		c.want = PolicyAction{
			Kind:        ActionKind(i32(r, 84)),
			ResignValue: int(i32(r, 88)),
			Searched:    i32(r, 92) != 0,
			EquityA:     math.Float64frombits(le.Uint64(r[140:])),
			EquityB:     math.Float64frombits(le.Uint64(r[148:])),
		}
		c.want.Play.NumMoves = int(i32(r, 96))
		for m := 0; m < c.want.Play.NumMoves; m++ {
			c.want.Play.Moves[m] = Move{From: int8(r[100+2*m]), To: int8(r[101+2*m])}
		}
		if c.want.Kind == ActionMove && c.rc == 0 {
			c.want.Play.Result = readPolicyPosition(r[108:137])
		}
	}
	return cases
}

// TestPolicyMatchesTheReferenceCorpus holds the port to gn_policy.c: every
// decision of the corpus answered with the same action, the same play and
// result, the same refusals, and the reference's equities bit for bit.
func TestPolicyMatchesTheReferenceCorpus(t *testing.T) {
	cases := readPolicyCorpus(t)
	if testing.Short() {
		// The instant level alone: the deeper ones are a few seconds each.
		var instant []policyCase
		for _, c := range cases {
			if c.level == "instant" {
				instant = append(instant, c)
			}
		}
		cases = instant
	}
	p, err := NewPolicy()
	if err != nil {
		t.Fatal(err)
	}
	failures, ties := 0, 0
	worst := 0.0
	fail := func(n int, c policyCase, got PolicyAction, why string) {
		t.Helper()
		w := c.want
		t.Errorf("case %d (%s, pending %d): %s\n got  kind %d resign %d searched %v eq (%v, %v) play %+v\n want kind %d resign %d searched %v eq (%v, %v) play %+v",
			n, c.level, c.in.Pending, why,
			got.Kind, got.ResignValue, got.Searched, got.EquityA, got.EquityB, got.Play,
			w.Kind, w.ResignValue, w.Searched, w.EquityA, w.EquityB, w.Play)
		failures++
		if failures >= 10 {
			t.Fatalf("stopping after %d failures", failures)
		}
	}
	for n, c := range cases {
		got, err := p.Decide(c.level, &c.in)
		if c.rc != 0 {
			if !errors.Is(err, ErrPolicyRefused) {
				fail(n, c, got, fmt.Sprintf("refused upstream: %+v", c.in))
			}
			continue
		}
		if err != nil {
			fail(n, c, got, err.Error())
			continue
		}
		w := c.want
		dA, dB := math.Abs(got.EquityA-w.EquityA), math.Abs(got.EquityB-w.EquityB)
		worst = max(worst, dA, dB)
		if dA > goldTolerance || dB > goldTolerance || got.Searched != w.Searched {
			fail(n, c, got, "numbers differ")
			continue
		}
		if got.Kind == w.Kind && got.ResignValue == w.ResignValue && samePolicyPlay(&got.Play, &w.Play) {
			continue
		}
		if policyTie(t, p, &c, &got) {
			ties++
			continue
		}
		fail(n, c, got, "action differs")
	}
	t.Logf("%d decisions replayed against the C reference: max|Δ equity| = %.3e, %d ties within %.0e",
		len(cases), worst, ties, goldTolerance)
}

// TestPolicyRefusesAnUnknownLevel: a typo is refused, never a default.
func TestPolicyRefusesAnUnknownLevel(t *testing.T) {
	p, err := NewPolicy()
	if err != nil {
		t.Fatal(err)
	}
	d := PolicyDecision{Position: readPolicyCorpus(t)[0].in.Position, Pending: PendingCube, Cube: 1}
	if _, err := p.Decide("weak", &d); !errors.Is(err, ErrPolicyRefused) {
		t.Fatalf("unknown level answered: %v", err)
	}
}

// samePolicyPlay: the same board reached with the same number of dice. The
// sub-moves that lead there are the generator's representative of a set of
// paths deduplicated by result, and the board is what is played.
func samePolicyPlay(a, b *Play) bool {
	return a.NumMoves == b.NumMoves && a.Result == b.Result
}

// policyTie: the port and the reference only disagree inside the tolerance —
// the two numbers a cube or resignation verdict compares are within it, or the
// reference's play is valued within it of the port's. Demanding the same pick
// there would demand more than the tolerance states (gold_test.go).
func policyTie(t *testing.T, p *Policy, c *policyCase, got *PolicyAction) bool {
	t.Helper()
	if c.in.Pending != PendingMove {
		return got.Kind != ActionResign && c.want.Kind != ActionResign &&
			math.Abs(c.want.EquityA-c.want.EquityB) <= goldTolerance
	}
	shape, _ := Level(c.level)
	if !p.configure(&shape, &c.in) {
		return false
	}
	ranked := make([]Candidate, MaxPlays)
	n, err := p.s.Plays(&c.in.Position, c.in.D1, c.in.D2, ranked)
	if err != nil {
		return false
	}
	for _, cand := range ranked[:n] {
		if cand.Play.Result == c.want.Play.Result {
			return math.Abs(cand.Equity-got.EquityA) <= goldTolerance
		}
	}
	return false
}
