import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

export default [
    js.configs.recommended,
    ...svelte.configs['flat/recommended'],
    prettier,
    ...svelte.configs['flat/prettier'],
    {
        languageOptions: {
            globals: {
                ...globals.browser,
                ...globals.node
            }
        },
        rules: {
            // varsIgnorePattern deliberately does NOT cover plain let/const
            // declarations — an unused `_foo` local should be an error (dead
            // code), not silently tolerated. destructuredArrayIgnorePattern
            // keeps the escape hatch for array-destructuring positions you
            // must name but don't need (e.g. `const [, _second] = pair`).
            'no-unused-vars': [
                'error',
                {
                    destructuredArrayIgnorePattern: '^_',
                    argsIgnorePattern: '^_',
                    caughtErrorsIgnorePattern: '^_'
                }
            ],
            'no-console': 'error',
            // Native dialogs are invisible or untranslated in some webviews;
            // confirmAction (services/confirmService.js) is the themed, translated one.
            'no-restricted-globals': [
                'error',
                { name: 'confirm', message: 'Use confirmAction from services/confirmService.js.' },
                { name: 'alert', message: 'Use the status bar or a modal, not a native alert.' },
                { name: 'prompt', message: 'Use a modal with an input, not a native prompt.' }
            ],
            'no-restricted-properties': [
                'error',
                { object: 'window', property: 'confirm', message: 'Use confirmAction from services/confirmService.js.' },
                { object: 'window', property: 'alert', message: 'Use the status bar or a modal, not a native alert.' },
                { object: 'window', property: 'prompt', message: 'Use a modal with an input, not a native prompt.' }
            ]
        }
    },
    {
        files: ['**/*.svelte'],
        rules: {
            // Many "unused" vars in Svelte are used in the template; store
            // auto-subscriptions ($store) are the one pattern still allowed
            // through varsIgnorePattern here. Plain `_foo` locals are not.
            'no-unused-vars': [
                'error',
                {
                    varsIgnorePattern: '^\\$',
                    destructuredArrayIgnorePattern: '^_',
                    argsIgnorePattern: '^_',
                    caughtErrorsIgnorePattern: '^_'
                }
            ],
            // Errors, not warnings: an unkeyed each-block or reactive loop
            // must fail CI instead of accumulating silently.
            'svelte/require-each-key': 'error',
            'svelte/prefer-svelte-reactivity': 'error',
            'svelte/infinite-reactive-loop': 'error',
            // Svelte reactive assignments can look "useless" to the JS analyser
            'no-useless-assignment': 'warn'
        }
    },
    {
        // src/i18n/help/*.js are generated by cmd/help-gen (make help): each
        // exports a single multi-KB HTML template-literal string per help tab.
        // They parse fine at runtime (node/Vite) but exceed eslint's espree
        // parser limits, so we skip linting them — they contain no logic to
        // lint. What the exclusion used to hide (fiche D.15: an unescaped
        // interpolation in the About tab) is covered instead by
        // src/__tests__/help.safety.test.js, which inspects the shipped corpus
        // in all nine languages.
        ignores: ['wailsjs/**', 'dist/**', 'node_modules/**', 'src/i18n/help/*.js']
    }
];
