# Generated by `go run ./cmd/openapi-gen` from internal/server's route
# table. DO NOT EDIT BY HAND; regenerate instead. The transport lives in
# client.py, which is hand-written: what changes with the API is generated,
# what changes with judgement is not.
#
# Every method is one `POST /v1/<family>.<method>` call. A method whose route
# streams NDJSON returns an iterator of decoded objects; every other method
# returns the decoded JSON body (None when the route answers with no content).
"""blunderDB engine API — generated method surface."""

from __future__ import annotations

from typing import Any, Iterator, Optional, Union

from .client import BaseClient


class GeneratedAPI(BaseClient):
    """One method per route. Mixed into Client (client.py)."""

    def maintenance_vacuum(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /ops/maintenance.vacuum — hand-written handler — see openapi.yaml."
        return self._call("/ops/maintenance.vacuum", payload)

    def tenant_purge(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /ops/tenant.purge — hand-written handler — see openapi.yaml."
        return self._call("/ops/tenant.purge", payload)

    def across_analyses_load_by_ids(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/across.analysesLoadByIds — JSON."
        return self._call("/v1/across.analysesLoadByIds", payload)

    def across_club_ranking(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/across.clubRanking — JSON."
        return self._call("/v1/across.clubRanking", payload)

    def across_collection_positions(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/across.collectionPositions — NDJSON stream."
        return self._stream("/v1/across.collectionPositions", payload)

    def across_collections_list(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/across.collectionsList — NDJSON stream."
        return self._stream("/v1/across.collectionsList", payload)

    def across_comments_by_zobrist(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/across.commentsByZobrist — NDJSON stream."
        return self._stream("/v1/across.commentsByZobrist", payload)

    def across_match_move_positions(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/across.matchMovePositions — NDJSON stream."
        return self._stream("/v1/across.matchMovePositions", payload)

    def across_matches_get(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/across.matchesGet — JSON."
        return self._call("/v1/across.matchesGet", payload)

    def across_matches_list(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/across.matchesList — NDJSON stream."
        return self._stream("/v1/across.matchesList", payload)

    def across_player_table(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/across.playerTable — JSON."
        return self._call("/v1/across.playerTable", payload)

    def across_search_find(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/across.searchFind — NDJSON stream."
        return self._stream("/v1/across.searchFind", payload)

    def across_stats_compute(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/across.statsCompute — JSON."
        return self._call("/v1/across.statsCompute", payload)

    def analyses_delete(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/analyses.delete — JSON."
        return self._call("/v1/analyses.delete", payload)

    def analyses_load(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/analyses.load — JSON."
        return self._call("/v1/analyses.load", payload)

    def analyses_load_by_ids(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/analyses.loadByIds — JSON."
        return self._call("/v1/analyses.loadByIds", payload)

    def analyses_repair(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/analyses.repair — JSON."
        return self._call("/v1/analyses.repair", payload)

    def analyses_save(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/analyses.save — JSON."
        return self._call("/v1/analyses.save", payload)

    def anki_bury_card(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.buryCard — JSON."
        return self._call("/v1/anki.buryCard", payload)

    def anki_create_deck(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.createDeck — JSON."
        return self._call("/v1/anki.createDeck", payload)

    def anki_create_study_deck(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.createStudyDeck — JSON."
        return self._call("/v1/anki.createStudyDeck", payload)

    def anki_deck_position_count(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.deckPositionCount — JSON."
        return self._call("/v1/anki.deckPositionCount", payload)

    def anki_deck_position_ids(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.deckPositionIds — JSON."
        return self._call("/v1/anki.deckPositionIds", payload)

    def anki_deck_positions(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/anki.deckPositions — NDJSON stream."
        return self._stream("/v1/anki.deckPositions", payload)

    def anki_deck_stats(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.deckStats — JSON."
        return self._call("/v1/anki.deckStats", payload)

    def anki_delete_deck(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.deleteDeck — JSON."
        return self._call("/v1/anki.deleteDeck", payload)

    def anki_filtered_position_count(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.filteredPositionCount — JSON."
        return self._call("/v1/anki.filteredPositionCount", payload)

    def anki_filtered_position_ids(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.filteredPositionIds — JSON."
        return self._call("/v1/anki.filteredPositionIds", payload)

    def anki_forecast(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.forecast — JSON."
        return self._call("/v1/anki.forecast", payload)

    def anki_index_of_deck_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.indexOfDeckPosition — JSON."
        return self._call("/v1/anki.indexOfDeckPosition", payload)

    def anki_index_of_filtered_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.indexOfFilteredPosition — JSON."
        return self._call("/v1/anki.indexOfFilteredPosition", payload)

    def anki_linked_card(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.linkedCard — JSON."
        return self._call("/v1/anki.linkedCard", payload)

    def anki_list_decks(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/anki.listDecks — NDJSON stream."
        return self._stream("/v1/anki.listDecks", payload)

    def anki_next_card(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.nextCard — JSON."
        return self._call("/v1/anki.nextCard", payload)

    def anki_remove_card(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.removeCard — JSON."
        return self._call("/v1/anki.removeCard", payload)

    def anki_reset_deck(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.resetDeck — JSON."
        return self._call("/v1/anki.resetDeck", payload)

    def anki_retention(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.retention — JSON."
        return self._call("/v1/anki.retention", payload)

    def anki_review_card(self, payload: Optional[dict] = None, *, idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/anki.reviewCard — JSON. Accepts an Idempotency-Key."
        return self._call("/v1/anki.reviewCard", payload, idempotency_key=idempotency_key)

    def anki_review_log(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/anki.reviewLog — NDJSON stream."
        return self._stream("/v1/anki.reviewLog", payload)

    def anki_reviews_by_game_type(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.reviewsByGameType — JSON."
        return self._call("/v1/anki.reviewsByGameType", payload)

    def anki_suspend_card(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.suspendCard — JSON."
        return self._call("/v1/anki.suspendCard", payload)

    def anki_sync(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.sync — JSON."
        return self._call("/v1/anki.sync", payload)

    def anki_sync_with_positions(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.syncWithPositions — JSON."
        return self._call("/v1/anki.syncWithPositions", payload)

    def anki_update_deck(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.updateDeck — JSON."
        return self._call("/v1/anki.updateDeck", payload)

    def anki_update_deck_params(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.updateDeckParams — JSON."
        return self._call("/v1/anki.updateDeckParams", payload)

    def collections_add_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.addPosition — JSON."
        return self._call("/v1/collections.addPosition", payload)

    def collections_add_positions(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.addPositions — JSON."
        return self._call("/v1/collections.addPositions", payload)

    def collections_collections_of(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/collections.collectionsOf — NDJSON stream."
        return self._stream("/v1/collections.collectionsOf", payload)

    def collections_copy_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.copyPosition — JSON."
        return self._call("/v1/collections.copyPosition", payload)

    def collections_count_positions(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.countPositions — JSON."
        return self._call("/v1/collections.countPositions", payload)

    def collections_create(self, payload: Optional[dict] = None, *, idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/collections.create — JSON. Accepts an Idempotency-Key."
        return self._call("/v1/collections.create", payload, idempotency_key=idempotency_key)

    def collections_delete(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.delete — JSON."
        return self._call("/v1/collections.delete", payload)

    def collections_evaluate(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.evaluate — JSON."
        return self._call("/v1/collections.evaluate", payload)

    def collections_freeze(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.freeze — JSON."
        return self._call("/v1/collections.freeze", payload)

    def collections_get(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.get — JSON."
        return self._call("/v1/collections.get", payload)

    def collections_index_of_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.indexOfPosition — JSON."
        return self._call("/v1/collections.indexOfPosition", payload)

    def collections_list(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/collections.list — NDJSON stream."
        return self._stream("/v1/collections.list", payload)

    def collections_move_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.movePosition — JSON."
        return self._call("/v1/collections.movePosition", payload)

    def collections_position_ids(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.positionIds — JSON."
        return self._call("/v1/collections.positionIds", payload)

    def collections_position_index_map(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.positionIndexMap — JSON."
        return self._call("/v1/collections.positionIndexMap", payload)

    def collections_positions(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/collections.positions — NDJSON stream."
        return self._stream("/v1/collections.positions", payload)

    def collections_remove_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.removePosition — JSON."
        return self._call("/v1/collections.removePosition", payload)

    def collections_remove_positions(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.removePositions — JSON."
        return self._call("/v1/collections.removePositions", payload)

    def collections_reorder(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.reorder — JSON."
        return self._call("/v1/collections.reorder", payload)

    def collections_reorder_positions(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.reorderPositions — JSON."
        return self._call("/v1/collections.reorderPositions", payload)

    def collections_set_filter(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.setFilter — JSON."
        return self._call("/v1/collections.setFilter", payload)

    def collections_suggest(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.suggest — JSON."
        return self._call("/v1/collections.suggest", payload)

    def collections_update(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.update — JSON."
        return self._call("/v1/collections.update", payload)

    def comments_add(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/comments.add — JSON."
        return self._call("/v1/comments.add", payload)

    def comments_by_position(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/comments.byPosition — NDJSON stream."
        return self._stream("/v1/comments.byPosition", payload)

    def comments_delete(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/comments.delete — JSON."
        return self._call("/v1/comments.delete", payload)

    def comments_delete_for_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/comments.deleteForPosition — JSON."
        return self._call("/v1/comments.deleteForPosition", payload)

    def comments_list_all(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/comments.listAll — NDJSON stream."
        return self._stream("/v1/comments.listAll", payload)

    def comments_search(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/comments.search — NDJSON stream."
        return self._stream("/v1/comments.search", payload)

    def comments_tags(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/comments.tags — JSON."
        return self._call("/v1/comments.tags", payload)

    def comments_text(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/comments.text — JSON."
        return self._call("/v1/comments.text", payload)

    def comments_update(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/comments.update — JSON."
        return self._call("/v1/comments.update", payload)

    def directions_add_note(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.addNote — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.addNote", payload, if_match=if_match, idempotency_key=idempotency_key)

    def directions_add_pair(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.addPair — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.addPair", payload, if_match=if_match, idempotency_key=idempotency_key)

    def directions_add_participant(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.addParticipant — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.addParticipant", payload, if_match=if_match, idempotency_key=idempotency_key)

    def directions_attach_match(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.attachMatch — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.attachMatch", payload, if_match=if_match, idempotency_key=idempotency_key)

    def directions_brackets(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/directions.brackets — JSON."
        return self._call("/v1/directions.brackets", payload)

    def directions_cancel_match(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.cancelMatch — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.cancelMatch", payload, if_match=if_match, idempotency_key=idempotency_key)

    def directions_clock(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/directions.clock — JSON."
        return self._call("/v1/directions.clock", payload)

    def directions_close(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.close — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.close", payload, if_match=if_match, idempotency_key=idempotency_key)

    def directions_confirm_all_proposals(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.confirmAllProposals — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.confirmAllProposals", payload, if_match=if_match, idempotency_key=idempotency_key)

    def directions_confirm_proposal(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.confirmProposal — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.confirmProposal", payload, if_match=if_match, idempotency_key=idempotency_key)

    def directions_correct_result(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.correctResult — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.correctResult", payload, if_match=if_match, idempotency_key=idempotency_key)

    def directions_create(self, payload: Optional[dict] = None, *, idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.create — JSON. Accepts an Idempotency-Key."
        return self._call("/v1/directions.create", payload, idempotency_key=idempotency_key)

    def directions_detach_match(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.detachMatch — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.detachMatch", payload, if_match=if_match, idempotency_key=idempotency_key)

    def directions_directory(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/directions.directory — JSON."
        return self._call("/v1/directions.directory", payload)

    def directions_enter_forfeit(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.enterForfeit — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.enterForfeit", payload, if_match=if_match, idempotency_key=idempotency_key)

    def directions_enter_participants(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.enterParticipants — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.enterParticipants", payload, if_match=if_match, idempotency_key=idempotency_key)

    def directions_enter_result(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.enterResult — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.enterResult", payload, if_match=if_match, idempotency_key=idempotency_key)

    def directions_free_participants(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/directions.freeParticipants — JSON."
        return self._call("/v1/directions.freeParticipants", payload)

    def directions_get(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/directions.get — JSON."
        return self._call("/v1/directions.get", payload)

    def directions_history(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/directions.history — JSON."
        return self._call("/v1/directions.history", payload)

    def directions_last_decision(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/directions.lastDecision — JSON."
        return self._call("/v1/directions.lastDecision", payload)

    def directions_list(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/directions.list — JSON."
        return self._call("/v1/directions.list", payload)

    def directions_make_absent(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.makeAbsent — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.makeAbsent", payload, if_match=if_match, idempotency_key=idempotency_key)

    def directions_make_available(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.makeAvailable — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.makeAvailable", payload, if_match=if_match, idempotency_key=idempotency_key)

    def directions_move_match_to_table(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.moveMatchToTable — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.moveMatchToTable", payload, if_match=if_match, idempotency_key=idempotency_key)

    def directions_page_html(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/directions.pageHtml — JSON."
        return self._call("/v1/directions.pageHtml", payload)

    def directions_pairing_sheet_html(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/directions.pairingSheetHtml — JSON."
        return self._call("/v1/directions.pairingSheetHtml", payload)

    def directions_participants(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/directions.participants — JSON."
        return self._call("/v1/directions.participants", payload)

    def directions_preview_config(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/directions.previewConfig — JSON."
        return self._call("/v1/directions.previewConfig", payload)

    def directions_reinstate(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.reinstate — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.reinstate", payload, if_match=if_match, idempotency_key=idempotency_key)

    def directions_reopen(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.reopen — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.reopen", payload, if_match=if_match, idempotency_key=idempotency_key)

    def directions_set_config(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.setConfig — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.setConfig", payload, if_match=if_match, idempotency_key=idempotency_key)

    def directions_set_tables(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.setTables — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.setTables", payload, if_match=if_match, idempotency_key=idempotency_key)

    def directions_slots(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/directions.slots — JSON."
        return self._call("/v1/directions.slots", payload)

    def directions_standings(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/directions.standings — JSON."
        return self._call("/v1/directions.standings", payload)

    def directions_standings_csv(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/directions.standingsCsv — JSON."
        return self._call("/v1/directions.standingsCsv", payload)

    def directions_start_match(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.startMatch — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.startMatch", payload, if_match=if_match, idempotency_key=idempotency_key)

    def directions_table_grid(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/directions.tableGrid — JSON."
        return self._call("/v1/directions.tableGrid", payload)

    def directions_update_pair(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.updatePair — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.updatePair", payload, if_match=if_match, idempotency_key=idempotency_key)

    def directions_update_participant(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.updateParticipant — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.updateParticipant", payload, if_match=if_match, idempotency_key=idempotency_key)

    def directions_withdraw(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/directions.withdraw — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/directions.withdraw", payload, if_match=if_match, idempotency_key=idempotency_key)

    def duels_act(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/duels.act — hand-written handler — see openapi.yaml."
        return self._call("/v1/duels.act", payload)

    def duels_contribute(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/duels.contribute — hand-written handler — see openapi.yaml."
        return self._call("/v1/duels.contribute", payload)

    def duels_create(self, payload: Optional[dict] = None, *, idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/duels.create — JSON. Accepts an Idempotency-Key."
        return self._call("/v1/duels.create", payload, idempotency_key=idempotency_key)

    def duels_discard(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/duels.discard — hand-written handler — see openapi.yaml."
        return self._call("/v1/duels.discard", payload)

    def duels_flag(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/duels.flag — hand-written handler — see openapi.yaml."
        return self._call("/v1/duels.flag", payload)

    def duels_forfeit(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/duels.forfeit — hand-written handler — see openapi.yaml."
        return self._call("/v1/duels.forfeit", payload)

    def duels_get(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/duels.get — hand-written handler — see openapi.yaml."
        return self._call("/v1/duels.get", payload)

    def duels_list(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/duels.list — JSON."
        return self._call("/v1/duels.list", payload)

    def duels_open(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/duels.open — hand-written handler — see openapi.yaml."
        return self._call("/v1/duels.open", payload)

    def duels_stop(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/duels.stop — hand-written handler — see openapi.yaml."
        return self._call("/v1/duels.stop", payload)

    def duels_suspend(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/duels.suspend — hand-written handler — see openapi.yaml."
        return self._call("/v1/duels.suspend", payload)

    def events_alias_list(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/events.alias.list — JSON."
        return self._call("/v1/events.alias.list", payload)

    def events_alias_remove(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/events.alias.remove — JSON."
        return self._call("/v1/events.alias.remove", payload)

    def events_alias_set(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/events.alias.set — JSON."
        return self._call("/v1/events.alias.set", payload)

    def events_alias_suggest(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/events.alias.suggest — JSON."
        return self._call("/v1/events.alias.suggest", payload)

    def exports_json(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/exports.json — hand-written handler — see openapi.yaml."
        return self._call("/v1/exports.json", payload)

    def exports_sqlite(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/exports.sqlite — hand-written handler — see openapi.yaml."
        return self._call("/v1/exports.sqlite", payload)

    def filters_delete(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/filters.delete — JSON."
        return self._call("/v1/filters.delete", payload)

    def filters_list(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/filters.list — NDJSON stream."
        return self._stream("/v1/filters.list", payload)

    def filters_load_edit_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/filters.loadEditPosition — JSON."
        return self._call("/v1/filters.loadEditPosition", payload)

    def filters_load_exclude_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/filters.loadExcludePosition — JSON."
        return self._call("/v1/filters.loadExcludePosition", payload)

    def filters_save(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/filters.save — JSON."
        return self._call("/v1/filters.save", payload)

    def filters_save_edit_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/filters.saveEditPosition — JSON."
        return self._call("/v1/filters.saveEditPosition", payload)

    def filters_save_exclude_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/filters.saveExcludePosition — JSON."
        return self._call("/v1/filters.saveExcludePosition", payload)

    def filters_set_pinned(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/filters.setPinned — JSON."
        return self._call("/v1/filters.setPinned", payload)

    def filters_update(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/filters.update — JSON."
        return self._call("/v1/filters.update", payload)

    def gammonnet_analyze_missing(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/gammonnet.analyzeMissing — hand-written handler — see openapi.yaml."
        return self._call("/v1/gammonnet.analyzeMissing", payload)

    def gammonnet_analyze_missing_cancel(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/gammonnet.analyzeMissing.cancel — hand-written handler — see openapi.yaml."
        return self._call("/v1/gammonnet.analyzeMissing.cancel", payload)

    def gammonnet_compare(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/gammonnet.compare — hand-written handler — see openapi.yaml."
        return self._call("/v1/gammonnet.compare", payload)

    def gammonnet_cube_matrix(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/gammonnet.cubeMatrix — hand-written handler — see openapi.yaml."
        return self._call("/v1/gammonnet.cubeMatrix", payload)

    def gammonnet_evaluate(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/gammonnet.evaluate — hand-written handler — see openapi.yaml."
        return self._call("/v1/gammonnet.evaluate", payload)

    def gammonnet_sweep_stale(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/gammonnet.sweepStale — hand-written handler — see openapi.yaml."
        return self._call("/v1/gammonnet.sweepStale", payload)

    def history_clear(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/history.clear — JSON."
        return self._call("/v1/history.clear", payload)

    def history_load(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/history.load — JSON."
        return self._call("/v1/history.load", payload)

    def history_save(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/history.save — JSON."
        return self._call("/v1/history.save", payload)

    def imports_batch(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.batch — hand-written handler — see openapi.yaml."
        return self._call("/v1/imports.batch", payload)

    def imports_batch_cancel(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.batch.cancel — JSON."
        return self._call("/v1/imports.batch.cancel", payload)

    def imports_batch_status(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.batch.status — JSON."
        return self._call("/v1/imports.batch.status", payload)

    def imports_bgf(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.bgf — hand-written handler — see openapi.yaml."
        return self._call("/v1/imports.bgf", payload)

    def imports_cancel(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.cancel — hand-written handler — see openapi.yaml."
        return self._call("/v1/imports.cancel", payload)

    def imports_db(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.db — hand-written handler — see openapi.yaml."
        return self._call("/v1/imports.db", payload)

    def imports_files(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.files — JSON."
        return self._call("/v1/imports.files", payload)

    def imports_gnubg(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.gnubg — hand-written handler — see openapi.yaml."
        return self._call("/v1/imports.gnubg", payload)

    def imports_json(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.json — hand-written handler — see openapi.yaml."
        return self._call("/v1/imports.json", payload)

    def imports_list(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.list — JSON."
        return self._call("/v1/imports.list", payload)

    def imports_ogxm(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.ogxm — hand-written handler — see openapi.yaml."
        return self._call("/v1/imports.ogxm", payload)

    def imports_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.position — hand-written handler — see openapi.yaml."
        return self._call("/v1/imports.position", payload)

    def imports_report(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.report — JSON."
        return self._call("/v1/imports.report", payload)

    def imports_study_queue(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.studyQueue — JSON."
        return self._call("/v1/imports.studyQueue", payload)

    def imports_xg(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.xg — hand-written handler — see openapi.yaml."
        return self._call("/v1/imports.xg", payload)

    def lessons_add_step(self, payload: Optional[dict] = None, *, idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/lessons.addStep — JSON. Accepts an Idempotency-Key."
        return self._call("/v1/lessons.addStep", payload, idempotency_key=idempotency_key)

    def lessons_create(self, payload: Optional[dict] = None, *, idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/lessons.create — JSON. Accepts an Idempotency-Key."
        return self._call("/v1/lessons.create", payload, idempotency_key=idempotency_key)

    def lessons_delete(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/lessons.delete — JSON."
        return self._call("/v1/lessons.delete", payload)

    def lessons_done_steps(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/lessons.doneSteps — JSON."
        return self._call("/v1/lessons.doneSteps", payload)

    def lessons_get(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/lessons.get — JSON."
        return self._call("/v1/lessons.get", payload)

    def lessons_list(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/lessons.list — JSON."
        return self._call("/v1/lessons.list", payload)

    def lessons_remove_step(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/lessons.removeStep — JSON."
        return self._call("/v1/lessons.removeStep", payload)

    def lessons_reorder_steps(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/lessons.reorderSteps — JSON."
        return self._call("/v1/lessons.reorderSteps", payload)

    def lessons_set_step_done(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/lessons.setStepDone — JSON."
        return self._call("/v1/lessons.setStepDone", payload)

    def lessons_update(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/lessons.update — JSON."
        return self._call("/v1/lessons.update", payload)

    def lessons_update_step(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/lessons.updateStep — JSON."
        return self._call("/v1/lessons.updateStep", payload)

    def library_settings_load(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/librarySettings.load — JSON."
        return self._call("/v1/librarySettings.load", payload)

    def library_settings_save(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/librarySettings.save — JSON."
        return self._call("/v1/librarySettings.save", payload)

    def maintenance_reencode(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/maintenance.reencode — hand-written handler — see openapi.yaml."
        return self._call("/v1/maintenance.reencode", payload)

    def matches_count(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.count — JSON."
        return self._call("/v1/matches.count", payload)

    def matches_create_game(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.createGame — JSON."
        return self._call("/v1/matches.createGame", payload)

    def matches_create_move(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.createMove — JSON."
        return self._call("/v1/matches.createMove", payload)

    def matches_delete(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.delete — JSON."
        return self._call("/v1/matches.delete", payload)

    def matches_duplicates(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.duplicates — JSON."
        return self._call("/v1/matches.duplicates", payload)

    def matches_export_mat(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.exportMat — hand-written handler — see openapi.yaml."
        return self._call("/v1/matches.exportMat", payload)

    def matches_find_by_hash(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.findByHash — JSON."
        return self._call("/v1/matches.findByHash", payload)

    def matches_games(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/matches.games — NDJSON stream."
        return self._stream("/v1/matches.games", payload)

    def matches_get(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.get — JSON."
        return self._call("/v1/matches.get", payload)

    def matches_last_visited(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.lastVisited — JSON."
        return self._call("/v1/matches.lastVisited", payload)

    def matches_list(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/matches.list — NDJSON stream."
        return self._stream("/v1/matches.list", payload)

    def matches_merge_players(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.mergePlayers — JSON."
        return self._call("/v1/matches.mergePlayers", payload)

    def matches_move_positions(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/matches.movePositions — NDJSON stream."
        return self._stream("/v1/matches.movePositions", payload)

    def matches_moves(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/matches.moves — NDJSON stream."
        return self._stream("/v1/matches.moves", payload)

    def matches_moves_by_match(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/matches.movesByMatch — NDJSON stream."
        return self._stream("/v1/matches.movesByMatch", payload)

    def matches_origin(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.origin — JSON."
        return self._call("/v1/matches.origin", payload)

    def matches_save(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.save — JSON."
        return self._call("/v1/matches.save", payload)

    def matches_score_moves(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.scoreMoves — JSON."
        return self._call("/v1/matches.scoreMoves", payload)

    def matches_set_last_visited_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.setLastVisitedPosition — JSON."
        return self._call("/v1/matches.setLastVisitedPosition", payload)

    def matches_set_video_source(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.setVideoSource — JSON."
        return self._call("/v1/matches.setVideoSource", payload)

    def matches_swap_players(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.swapPlayers — JSON."
        return self._call("/v1/matches.swapPlayers", payload)

    def matches_update(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.update — JSON."
        return self._call("/v1/matches.update", payload)

    def matches_update_comment(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.updateComment — JSON."
        return self._call("/v1/matches.updateComment", payload)

    def met_import(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/met.import — JSON."
        return self._call("/v1/met.import", payload)

    def met_list(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/met.list — JSON."
        return self._call("/v1/met.list", payload)

    def met_of_analysis(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/met.ofAnalysis — JSON."
        return self._call("/v1/met.ofAnalysis", payload)

    def met_set_current(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/met.setCurrent — JSON."
        return self._call("/v1/met.setCurrent", payload)

    def metadata_counts(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/metadata.counts — JSON."
        return self._call("/v1/metadata.counts", payload)

    def metadata_counts_estimate(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/metadata.countsEstimate — JSON."
        return self._call("/v1/metadata.countsEstimate", payload)

    def metadata_version(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/metadata.version — JSON."
        return self._call("/v1/metadata.version", payload)

    def pile_state(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/pile.state — JSON."
        return self._call("/v1/pile.state", payload)

    def pile_toggle(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/pile.toggle — JSON."
        return self._call("/v1/pile.toggle", payload)

    def players_alias_list(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/players.alias.list — JSON."
        return self._call("/v1/players.alias.list", payload)

    def players_alias_remove(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/players.alias.remove — JSON."
        return self._call("/v1/players.alias.remove", payload)

    def players_alias_set(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/players.alias.set — JSON."
        return self._call("/v1/players.alias.set", payload)

    def players_alias_suggest(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/players.alias.suggest — JSON."
        return self._call("/v1/players.alias.suggest", payload)

    def positions_count(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.count — JSON."
        return self._call("/v1/positions.count", payload)

    def positions_delete(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.delete — JSON."
        return self._call("/v1/positions.delete", payload)

    def positions_epc(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.epc — JSON."
        return self._call("/v1/positions.epc", payload)

    def positions_exists(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.exists — JSON."
        return self._call("/v1/positions.exists", payload)

    def positions_explain(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.explain — JSON."
        return self._call("/v1/positions.explain", payload)

    def positions_from_ogid(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.fromOGID — JSON."
        return self._call("/v1/positions.fromOGID", payload)

    def positions_from_xgid(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.fromXGID — JSON."
        return self._call("/v1/positions.fromXGID", payload)

    def positions_from_xgp(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.fromXGP — JSON."
        return self._call("/v1/positions.fromXGP", payload)

    def positions_index_of(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.indexOf — JSON."
        return self._call("/v1/positions.indexOf", payload)

    def positions_legal_moves(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.legalMoves — JSON."
        return self._call("/v1/positions.legalMoves", payload)

    def positions_list(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/positions.list — NDJSON stream."
        return self._stream("/v1/positions.list", payload)

    def positions_list_ids(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.listIds — JSON."
        return self._call("/v1/positions.listIds", payload)

    def positions_load(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.load — JSON."
        return self._call("/v1/positions.load", payload)

    def positions_load_by_ids(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.loadByIds — JSON."
        return self._call("/v1/positions.loadByIds", payload)

    def positions_parse_text(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.parseText — JSON."
        return self._call("/v1/positions.parseText", payload)

    def positions_reclassify_phases(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.reclassifyPhases — JSON."
        return self._call("/v1/positions.reclassifyPhases", payload)

    def positions_repair_crawford(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.repairCrawford — JSON."
        return self._call("/v1/positions.repairCrawford", payload)

    def positions_save(self, payload: Optional[dict] = None, *, idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/positions.save — JSON. Accepts an Idempotency-Key."
        return self._call("/v1/positions.save", payload, idempotency_key=idempotency_key)

    def positions_similar(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.similar — JSON."
        return self._call("/v1/positions.similar", payload)

    def positions_update(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.update — JSON."
        return self._call("/v1/positions.update", payload)

    def quiz_grade_checker(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/quiz.gradeChecker — JSON."
        return self._call("/v1/quiz.gradeChecker", payload)

    def quiz_grade_checker_move(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/quiz.gradeCheckerMove — JSON."
        return self._call("/v1/quiz.gradeCheckerMove", payload)

    def quiz_grade_cube(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/quiz.gradeCube — JSON."
        return self._call("/v1/quiz.gradeCube", payload)

    def rencontres_attach(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/rencontres.attach — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/rencontres.attach", payload, if_match=if_match, idempotency_key=idempotency_key)

    def rencontres_create(self, payload: Optional[dict] = None, *, idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/rencontres.create — JSON. Accepts an Idempotency-Key."
        return self._call("/v1/rencontres.create", payload, idempotency_key=idempotency_key)

    def rencontres_detach(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/rencontres.detach — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/rencontres.detach", payload, if_match=if_match, idempotency_key=idempotency_key)

    def rencontres_get(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/rencontres.get — JSON."
        return self._call("/v1/rencontres.get", payload)

    def rencontres_list(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/rencontres.list — JSON."
        return self._call("/v1/rencontres.list", payload)

    def rencontres_page_html(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/rencontres.pageHtml — JSON."
        return self._call("/v1/rencontres.pageHtml", payload)

    def rencontres_ranking(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/rencontres.ranking — JSON."
        return self._call("/v1/rencontres.ranking", payload)

    def rencontres_set_breaks(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/rencontres.setBreaks — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/rencontres.setBreaks", payload, if_match=if_match, idempotency_key=idempotency_key)

    def rencontres_set_event_rooms(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/rencontres.setEventRooms — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/rencontres.setEventRooms", payload, if_match=if_match, idempotency_key=idempotency_key)

    def rencontres_set_table_out_of_service(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/rencontres.setTableOutOfService — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/rencontres.setTableOutOfService", payload, if_match=if_match, idempotency_key=idempotency_key)

    def rencontres_set_tables(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/rencontres.setTables — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/rencontres.setTables", payload, if_match=if_match, idempotency_key=idempotency_key)

    def rencontres_trash(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/rencontres.trash — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/rencontres.trash", payload, if_match=if_match, idempotency_key=idempotency_key)

    def rencontres_update(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/rencontres.update — JSON. Requires If-Match: the Direction-Version of your last read. Accepts an Idempotency-Key."
        return self._call("/v1/rencontres.update", payload, if_match=if_match, idempotency_key=idempotency_key)

    def rollout_filter(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/rollout.filter — hand-written handler — see openapi.yaml."
        return self._call("/v1/rollout.filter", payload)

    def rollout_filter_cancel(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/rollout.filter.cancel — hand-written handler — see openapi.yaml."
        return self._call("/v1/rollout.filter.cancel", payload)

    def rollout_list(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/rollout.list — JSON."
        return self._call("/v1/rollout.list", payload)

    def rollout_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/rollout.position — hand-written handler — see openapi.yaml."
        return self._call("/v1/rollout.position", payload)

    def search_count(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/search.count — JSON."
        return self._call("/v1/search.count", payload)

    def search_find(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/search.find — NDJSON stream."
        return self._stream("/v1/search.find", payload)

    def search_ids(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/search.ids — JSON."
        return self._call("/v1/search.ids", payload)

    def search_index_of(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/search.indexOf — JSON."
        return self._call("/v1/search.indexOf", payload)

    def search_parse(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/search.parse — JSON."
        return self._call("/v1/search.parse", payload)

    def search_query(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/search.query — hand-written handler — see openapi.yaml."
        return self._call("/v1/search.query", payload)

    def search_history_delete_entry(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/searchHistory.deleteEntry — JSON."
        return self._call("/v1/searchHistory.deleteEntry", payload)

    def search_history_list(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/searchHistory.list — NDJSON stream."
        return self._stream("/v1/searchHistory.list", payload)

    def search_history_save(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/searchHistory.save — JSON."
        return self._call("/v1/searchHistory.save", payload)

    def session_clear(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/session.clear — JSON."
        return self._call("/v1/session.clear", payload)

    def session_load(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/session.load — JSON."
        return self._call("/v1/session.load", payload)

    def session_save(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/session.save — JSON."
        return self._call("/v1/session.save", payload)

    def stats_biases(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.biases — JSON."
        return self._call("/v1/stats.biases", payload)

    def stats_compute(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.compute — JSON."
        return self._call("/v1/stats.compute", payload)

    def stats_date_range(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.dateRange — JSON."
        return self._call("/v1/stats.dateRange", payload)

    def stats_head_to_head(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.headToHead — JSON."
        return self._call("/v1/stats.headToHead", payload)

    def stats_match_badges(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.matchBadges — JSON."
        return self._call("/v1/stats.matchBadges", payload)

    def stats_match_decision_losses(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.matchDecisionLosses — JSON."
        return self._call("/v1/stats.matchDecisionLosses", payload)

    def stats_match_detail(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.matchDetail — JSON."
        return self._call("/v1/stats.matchDetail", payload)

    def stats_match_move_grades(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.matchMoveGrades — JSON."
        return self._call("/v1/stats.matchMoveGrades", payload)

    def stats_match_review(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.matchReview — JSON."
        return self._call("/v1/stats.matchReview", payload)

    def stats_match_time_summary(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.matchTimeSummary — JSON."
        return self._call("/v1/stats.matchTimeSummary", payload)

    def stats_player_contrast(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.playerContrast — JSON."
        return self._call("/v1/stats.playerContrast", payload)

    def stats_player_names(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.playerNames — JSON."
        return self._call("/v1/stats.playerNames", payload)

    def stats_player_table(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.playerTable — JSON."
        return self._call("/v1/stats.playerTable", payload)

    def stats_position_ids_by_match(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.positionIdsByMatch — JSON."
        return self._call("/v1/stats.positionIdsByMatch", payload)

    def stats_position_ids_by_selection(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.positionIdsBySelection — JSON."
        return self._call("/v1/stats.positionIdsBySelection", payload)

    def stats_position_ids_by_tournament(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.positionIdsByTournament — JSON."
        return self._call("/v1/stats.positionIdsByTournament", payload)

    def stats_pr_by_window(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.prByWindow — JSON."
        return self._call("/v1/stats.prByWindow", payload)

    def stats_ranking(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.ranking — JSON."
        return self._call("/v1/stats.ranking", payload)

    def stats_rebuild_match_stats(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.rebuildMatchStats — JSON."
        return self._call("/v1/stats.rebuildMatchStats", payload)

    def stats_recurring_errors(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.recurringErrors — JSON."
        return self._call("/v1/stats.recurringErrors", payload)

    def stats_report(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.report — JSON."
        return self._call("/v1/stats.report", payload)

    def stats_study_effect(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.studyEffect — JSON."
        return self._call("/v1/stats.studyEffect", payload)

    def stats_study_ids(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.studyIds — JSON."
        return self._call("/v1/stats.studyIds", payload)

    def stats_study_plan(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.studyPlan — JSON."
        return self._call("/v1/stats.studyPlan", payload)

    def stats_study_plan_ids(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.studyPlanIds — JSON."
        return self._call("/v1/stats.studyPlanIds", payload)

    def stats_study_plan_queue(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.studyPlanQueue — JSON."
        return self._call("/v1/stats.studyPlanQueue", payload)

    def stats_time_errors(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.timeErrors — JSON."
        return self._call("/v1/stats.timeErrors", payload)

    def stats_tournament_badges(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.tournamentBadges — JSON."
        return self._call("/v1/stats.tournamentBadges", payload)

    def stats_tournament_review(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.tournamentReview — JSON."
        return self._call("/v1/stats.tournamentReview", payload)

    def stats_training(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.training — JSON."
        return self._call("/v1/stats.training", payload)

    def study_backlog(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/study.backlog — JSON."
        return self._call("/v1/study.backlog", payload)

    def study_set_studied(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/study.setStudied — JSON."
        return self._call("/v1/study.setStudied", payload)

    def tenants_quota(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/tenants.quota — JSON."
        return self._call("/v1/tenants.quota", payload)

    def tournaments_add_match(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/tournaments.addMatch — JSON."
        return self._call("/v1/tournaments.addMatch", payload)

    def tournaments_create(self, payload: Optional[dict] = None, *, idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/tournaments.create — JSON. Accepts an Idempotency-Key."
        return self._call("/v1/tournaments.create", payload, idempotency_key=idempotency_key)

    def tournaments_delete(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/tournaments.delete — JSON."
        return self._call("/v1/tournaments.delete", payload)

    def tournaments_get(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/tournaments.get — JSON."
        return self._call("/v1/tournaments.get", payload)

    def tournaments_list(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/tournaments.list — NDJSON stream."
        return self._stream("/v1/tournaments.list", payload)

    def tournaments_matches(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/tournaments.matches — NDJSON stream."
        return self._stream("/v1/tournaments.matches", payload)

    def tournaments_remove_match(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/tournaments.removeMatch — JSON."
        return self._call("/v1/tournaments.removeMatch", payload)

    def tournaments_reorder_matches(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/tournaments.reorderMatches — JSON."
        return self._call("/v1/tournaments.reorderMatches", payload)

    def tournaments_set_match_by_name(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/tournaments.setMatchByName — JSON."
        return self._call("/v1/tournaments.setMatchByName", payload)

    def tournaments_tournament_of(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/tournaments.tournamentOf — JSON."
        return self._call("/v1/tournaments.tournamentOf", payload)

    def tournaments_update(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/tournaments.update — JSON."
        return self._call("/v1/tournaments.update", payload)

    def tournaments_update_comment(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/tournaments.updateComment — JSON."
        return self._call("/v1/tournaments.updateComment", payload)

    def training_missed(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/training.missed — JSON."
        return self._call("/v1/training.missed", payload)

    def training_number_stats(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/training.numberStats — JSON."
        return self._call("/v1/training.numberStats", payload)

    def training_save(self, payload: Optional[dict] = None, *, idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/training.save — JSON. Accepts an Idempotency-Key."
        return self._call("/v1/training.save", payload, idempotency_key=idempotency_key)

    def training_sessions(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/training.sessions — JSON."
        return self._call("/v1/training.sessions", payload)

    def transcriptions_abandon(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/transcriptions.abandon — JSON. Requires If-Match: the draft's revision. Accepts an Idempotency-Key."
        return self._call("/v1/transcriptions.abandon", payload, if_match=if_match, idempotency_key=idempotency_key)

    def transcriptions_apply(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/transcriptions.apply — JSON. Requires If-Match: the draft's revision. Accepts an Idempotency-Key."
        return self._call("/v1/transcriptions.apply", payload, if_match=if_match, idempotency_key=idempotency_key)

    def transcriptions_close(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/transcriptions.close — JSON."
        return self._call("/v1/transcriptions.close", payload)

    def transcriptions_create(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/transcriptions.create — JSON."
        return self._call("/v1/transcriptions.create", payload)

    def transcriptions_edit_match(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/transcriptions.editMatch — JSON."
        return self._call("/v1/transcriptions.editMatch", payload)

    def transcriptions_export_mat(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/transcriptions.exportMat — JSON."
        return self._call("/v1/transcriptions.exportMat", payload)

    def transcriptions_finish(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/transcriptions.finish — JSON. Requires If-Match: the draft's revision. Accepts an Idempotency-Key."
        return self._call("/v1/transcriptions.finish", payload, if_match=if_match, idempotency_key=idempotency_key)

    def transcriptions_get(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/transcriptions.get — hand-written handler — see openapi.yaml."
        return self._call("/v1/transcriptions.get", payload)

    def transcriptions_list(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/transcriptions.list — JSON."
        return self._call("/v1/transcriptions.list", payload)

    def transcriptions_losses(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/transcriptions.losses — JSON."
        return self._call("/v1/transcriptions.losses", payload)

    def transcriptions_materialize(self, payload: Optional[dict] = None, *, idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/transcriptions.materialize — JSON. Accepts an Idempotency-Key."
        return self._call("/v1/transcriptions.materialize", payload, idempotency_key=idempotency_key)

    def transcriptions_open(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/transcriptions.open — JSON."
        return self._call("/v1/transcriptions.open", payload)

    def transcriptions_redo(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/transcriptions.redo — JSON. Requires If-Match: the draft's revision. Accepts an Idempotency-Key."
        return self._call("/v1/transcriptions.redo", payload, if_match=if_match, idempotency_key=idempotency_key)

    def transcriptions_undo(self, payload: Optional[dict] = None, *, if_match: Union[int, str], idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/transcriptions.undo — JSON. Requires If-Match: the draft's revision. Accepts an Idempotency-Key."
        return self._call("/v1/transcriptions.undo", payload, if_match=if_match, idempotency_key=idempotency_key)

    def trash_count(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/trash.count — JSON."
        return self._call("/v1/trash.count", payload)

    def trash_delete_collection(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/trash.deleteCollection — JSON."
        return self._call("/v1/trash.deleteCollection", payload)

    def trash_delete_comment(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/trash.deleteComment — JSON."
        return self._call("/v1/trash.deleteComment", payload)

    def trash_delete_match(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/trash.deleteMatch — JSON."
        return self._call("/v1/trash.deleteMatch", payload)

    def trash_delete_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/trash.deletePosition — JSON."
        return self._call("/v1/trash.deletePosition", payload)

    def trash_discard(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/trash.discard — JSON."
        return self._call("/v1/trash.discard", payload)

    def trash_empty(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/trash.empty — JSON."
        return self._call("/v1/trash.empty", payload)

    def trash_list(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/trash.list — JSON."
        return self._call("/v1/trash.list", payload)

    def trash_restore(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/trash.restore — JSON."
        return self._call("/v1/trash.restore", payload)
