# Generated by `go run ./cmd/openapi-gen` from internal/server's route
# table. DO NOT EDIT BY HAND; regenerate instead. The transport lives in
# client.py, which is hand-written: what changes with the API is generated,
# what changes with judgement is not.
#
# Every method is one `POST /v1/<family>.<method>` call. A method whose route
# streams NDJSON returns an iterator of decoded objects; every other method
# returns the decoded JSON body (None when the route answers with no content).
"""blunderDB engine API — generated method surface."""

from __future__ import annotations

from typing import Any, Iterator, Optional

from .client import BaseClient


class GeneratedAPI(BaseClient):
    """One method per route. Mixed into Client (client.py)."""

    def maintenance_vacuum(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /ops/maintenance.vacuum — hand-written handler — see openapi.yaml."
        return self._call("/ops/maintenance.vacuum", payload)

    def tenant_purge(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /ops/tenant.purge — hand-written handler — see openapi.yaml."
        return self._call("/ops/tenant.purge", payload)

    def analyses_delete(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/analyses.delete — JSON."
        return self._call("/v1/analyses.delete", payload)

    def analyses_load(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/analyses.load — JSON."
        return self._call("/v1/analyses.load", payload)

    def analyses_repair(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/analyses.repair — JSON."
        return self._call("/v1/analyses.repair", payload)

    def analyses_save(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/analyses.save — JSON."
        return self._call("/v1/analyses.save", payload)

    def anki_bury_card(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.buryCard — JSON."
        return self._call("/v1/anki.buryCard", payload)

    def anki_create_deck(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.createDeck — JSON."
        return self._call("/v1/anki.createDeck", payload)

    def anki_deck_positions(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/anki.deckPositions — NDJSON stream."
        return self._stream("/v1/anki.deckPositions", payload)

    def anki_deck_stats(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.deckStats — JSON."
        return self._call("/v1/anki.deckStats", payload)

    def anki_delete_deck(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.deleteDeck — JSON."
        return self._call("/v1/anki.deleteDeck", payload)

    def anki_forecast(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.forecast — JSON."
        return self._call("/v1/anki.forecast", payload)

    def anki_list_decks(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/anki.listDecks — NDJSON stream."
        return self._stream("/v1/anki.listDecks", payload)

    def anki_next_card(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.nextCard — JSON."
        return self._call("/v1/anki.nextCard", payload)

    def anki_remove_card(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.removeCard — JSON."
        return self._call("/v1/anki.removeCard", payload)

    def anki_reset_deck(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.resetDeck — JSON."
        return self._call("/v1/anki.resetDeck", payload)

    def anki_retention(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.retention — JSON."
        return self._call("/v1/anki.retention", payload)

    def anki_review_card(self, payload: Optional[dict] = None, *, idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/anki.reviewCard — JSON. Accepts an Idempotency-Key."
        return self._call("/v1/anki.reviewCard", payload, idempotency_key=idempotency_key)

    def anki_review_log(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/anki.reviewLog — NDJSON stream."
        return self._stream("/v1/anki.reviewLog", payload)

    def anki_suspend_card(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.suspendCard — JSON."
        return self._call("/v1/anki.suspendCard", payload)

    def anki_sync(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.sync — JSON."
        return self._call("/v1/anki.sync", payload)

    def anki_sync_with_positions(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.syncWithPositions — JSON."
        return self._call("/v1/anki.syncWithPositions", payload)

    def anki_update_deck(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.updateDeck — JSON."
        return self._call("/v1/anki.updateDeck", payload)

    def anki_update_deck_params(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/anki.updateDeckParams — JSON."
        return self._call("/v1/anki.updateDeckParams", payload)

    def collections_add_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.addPosition — JSON."
        return self._call("/v1/collections.addPosition", payload)

    def collections_add_positions(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.addPositions — JSON."
        return self._call("/v1/collections.addPositions", payload)

    def collections_collections_of(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/collections.collectionsOf — NDJSON stream."
        return self._stream("/v1/collections.collectionsOf", payload)

    def collections_copy_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.copyPosition — JSON."
        return self._call("/v1/collections.copyPosition", payload)

    def collections_create(self, payload: Optional[dict] = None, *, idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/collections.create — JSON. Accepts an Idempotency-Key."
        return self._call("/v1/collections.create", payload, idempotency_key=idempotency_key)

    def collections_delete(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.delete — JSON."
        return self._call("/v1/collections.delete", payload)

    def collections_get(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.get — JSON."
        return self._call("/v1/collections.get", payload)

    def collections_list(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/collections.list — NDJSON stream."
        return self._stream("/v1/collections.list", payload)

    def collections_move_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.movePosition — JSON."
        return self._call("/v1/collections.movePosition", payload)

    def collections_position_index_map(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.positionIndexMap — JSON."
        return self._call("/v1/collections.positionIndexMap", payload)

    def collections_positions(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/collections.positions — NDJSON stream."
        return self._stream("/v1/collections.positions", payload)

    def collections_remove_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.removePosition — JSON."
        return self._call("/v1/collections.removePosition", payload)

    def collections_remove_positions(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.removePositions — JSON."
        return self._call("/v1/collections.removePositions", payload)

    def collections_reorder(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.reorder — JSON."
        return self._call("/v1/collections.reorder", payload)

    def collections_reorder_positions(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.reorderPositions — JSON."
        return self._call("/v1/collections.reorderPositions", payload)

    def collections_update(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/collections.update — JSON."
        return self._call("/v1/collections.update", payload)

    def comments_add(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/comments.add — JSON."
        return self._call("/v1/comments.add", payload)

    def comments_by_position(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/comments.byPosition — NDJSON stream."
        return self._stream("/v1/comments.byPosition", payload)

    def comments_delete(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/comments.delete — JSON."
        return self._call("/v1/comments.delete", payload)

    def comments_delete_for_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/comments.deleteForPosition — JSON."
        return self._call("/v1/comments.deleteForPosition", payload)

    def comments_list_all(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/comments.listAll — NDJSON stream."
        return self._stream("/v1/comments.listAll", payload)

    def comments_search(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/comments.search — NDJSON stream."
        return self._stream("/v1/comments.search", payload)

    def comments_tags(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/comments.tags — JSON."
        return self._call("/v1/comments.tags", payload)

    def comments_text(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/comments.text — JSON."
        return self._call("/v1/comments.text", payload)

    def comments_update(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/comments.update — JSON."
        return self._call("/v1/comments.update", payload)

    def exports_json(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/exports.json — hand-written handler — see openapi.yaml."
        return self._call("/v1/exports.json", payload)

    def exports_sqlite(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/exports.sqlite — hand-written handler — see openapi.yaml."
        return self._call("/v1/exports.sqlite", payload)

    def filters_delete(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/filters.delete — JSON."
        return self._call("/v1/filters.delete", payload)

    def filters_list(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/filters.list — NDJSON stream."
        return self._stream("/v1/filters.list", payload)

    def filters_load_edit_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/filters.loadEditPosition — JSON."
        return self._call("/v1/filters.loadEditPosition", payload)

    def filters_load_exclude_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/filters.loadExcludePosition — JSON."
        return self._call("/v1/filters.loadExcludePosition", payload)

    def filters_save(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/filters.save — JSON."
        return self._call("/v1/filters.save", payload)

    def filters_save_edit_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/filters.saveEditPosition — JSON."
        return self._call("/v1/filters.saveEditPosition", payload)

    def filters_save_exclude_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/filters.saveExcludePosition — JSON."
        return self._call("/v1/filters.saveExcludePosition", payload)

    def filters_update(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/filters.update — JSON."
        return self._call("/v1/filters.update", payload)

    def gammonnet_analyze_missing(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/gammonnet.analyzeMissing — hand-written handler — see openapi.yaml."
        return self._call("/v1/gammonnet.analyzeMissing", payload)

    def gammonnet_analyze_missing_cancel(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/gammonnet.analyzeMissing.cancel — hand-written handler — see openapi.yaml."
        return self._call("/v1/gammonnet.analyzeMissing.cancel", payload)

    def gammonnet_compare(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/gammonnet.compare — hand-written handler — see openapi.yaml."
        return self._call("/v1/gammonnet.compare", payload)

    def gammonnet_cube_matrix(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/gammonnet.cubeMatrix — hand-written handler — see openapi.yaml."
        return self._call("/v1/gammonnet.cubeMatrix", payload)

    def gammonnet_sweep_stale(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/gammonnet.sweepStale — hand-written handler — see openapi.yaml."
        return self._call("/v1/gammonnet.sweepStale", payload)

    def history_clear(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/history.clear — JSON."
        return self._call("/v1/history.clear", payload)

    def history_load(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/history.load — JSON."
        return self._call("/v1/history.load", payload)

    def history_save(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/history.save — JSON."
        return self._call("/v1/history.save", payload)

    def imports_bgf(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.bgf — hand-written handler — see openapi.yaml."
        return self._call("/v1/imports.bgf", payload)

    def imports_cancel(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.cancel — hand-written handler — see openapi.yaml."
        return self._call("/v1/imports.cancel", payload)

    def imports_db(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.db — hand-written handler — see openapi.yaml."
        return self._call("/v1/imports.db", payload)

    def imports_gnubg(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.gnubg — hand-written handler — see openapi.yaml."
        return self._call("/v1/imports.gnubg", payload)

    def imports_json(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.json — hand-written handler — see openapi.yaml."
        return self._call("/v1/imports.json", payload)

    def imports_list(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.list — JSON."
        return self._call("/v1/imports.list", payload)

    def imports_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.position — hand-written handler — see openapi.yaml."
        return self._call("/v1/imports.position", payload)

    def imports_report(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.report — JSON."
        return self._call("/v1/imports.report", payload)

    def imports_study_queue(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.studyQueue — JSON."
        return self._call("/v1/imports.studyQueue", payload)

    def imports_xg(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/imports.xg — hand-written handler — see openapi.yaml."
        return self._call("/v1/imports.xg", payload)

    def matches_create_game(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.createGame — JSON."
        return self._call("/v1/matches.createGame", payload)

    def matches_create_move(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.createMove — JSON."
        return self._call("/v1/matches.createMove", payload)

    def matches_delete(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.delete — JSON."
        return self._call("/v1/matches.delete", payload)

    def matches_export_mat(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.exportMat — hand-written handler — see openapi.yaml."
        return self._call("/v1/matches.exportMat", payload)

    def matches_find_by_hash(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.findByHash — JSON."
        return self._call("/v1/matches.findByHash", payload)

    def matches_games(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/matches.games — NDJSON stream."
        return self._stream("/v1/matches.games", payload)

    def matches_get(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.get — JSON."
        return self._call("/v1/matches.get", payload)

    def matches_last_visited(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.lastVisited — JSON."
        return self._call("/v1/matches.lastVisited", payload)

    def matches_list(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/matches.list — NDJSON stream."
        return self._stream("/v1/matches.list", payload)

    def matches_merge_players(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.mergePlayers — JSON."
        return self._call("/v1/matches.mergePlayers", payload)

    def matches_move_positions(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/matches.movePositions — NDJSON stream."
        return self._stream("/v1/matches.movePositions", payload)

    def matches_moves(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/matches.moves — NDJSON stream."
        return self._stream("/v1/matches.moves", payload)

    def matches_moves_by_match(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/matches.movesByMatch — NDJSON stream."
        return self._stream("/v1/matches.movesByMatch", payload)

    def matches_save(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.save — JSON."
        return self._call("/v1/matches.save", payload)

    def matches_set_last_visited_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.setLastVisitedPosition — JSON."
        return self._call("/v1/matches.setLastVisitedPosition", payload)

    def matches_swap_players(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.swapPlayers — JSON."
        return self._call("/v1/matches.swapPlayers", payload)

    def matches_update(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.update — JSON."
        return self._call("/v1/matches.update", payload)

    def matches_update_comment(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/matches.updateComment — JSON."
        return self._call("/v1/matches.updateComment", payload)

    def metadata_counts(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/metadata.counts — JSON."
        return self._call("/v1/metadata.counts", payload)

    def metadata_version(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/metadata.version — JSON."
        return self._call("/v1/metadata.version", payload)

    def positions_delete(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.delete — JSON."
        return self._call("/v1/positions.delete", payload)

    def positions_epc(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.epc — JSON."
        return self._call("/v1/positions.epc", payload)

    def positions_exists(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.exists — JSON."
        return self._call("/v1/positions.exists", payload)

    def positions_explain(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.explain — JSON."
        return self._call("/v1/positions.explain", payload)

    def positions_from_ogid(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.fromOGID — JSON."
        return self._call("/v1/positions.fromOGID", payload)

    def positions_from_xgid(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.fromXGID — JSON."
        return self._call("/v1/positions.fromXGID", payload)

    def positions_from_xgp(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.fromXGP — JSON."
        return self._call("/v1/positions.fromXGP", payload)

    def positions_legal_moves(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.legalMoves — JSON."
        return self._call("/v1/positions.legalMoves", payload)

    def positions_list(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/positions.list — NDJSON stream."
        return self._stream("/v1/positions.list", payload)

    def positions_list_ids(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.listIds — JSON."
        return self._call("/v1/positions.listIds", payload)

    def positions_load(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.load — JSON."
        return self._call("/v1/positions.load", payload)

    def positions_load_by_ids(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.loadByIds — JSON."
        return self._call("/v1/positions.loadByIds", payload)

    def positions_parse_text(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.parseText — JSON."
        return self._call("/v1/positions.parseText", payload)

    def positions_reclassify_phases(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.reclassifyPhases — JSON."
        return self._call("/v1/positions.reclassifyPhases", payload)

    def positions_save(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.save — JSON."
        return self._call("/v1/positions.save", payload)

    def positions_similar(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.similar — JSON."
        return self._call("/v1/positions.similar", payload)

    def positions_update(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/positions.update — JSON."
        return self._call("/v1/positions.update", payload)

    def quiz_grade_checker(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/quiz.gradeChecker — JSON."
        return self._call("/v1/quiz.gradeChecker", payload)

    def quiz_grade_checker_move(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/quiz.gradeCheckerMove — JSON."
        return self._call("/v1/quiz.gradeCheckerMove", payload)

    def quiz_grade_cube(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/quiz.gradeCube — JSON."
        return self._call("/v1/quiz.gradeCube", payload)

    def search_find(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/search.find — NDJSON stream."
        return self._stream("/v1/search.find", payload)

    def search_parse(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/search.parse — JSON."
        return self._call("/v1/search.parse", payload)

    def search_query(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/search.query — hand-written handler — see openapi.yaml."
        return self._call("/v1/search.query", payload)

    def search_history_delete_entry(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/searchHistory.deleteEntry — JSON."
        return self._call("/v1/searchHistory.deleteEntry", payload)

    def search_history_list(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/searchHistory.list — NDJSON stream."
        return self._stream("/v1/searchHistory.list", payload)

    def search_history_save(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/searchHistory.save — JSON."
        return self._call("/v1/searchHistory.save", payload)

    def session_clear(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/session.clear — JSON."
        return self._call("/v1/session.clear", payload)

    def session_load(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/session.load — JSON."
        return self._call("/v1/session.load", payload)

    def session_save(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/session.save — JSON."
        return self._call("/v1/session.save", payload)

    def stats_compute(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.compute — JSON."
        return self._call("/v1/stats.compute", payload)

    def stats_date_range(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.dateRange — JSON."
        return self._call("/v1/stats.dateRange", payload)

    def stats_match_badges(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.matchBadges — JSON."
        return self._call("/v1/stats.matchBadges", payload)

    def stats_match_detail(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.matchDetail — JSON."
        return self._call("/v1/stats.matchDetail", payload)

    def stats_player_names(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.playerNames — JSON."
        return self._call("/v1/stats.playerNames", payload)

    def stats_player_table(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.playerTable — JSON."
        return self._call("/v1/stats.playerTable", payload)

    def stats_position_ids_by_match(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.positionIdsByMatch — JSON."
        return self._call("/v1/stats.positionIdsByMatch", payload)

    def stats_position_ids_by_selection(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.positionIdsBySelection — JSON."
        return self._call("/v1/stats.positionIdsBySelection", payload)

    def stats_position_ids_by_tournament(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.positionIdsByTournament — JSON."
        return self._call("/v1/stats.positionIdsByTournament", payload)

    def stats_tournament_badges(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/stats.tournamentBadges — JSON."
        return self._call("/v1/stats.tournamentBadges", payload)

    def tournaments_add_match(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/tournaments.addMatch — JSON."
        return self._call("/v1/tournaments.addMatch", payload)

    def tournaments_create(self, payload: Optional[dict] = None, *, idempotency_key: Optional[str] = None) -> Optional[Any]:
        "POST /v1/tournaments.create — JSON. Accepts an Idempotency-Key."
        return self._call("/v1/tournaments.create", payload, idempotency_key=idempotency_key)

    def tournaments_delete(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/tournaments.delete — JSON."
        return self._call("/v1/tournaments.delete", payload)

    def tournaments_get(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/tournaments.get — JSON."
        return self._call("/v1/tournaments.get", payload)

    def tournaments_list(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/tournaments.list — NDJSON stream."
        return self._stream("/v1/tournaments.list", payload)

    def tournaments_matches(self, payload: Optional[dict] = None) -> Iterator[Any]:
        "POST /v1/tournaments.matches — NDJSON stream."
        return self._stream("/v1/tournaments.matches", payload)

    def tournaments_remove_match(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/tournaments.removeMatch — JSON."
        return self._call("/v1/tournaments.removeMatch", payload)

    def tournaments_reorder_matches(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/tournaments.reorderMatches — JSON."
        return self._call("/v1/tournaments.reorderMatches", payload)

    def tournaments_set_match_by_name(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/tournaments.setMatchByName — JSON."
        return self._call("/v1/tournaments.setMatchByName", payload)

    def tournaments_tournament_of(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/tournaments.tournamentOf — JSON."
        return self._call("/v1/tournaments.tournamentOf", payload)

    def tournaments_update(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/tournaments.update — JSON."
        return self._call("/v1/tournaments.update", payload)

    def tournaments_update_comment(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/tournaments.updateComment — JSON."
        return self._call("/v1/tournaments.updateComment", payload)

    def trash_count(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/trash.count — JSON."
        return self._call("/v1/trash.count", payload)

    def trash_delete_collection(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/trash.deleteCollection — JSON."
        return self._call("/v1/trash.deleteCollection", payload)

    def trash_delete_comment(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/trash.deleteComment — JSON."
        return self._call("/v1/trash.deleteComment", payload)

    def trash_delete_position(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/trash.deletePosition — JSON."
        return self._call("/v1/trash.deletePosition", payload)

    def trash_discard(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/trash.discard — JSON."
        return self._call("/v1/trash.discard", payload)

    def trash_empty(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/trash.empty — JSON."
        return self._call("/v1/trash.empty", payload)

    def trash_list(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/trash.list — JSON."
        return self._call("/v1/trash.list", payload)

    def trash_restore(self, payload: Optional[dict] = None) -> Optional[Any]:
        "POST /v1/trash.restore — JSON."
        return self._call("/v1/trash.restore", payload)
