// Code generated by cmd/calibrace; DO NOT EDIT BY HAND.
//
// Calibrated against gnubg_ts6x11.bd (TS-06-11), 300000 samples in the estimated regime
// (max(checkers) ≥ 7), 70/30 train/holdout split, seed 20260809.
// Regenerate (the oracle is the bearoff-data-1 release asset, never in git):
//
//	BLUNDERDB_TS11_PATH=/path/to/gnubg_ts6x11.bd go generate ./pkg/blunderdb/engine/race
//
// which runs the directive below; go generate passes the environment through.

//go:generate go run github.com/kevung/blunderdb/cmd/calibrace -out correction_coeffs.go

package race

const nCorrectionCoeffs = 32

// Holdout residual of the corrected estimator, in win-probability units.
// Valid on the oracle domain (≤ 11 checkers per side); an extrapolation
// beyond.
const (
	CorrectionSigma = 0.000442
	CorrectionP99   = 0.001730
	CorrectionMax   = 0.008925
)

var correctionCoeffs = [nCorrectionCoeffs]float64{
	-0.0002169150256196778,
	-0.003205496948687517,
	0.013213707289974109,
	-0.13662730032874393,
	0.5135760881145819,
	-0.8450737131315151,
	0.6493686502501006,
	-0.19075787422265636,
	0.0010374043484201758,
	0.027466885932774125,
	-0.02859983079389251,
	0.0002881641855491799,
	-0.03201655789550306,
	0.030862661814701087,
	-0.00013110426295195543,
	0.005522156572702108,
	-0.005339772809350867,
	-0.00016156363930873354,
	-0.004678814841877727,
	0.004961594494598261,
	0.000347736883795079,
	0.004596312333976014,
	-0.004925695247365837,
	-2.9733030828247268e-05,
	-0.0048795220761538435,
	0.004691528442047125,
	9.541506928957507e-05,
	0.0014432816971265948,
	-0.00154166590361172,
	4.06644770805777e-06,
	-0.001011883952863225,
	0.0009051017996487414,
}
