// Command calibrace calibrates the win-probability correction of
// pkg/blunderdb/engine/race against a TS-06-11 two-sided bearoff oracle
// (the bearoff-data-1 release asset; never committed to git).
//
// Usage:
//
//	BLUNDERDB_TS11_PATH=/path/to/gnubg_ts6x11.bd go run ./cmd/calibrace \
//	    -out pkg/blunderdb/engine/race/correction_coeffs.go
//
// It samples pairs of one-sided positions in the estimated regime
// (max(checkers) ≥ 7), fits the 32-coefficient least-squares correction on a
// train split, measures the residual on a disjoint holdout, and writes the
// frozen coefficients plus the measured bounds as Go source. Deterministic:
// same oracle, same output.
package main

import (
	"flag"
	"fmt"
	"math"
	"math/rand"
	"os"
	"sort"
	"time"

	"github.com/kevung/blunderdb/pkg/blunderdb/engine/race"
)

const nCoeffs = 32

func randBoard(rng *rand.Rand, n int) [6]int {
	var b [6]int
	for i := 0; i < n; i++ {
		b[rng.Intn(6)]++
	}
	return b
}

func main() {
	out := flag.String("out", "pkg/blunderdb/engine/race/correction_coeffs.go", "generated file path")
	samples := flag.Int("samples", 300000, "number of sampled position pairs")
	flag.Parse()

	path := os.Getenv("BLUNDERDB_TS11_PATH")
	if path == "" {
		fmt.Fprintln(os.Stderr, "BLUNDERDB_TS11_PATH not set (path to gnubg_ts6x11.bd)")
		os.Exit(2)
	}
	oracle, err := race.OpenTwoSided(path)
	if err != nil {
		fmt.Fprintln(os.Stderr, "open oracle:", err)
		os.Exit(1)
	}
	maxC := oracle.Checkers()
	fmt.Printf("oracle: %s (TS-06-%02d)\n", oracle.Origin(), maxC)

	rng := rand.New(rand.NewSource(20260809))
	start := time.Now()

	type sample struct {
		x   []float64
		err float64
	}
	var train, hold []sample
	for len(train)+len(hold) < *samples {
		nu, nt := 1+rng.Intn(maxC), 1+rng.Intn(maxC)
		if nu <= 6 && nt <= 6 {
			continue // exact regime, never estimated
		}
		us, them := randBoard(rng, nu), randBoard(rng, nt)
		entry, err := oracle.Lookup(us, them)
		if err != nil {
			fmt.Fprintln(os.Stderr, "lookup:", err)
			os.Exit(1)
		}
		praw, x, err := race.RawWinProbFeatures(us, them)
		if err != nil {
			fmt.Fprintln(os.Stderr, "features:", err)
			os.Exit(1)
		}
		s := sample{x: x, err: entry.WinProb - praw}
		if rng.Float64() < 0.7 {
			train = append(train, s)
		} else {
			hold = append(hold, s)
		}
	}
	fmt.Printf("sampled %d (train %d, holdout %d) in %v\n",
		*samples, len(train), len(hold), time.Since(start).Round(time.Millisecond))

	// Normal equations XtX c = Xty, solved by Gaussian elimination with
	// partial pivoting. 32×32: numerically comfortable.
	var xtx [nCoeffs][nCoeffs]float64
	var xty [nCoeffs]float64
	for _, s := range train {
		for i := 0; i < nCoeffs; i++ {
			xi := s.x[i]
			xty[i] += xi * s.err
			for j := i; j < nCoeffs; j++ {
				xtx[i][j] += xi * s.x[j]
			}
		}
	}
	for i := 0; i < nCoeffs; i++ {
		for j := 0; j < i; j++ {
			xtx[i][j] = xtx[j][i]
		}
	}
	coeffs, ok := solve(xtx, xty)
	if !ok {
		fmt.Fprintln(os.Stderr, "singular system")
		os.Exit(1)
	}

	// Holdout residuals.
	res := make([]float64, len(hold))
	for k, s := range hold {
		c := 0.0
		for i := 0; i < nCoeffs; i++ {
			c += coeffs[i] * s.x[i]
		}
		res[k] = math.Abs(s.err - c)
	}
	sort.Float64s(res)
	var sq float64
	for _, r := range res {
		sq += r * r
	}
	sigma := math.Sqrt(sq / float64(len(res)))
	p99 := res[int(0.99*float64(len(res)))]
	maxAbs := res[len(res)-1]
	fmt.Printf("holdout: sigma %.6f  p99 %.6f  max %.6f (win-prob units)\n", sigma, p99, maxAbs)

	f, err := os.Create(*out)
	if err != nil {
		fmt.Fprintln(os.Stderr, "create:", err)
		os.Exit(1)
	}
	defer f.Close()
	fmt.Fprintf(f, `// Code generated by cmd/calibrace; DO NOT EDIT BY HAND.
//
// Calibrated against %s (TS-06-%02d), %d samples in the estimated regime
// (max(checkers) ≥ 7), 70/30 train/holdout split, seed 20260809.
// Regenerate: BLUNDERDB_TS11_PATH=… go run ./cmd/calibrace -out %s

package race

const nCorrectionCoeffs = %d

// Holdout residual of the corrected estimator, in win-probability units.
// Valid on the oracle domain (≤ %d checkers per side); an extrapolation
// beyond.
const (
	CorrectionSigma = %.6f
	CorrectionP99   = %.6f
	CorrectionMax   = %.6f
)

var correctionCoeffs = [nCorrectionCoeffs]float64{
`, race.DownloadedFileName, maxC, *samples, *out, nCoeffs, maxC, sigma, p99, maxAbs)
	for _, c := range coeffs {
		fmt.Fprintf(f, "\t%v,\n", c)
	}
	fmt.Fprintln(f, "}")
	fmt.Println("wrote", *out)
}

func solve(a [nCoeffs][nCoeffs]float64, b [nCoeffs]float64) ([nCoeffs]float64, bool) {
	n := nCoeffs
	for col := 0; col < n; col++ {
		piv := col
		for r := col + 1; r < n; r++ {
			if math.Abs(a[r][col]) > math.Abs(a[piv][col]) {
				piv = r
			}
		}
		if math.Abs(a[piv][col]) < 1e-12 {
			return b, false
		}
		a[col], a[piv] = a[piv], a[col]
		b[col], b[piv] = b[piv], b[col]
		inv := 1.0 / a[col][col]
		for r := col + 1; r < n; r++ {
			f := a[r][col] * inv
			if f == 0 {
				continue
			}
			for c := col; c < n; c++ {
				a[r][c] -= f * a[col][c]
			}
			b[r] -= f * b[col]
		}
	}
	var x [nCoeffs]float64
	for i := n - 1; i >= 0; i-- {
		s := b[i]
		for j := i + 1; j < n; j++ {
			s -= a[i][j] * x[j]
		}
		x[i] = s / a[i][i]
	}
	return x, true
}
