package report

// labels holds the report block of frontend/src/i18n/locales/<lang>.json, one
// map per language; labels_test.go fails when a catalogue drifts from it.
var labels = map[string]map[string]string{
	"fr": {
		"title":     "Rapport blunderDB",
		"generated": "Établi le {date}",
		"positions": "Positions",
		"matches":   "Matchs",
		"decisions": "Décisions comptées",
		"prGlobal":  "PR global",
		"prChecker": "PR pions",
		"prCube":    "PR videau",
		"worst":     "Les dix décisions les plus coûteuses",
		"noBlunder": "Aucune décision fautive dans ce périmètre.",
		"checker":   "Coup de pions",
		"cube":      "Décision de videau",
		"bestMove":  "Meilleur coup :",
		"footer":    "Document autonome établi par blunderDB. Imprimez-le en PDF depuis votre navigateur.",
	},
	"en": {
		"title":     "blunderDB report",
		"generated": "Produced on {date}",
		"positions": "Positions",
		"matches":   "Matches",
		"decisions": "Counted decisions",
		"prGlobal":  "Global PR",
		"prChecker": "Checker PR",
		"prCube":    "Cube PR",
		"worst":     "The ten most expensive decisions",
		"noBlunder": "No faulty decision in this scope.",
		"checker":   "Checker play",
		"cube":      "Cube decision",
		"bestMove":  "Best move:",
		"footer":    "Self-contained document produced by blunderDB. Print it to PDF from your browser.",
	},
	"de": {
		"title":     "blunderDB-Bericht",
		"generated": "Erstellt am {date}",
		"positions": "Stellungen",
		"matches":   "Matches",
		"decisions": "Gezählte Entscheidungen",
		"prGlobal":  "PR gesamt",
		"prChecker": "PR Steine",
		"prCube":    "PR Würfel",
		"worst":     "Die zehn teuersten Entscheidungen",
		"noBlunder": "Keine fehlerhafte Entscheidung in diesem Bereich.",
		"checker":   "Steinzug",
		"cube":      "Würfelentscheidung",
		"bestMove":  "Bester Zug:",
		"footer":    "Eigenständiges Dokument von blunderDB. Drucken Sie es aus Ihrem Browser als PDF.",
	},
	"el": {
		"title":     "Αναφορά blunderDB",
		"generated": "Συντάχθηκε στις {date}",
		"positions": "Θέσεις",
		"matches":   "Αγώνες",
		"decisions": "Μετρημένες αποφάσεις",
		"prGlobal":  "Συνολικό PR",
		"prChecker": "PR κινήσεων",
		"prCube":    "PR κύβου",
		"worst":     "Οι δέκα πιο ακριβές αποφάσεις",
		"noBlunder": "Καμία εσφαλμένη απόφαση σε αυτό το εύρος.",
		"checker":   "Κίνηση πουλιών",
		"cube":      "Απόφαση κύβου",
		"bestMove":  "Καλύτερη κίνηση:",
		"footer":    "Αυτόνομο έγγραφο από το blunderDB. Τυπώστε το σε PDF από τον περιηγητή σας.",
	},
	"es": {
		"title":     "Informe blunderDB",
		"generated": "Elaborado el {date}",
		"positions": "Posiciones",
		"matches":   "Partidos",
		"decisions": "Decisiones contadas",
		"prGlobal":  "PR global",
		"prChecker": "PR fichas",
		"prCube":    "PR cubo",
		"worst":     "Las diez decisiones más costosas",
		"noBlunder": "Ninguna decisión errónea en este ámbito.",
		"checker":   "Jugada de fichas",
		"cube":      "Decisión de cubo",
		"bestMove":  "Mejor jugada:",
		"footer":    "Documento autónomo elaborado por blunderDB. Imprímalo en PDF desde su navegador.",
	},
	"fi": {
		"title":     "blunderDB-raportti",
		"generated": "Laadittu {date}",
		"positions": "Asemat",
		"matches":   "Ottelut",
		"decisions": "Lasketut päätökset",
		"prGlobal":  "Kokonais-PR",
		"prChecker": "Siirtojen PR",
		"prCube":    "Kuution PR",
		"worst":     "Kymmenen kalleinta päätöstä",
		"noBlunder": "Ei virheellisiä päätöksiä tällä alueella.",
		"checker":   "Nappulasiirto",
		"cube":      "Kuutiopäätös",
		"bestMove":  "Paras siirto:",
		"footer":    "blunderDB:n laatima itsenäinen asiakirja. Tulosta se PDF:ksi selaimestasi.",
	},
	"it": {
		"title":     "Rapporto blunderDB",
		"generated": "Redatto il {date}",
		"positions": "Posizioni",
		"matches":   "Incontri",
		"decisions": "Decisioni contate",
		"prGlobal":  "PR globale",
		"prChecker": "PR pedine",
		"prCube":    "PR cubo",
		"worst":     "Le dieci decisioni più costose",
		"noBlunder": "Nessuna decisione errata in questo perimetro.",
		"checker":   "Mossa di pedine",
		"cube":      "Decisione di cubo",
		"bestMove":  "Mossa migliore:",
		"footer":    "Documento autonomo redatto da blunderDB. Stampatelo in PDF dal vostro browser.",
	},
	"ja": {
		"title":     "blunderDB レポート",
		"generated": "作成日時：{date}",
		"positions": "局面",
		"matches":   "マッチ",
		"decisions": "計上した判断",
		"prGlobal":  "総合 PR",
		"prChecker": "チェッカー PR",
		"prCube":    "キューブ PR",
		"worst":     "最も損失の大きい 10 の判断",
		"noBlunder": "この範囲に誤った判断はありません。",
		"checker":   "チェッカープレイ",
		"cube":      "キューブ判断",
		"bestMove":  "最善手：",
		"footer":    "blunderDB が作成した自己完結の文書です。ブラウザから PDF に印刷できます。",
	},
	"ru": {
		"title":     "Отчёт blunderDB",
		"generated": "Составлен {date}",
		"positions": "Позиции",
		"matches":   "Матчи",
		"decisions": "Учтённые решения",
		"prGlobal":  "Общий PR",
		"prChecker": "PR ходов",
		"prCube":    "PR куба",
		"worst":     "Десять самых дорогих решений",
		"noBlunder": "В этом объёме нет ошибочных решений.",
		"checker":   "Ход шашками",
		"cube":      "Решение о кубе",
		"bestMove":  "Лучший ход:",
		"footer":    "Самодостаточный документ, составленный blunderDB. Распечатайте его в PDF из браузера.",
	},
}
