package cli

import (
	"flag"
	"fmt"
	"sort"
	"strings"
)

// runCompletion prints a shell completion script for bash, zsh, or fish
// (#176, B.8). The command list embedded in every script comes from
// commandNames(), which reads handlers() — the single source of truth
// CLAUDE.md requires (main.go's IsCommand asks the same table) — so a new
// subcommand is offered by completion the moment it is wired there, with
// nothing to keep in sync by hand.
func (cli *CLI) runCompletion(args []string) error {
	completionCmd := flag.NewFlagSet("completion", flag.ContinueOnError)
	completionCmd.Usage = func() {
		fmt.Println("Usage: blunderdb completion <bash|zsh|fish>")
		fmt.Println()
		fmt.Println("Print a shell completion script for the subcommand names to stdout.")
		fmt.Println()
		fmt.Println("Examples:")
		fmt.Println("  # bash: load for the current shell session")
		fmt.Println("  source <(blunderdb completion bash)")
		fmt.Println()
		fmt.Println("  # bash: install system-wide (Debian/Ubuntu/Arch layout)")
		fmt.Println("  blunderdb completion bash | sudo tee /etc/bash_completion.d/blunderdb > /dev/null")
		fmt.Println()
		fmt.Println("  # zsh: install into a directory already on $fpath")
		fmt.Println("  blunderdb completion zsh > \"${fpath[1]}/_blunderdb\"")
		fmt.Println()
		fmt.Println("  # fish: load for the current shell session")
		fmt.Println("  blunderdb completion fish | source")
	}
	if err := completionCmd.Parse(args); err != nil {
		return err
	}
	if completionCmd.NArg() != 1 {
		completionCmd.Usage()
		return fmt.Errorf("expected exactly one shell name: bash, zsh, or fish")
	}

	commands := cli.commandNames()

	switch strings.ToLower(completionCmd.Arg(0)) {
	case "bash":
		fmt.Print(bashCompletionScript(commands))
	case "zsh":
		fmt.Print(zshCompletionScript(commands))
	case "fish":
		fmt.Print(fishCompletionScript(commands))
	default:
		return fmt.Errorf("unknown shell: %s (must be 'bash', 'zsh', or 'fish')", completionCmd.Arg(0))
	}
	return nil
}

// commandNames returns every top-level word blunderdb accepts after its
// binary name: the CLI subcommands from handlers() (completion, registered
// there like every other command, included), plus the three headless
// commands (serve, call, migrate) that main.go dispatches before a CLI
// command is ever looked up — from a user's shell they are typed the exact
// same way, so completion offers all of them. Sorted for a stable,
// human-readable script (map iteration order is not).
func (cli *CLI) commandNames() []string {
	handlers := cli.handlers()
	names := make([]string, 0, len(handlers)+3)
	for name := range handlers {
		names = append(names, name)
	}
	names = append(names, "serve", "call", "migrate")
	sort.Strings(names)
	return names
}

// bashCompletionScript returns a completion function offering commands as
// the first word after `blunderdb`/`blunderDB` (both names are installed —
// see CLAUDE.md's Release Process — and share one completion function).
func bashCompletionScript(commands []string) string {
	return fmt.Sprintf(`# bash completion for blunderdb — generated by "blunderdb completion bash"
_blunderdb_completions() {
    local cur
    cur="${COMP_WORDS[COMP_CWORD]}"
    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "%s" -- "$cur") )
    fi
}
complete -F _blunderdb_completions blunderdb
complete -F _blunderdb_completions blunderDB
`, strings.Join(commands, " "))
}

// zshCompletionScript returns a #compdef completion function.
func zshCompletionScript(commands []string) string {
	return fmt.Sprintf(`#compdef blunderdb blunderDB
# zsh completion for blunderdb — generated by "blunderdb completion zsh"
_blunderdb() {
    local -a commands
    commands=(%s)
    _describe 'command' commands
}
compdef _blunderdb blunderdb
compdef _blunderdb blunderDB
`, strings.Join(commands, " "))
}

// fishCompletionScript returns fish complete(1) directives.
func fishCompletionScript(commands []string) string {
	joined := strings.Join(commands, " ")
	return fmt.Sprintf(`# fish completion for blunderdb — generated by "blunderdb completion fish"
set -l __blunderdb_commands %s
complete -c blunderdb -f -n "not __fish_seen_subcommand_from $__blunderdb_commands" -a "$__blunderdb_commands"
complete -c blunderDB -f -n "not __fish_seen_subcommand_from $__blunderdb_commands" -a "$__blunderdb_commands"
`, joined)
}
