package openapigen

import (
	"fmt"
	"sort"
	"strings"
)

// The generated half of the Python client (issue #289, fiche I.33).
//
// One method per route, generated from the SAME route table that produces
// openapi.yaml and the documentation annex. A hand-written client would drift
// the day a route is added and nobody would notice until a user did; this one
// cannot, because `go run ./cmd/openapi-gen` rewrites it and
// openapigen_test.go fails the build while it is stale.
//
// The transport — the session, the tenant header, the error envelope, the
// NDJSON decode — is hand-written in clients/python/blunderdb/client.py. That
// split is the point: what changes with the API is generated, what changes
// with judgement is written.

// pythonHeader is the file's preamble. It carries the same "do not edit"
// warning as the other generated files, for the same reason.
const pythonHeader = `# Generated by ` + "`go run ./cmd/openapi-gen`" + ` from internal/server's route
# table. DO NOT EDIT BY HAND; regenerate instead. The transport lives in
# client.py, which is hand-written: what changes with the API is generated,
# what changes with judgement is not.
#
# Every method is one ` + "`POST /v1/<family>.<method>`" + ` call. A method whose route
# streams NDJSON returns an iterator of decoded objects; every other method
# returns the decoded JSON body (None when the route answers with no content).
"""blunderDB engine API — generated method surface."""

from __future__ import annotations

from typing import Any, Iterator, Optional

from .client import BaseClient


class GeneratedAPI(BaseClient):
    """One method per route. Mixed into Client (client.py)."""
`

// GeneratePythonClient renders the generated half of the Python client.
func GeneratePythonClient(model *Model) string {
	routes := append([]Route(nil), model.Routes...)
	sort.Slice(routes, func(i, j int) bool { return routes[i].Pattern < routes[j].Pattern })

	var b strings.Builder
	b.WriteString(pythonHeader)

	seen := map[string]bool{}
	for _, r := range routes {
		name := pythonMethodName(r)
		if seen[name] {
			// Two routes cannot share a Python name; if they ever do, the
			// generator must say so rather than silently drop one.
			b.WriteString(fmt.Sprintf("\n    # NAME COLLISION on %s (%s) — rename one route.\n", name, r.Pattern))
			continue
		}
		seen[name] = true
		writePythonMethod(&b, r, name)
	}
	return b.String()
}

// writePythonMethod renders one route.
func writePythonMethod(b *strings.Builder, r Route, name string) {
	stream := r.Kind == kindStream
	ret := "Optional[Any]"
	if stream {
		ret = "Iterator[Any]"
	}

	args := "self, payload: Optional[dict] = None"
	if r.IdempotencyKeySupported {
		args += ", *, idempotency_key: Optional[str] = None"
	}

	fmt.Fprintf(b, "\n    def %s(%s) -> %s:\n", name, args, ret)
	fmt.Fprintf(b, "        %s\n", pythonDocstring(r))
	if r.IdempotencyKeySupported {
		fmt.Fprintf(b, "        return self._%s(%q, payload, idempotency_key=idempotency_key)\n", callVerb(stream), r.Pattern)
		return
	}
	fmt.Fprintf(b, "        return self._%s(%q, payload)\n", callVerb(stream), r.Pattern)
}

func callVerb(stream bool) string {
	if stream {
		return "stream"
	}
	return "call"
}

// pythonDocstring says what the route is and what it answers with. It stays a
// single line: the full contract is in openapi.yaml, and a client that
// paraphrased it would be a second contract to keep in step.
func pythonDocstring(r Route) string {
	shape := "JSON"
	if r.Kind == kindStream {
		shape = "NDJSON stream"
	} else if r.Kind == kindCustom {
		shape = "hand-written handler — see openapi.yaml"
	}
	extra := ""
	if r.IdempotencyKeySupported {
		extra = " Accepts an Idempotency-Key."
	}
	return fmt.Sprintf("%q", fmt.Sprintf("%s %s — %s.%s", r.Method, r.Pattern, shape, extra))
}

// pythonMethodName turns "/v1/positions.saveIndividual" into
// "positions_save_individual": the family, then the operation in snake_case.
// The family is kept because two families legitimately share an operation
// name (`list`, `delete`), and a bare `list()` would collide.
func pythonMethodName(r Route) string {
	return snakeCase(r.Family) + "_" + snakeCase(r.Op)
}

// snakeCase lowers a camelCase identifier, inserting an underscore before each
// capital. Digits stay attached to what precedes them ("fromXGID" →
// "from_xgid"), and a run of capitals is one word.
func snakeCase(s string) string {
	var b strings.Builder
	runes := []rune(s)
	for i, r := range runes {
		if r >= 'A' && r <= 'Z' {
			prevLower := i > 0 && runes[i-1] >= 'a' && runes[i-1] <= 'z'
			nextLower := i+1 < len(runes) && runes[i+1] >= 'a' && runes[i+1] <= 'z'
			if i > 0 && (prevLower || nextLower) {
				b.WriteByte('_')
			}
			b.WriteRune(r - 'A' + 'a')
			continue
		}
		if r == '.' || r == '-' {
			b.WriteByte('_')
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}
