package openapigen

import (
	"fmt"
	"strings"
)

// openAPIHeader is fixed prose so a reader of openapi.yaml sees the security
// model (ADR-0005) and the idempotency contract without the Sphinx annex.
const openAPIHeader = `# Generated by ` + "`go run ./cmd/openapi-gen`" + ` from internal/server's route table
# (internal/server/openapigen parses handlers_*.go's Go source directly —
# see that package's doc comment for why: generic type parameters are not
# recoverable from a running binary). DO NOT EDIT BY HAND; regenerate
# instead. openapigen_test.go's TestGeneratedFilesAreUpToDate fails the
# build the day this file goes stale.
openapi: 3.0.3
info:
  title: blunderDB engine API
  version: "1"
  description: >-
    POST /v1/<family>.<method> over HTTP + JSON (NDJSON for a streaming
    list). SECURITY: this daemon performs NO authentication of its own — it
    trusts the X-Tenant-ID request header verbatim and MUST run behind an
    authenticating reverse-proxy (see ADR-0005 and doc/source/mode_headless.rst).
    X-Tenant-ID is the tenant's positive decimal integer; a name is refused
    with 400 invalid, never mapped to a tenant by this daemon. Idempotency:
    positions.save (and every other positions.* write) is naturally
    idempotent through its Zobrist content hash — saving the same position
    twice returns the same row, never a duplicate. collections.create,
    tournaments.create and anki.reviewCard have no such natural key (two
    calls are two distinct effects) and instead accept an optional
    Idempotency-Key request header (marked "x-idempotency-key: true" below):
    a retried call carrying the same key replays the first attempt's result
    instead of repeating its effect. Every other route neither needs nor
    accepts that header.
servers:
  - url: /v1
`

// eventsPathItem documents GET /v1/events by hand: the route is no POST
// /v1/<family>.<method> call and is registered outside handlers_*.go
// (internal/server/events.go), so the parser does not see it.
const eventsPathItem = `  /v1/events:
    get:
      operationId: events
      tags: [events]
      x-kind: sse
      x-streaming: true
      description: >-
        Server-Sent Events: one message per committed gesture of the caller's
        tenant (Direction, Rencontre, transcription), naming what moved and its
        new version or revision — never the state; read it again with
        If-None-Match. Served only under serve --direction or --transcription.
        No history is kept: every stream opens with event resync (reason
        "reconnected" under Last-Event-ID, "subscribed" otherwise), and a
        subscriber dropped for falling behind receives one too; the client then
        reads everything again. A ": ping" comment every 25 s keeps proxies from closing the
        stream. Over PostgreSQL the daemons sharing the database relay their gestures to one
        another (LISTEN/NOTIFY); stream ids are local to one daemon, and one that lost its
        listener sends resync "missed" to its subscribers.
      parameters:
        - name: tournament
          in: query
          required: false
          description: Direction ids, comma-separated; a Direction in a Rencontre hears its room.
          schema:
            type: string
        - name: rencontre
          in: query
          required: false
          description: Rencontre ids, comma-separated.
          schema:
            type: string
        - name: transcription
          in: query
          required: false
          description: Draft ids, comma-separated.
          schema:
            type: string
        - name: Last-Event-ID
          in: header
          required: false
          description: The id of the last event seen; the opening resync then says "reconnected".
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            text/event-stream:
              schema:
                description: >-
                  Frames "id", "event" (direction, rencontre, transcription,
                  resync) and "data", one JSON object shaped as below.
                type: object
                properties:
                  kind:
                    type: string
                    enum: [direction, rencontre, transcription, resync]
                  tournamentId:
                    type: integer
                    format: int64
                  tournamentIds:
                    type: array
                    items:
                      type: integer
                      format: int64
                  rencontreId:
                    type: integer
                    format: int64
                  transcriptionId:
                    type: integer
                    format: int64
                  version:
                    type: string
                  revision:
                    type: integer
                    format: int64
                  removed:
                    type: boolean
                  matchId:
                    type: integer
                    format: int64
                  reason:
                    type: string
        "400":
          description: An unknown parameter or an invalid id, or no X-Tenant-ID.
        "404":
          description: Neither --direction nor --transcription — nothing this daemon writes would be announced, and the route is absent.
        "429":
          description: The tenant already holds its maximum of open streams (16).
        "503":
          description: The daemon is stopping.
`

// Generate renders model as an OpenAPI 3.0.3 YAML document.
func GenerateOpenAPI(model *Model) string {
	comps := newComponents()
	var b strings.Builder
	b.WriteString(openAPIHeader)
	b.WriteString("paths:\n")

	for _, r := range model.Routes {
		writePathItem(&b, r, model.Types, comps)
	}
	b.WriteString(eventsPathItem)

	writeComponents(&b, comps)
	return b.String()
}

func writePathItem(b *strings.Builder, r Route, types map[string]typeInfo, comps *Components) {
	fmt.Fprintf(b, "  %s:\n", yamlPlainOrQuoted(r.Pattern))
	fmt.Fprintf(b, "    %s:\n", strings.ToLower(r.Method))
	fmt.Fprintf(b, "      operationId: %s\n", yamlPlainOrQuoted(strings.TrimPrefix(strings.TrimPrefix(r.Pattern, "/v1/"), "/ops/")))
	fmt.Fprintf(b, "      tags: [%s]\n", r.Family)
	fmt.Fprintf(b, "      x-kind: %s\n", r.Kind)
	if r.IdempotencyKeySupported {
		b.WriteString("      x-idempotency-key: true\n")
	}
	if r.IfMatchRequired {
		b.WriteString("      x-if-match: required\n")
	}
	if r.Kind == kindStream {
		b.WriteString("      x-streaming: true\n")
	}
	if r.Conditional || r.IfMatchRequired || r.IdempotencyKeySupported {
		b.WriteString("      parameters:\n")
	}
	if r.IfMatchRequired {
		b.WriteString("        - name: If-Match\n")
		b.WriteString("          in: header\n")
		b.WriteString("          required: true\n")
		b.WriteString("          description: The version the gesture was decided on, as the last read gave it; 428 without it, 409 when it moved.\n")
		b.WriteString("          schema:\n")
		b.WriteString("            type: string\n")
	}
	if r.IdempotencyKeySupported {
		b.WriteString("        - name: Idempotency-Key\n")
		b.WriteString("          in: header\n")
		b.WriteString("          required: false\n")
		b.WriteString("          description: A key the client draws per gesture; a retry under it replays the first answer instead of writing again.\n")
		b.WriteString("          schema:\n")
		b.WriteString("            type: string\n")
	}
	if r.Conditional {
		b.WriteString("        - name: If-None-Match\n")
		b.WriteString("          in: header\n")
		b.WriteString("          required: false\n")
		b.WriteString("          description: An ETag of an earlier answer; 304 while it still holds.\n")
		b.WriteString("          schema:\n")
		b.WriteString("            type: string\n")
	}

	if reqSchema := resolveSchema(r.ReqType, types, comps); reqSchema != nil {
		b.WriteString("      requestBody:\n")
		b.WriteString("        content:\n")
		b.WriteString("          application/json:\n")
		b.WriteString("            schema:\n")
		writeSchema(b, reqSchema, 14)
	}

	b.WriteString("      responses:\n")
	if r.Conditional {
		b.WriteString("        \"304\":\n")
		b.WriteString("          description: Not Modified — the If-None-Match tag still holds; no body.\n")
	}
	if r.Gesture {
		b.WriteString("        \"409\":\n")
		b.WriteString("          description: Conflict — the If-Match version moved; error.details holds the fresh state and its version.\n")
		b.WriteString("        \"428\":\n")
		b.WriteString("          description: Precondition Required — no usable If-Match.\n")
	}
	b.WriteString("        \"200\":\n")
	b.WriteString("          description: OK\n")
	if r.Gesture {
		b.WriteString("          headers:\n")
		b.WriteString("            Direction-Version:\n")
		b.WriteString("              description: The version the gesture left; the If-Match of the next one.\n")
		b.WriteString("              schema:\n")
		b.WriteString("                type: string\n")
		b.WriteString("            Direction-Page-Warning:\n")
		b.WriteString("              description: A display page the gesture applied but could not rewrite, once per page.\n")
		b.WriteString("              schema:\n")
		b.WriteString("                type: string\n")
	}
	if r.Conditional {
		b.WriteString("          headers:\n")
		b.WriteString("            ETag:\n")
		b.WriteString("              description: Weak tag of this answer; send it back in If-None-Match.\n")
		b.WriteString("              schema:\n")
		b.WriteString("                type: string\n")
	}
	switch r.Kind {
	case kindStream:
		itemSchema := resolveSchema(r.ItemType, types, comps)
		b.WriteString("          content:\n")
		b.WriteString("            application/x-ndjson:\n")
		b.WriteString("              schema:\n")
		b.WriteString("                description: One JSON object per line (NDJSON), each shaped as below.\n")
		if itemSchema != nil {
			writeSchema(b, itemSchema, 16)
		}
	case kindJSON:
		respSchema := resolveSchema(r.RespType, types, comps)
		if respSchema != nil {
			b.WriteString("          content:\n")
			b.WriteString("            application/json:\n")
			b.WriteString("              schema:\n")
			writeSchema(b, respSchema, 16)
		}
	default:
		b.WriteString("          description: >-\n")
		b.WriteString("            Custom, hand-written handler; response shape not derived from this\n")
		b.WriteString("            generator's source analysis (a file upload/download, or a route\n")
		b.WriteString("            registered from a runtime table) — see internal/server for the actual\n")
		b.WriteString("            implementation.\n")
	}
}

// writeSchema writes s at the given indent (spaces), as a YAML mapping —
// either a bare "$ref" or the full inline object/array/scalar shape.
func writeSchema(b *strings.Builder, s *Schema, indent int) {
	pad := strings.Repeat(" ", indent)
	if s.Ref != "" {
		fmt.Fprintf(b, "%s$ref: %s\n", pad, yamlPlainOrQuoted(s.Ref))
		if s.Nullable {
			fmt.Fprintf(b, "%snullable: true\n", pad)
		}
		return
	}
	fmt.Fprintf(b, "%stype: %s\n", pad, s.Type)
	if s.Format != "" {
		fmt.Fprintf(b, "%sformat: %s\n", pad, s.Format)
	}
	if s.Nullable {
		fmt.Fprintf(b, "%snullable: true\n", pad)
	}
	if s.Description != "" {
		fmt.Fprintf(b, "%sdescription: %s\n", pad, yamlPlainOrQuoted(s.Description))
	}
	if s.Items != nil {
		fmt.Fprintf(b, "%sitems:\n", pad)
		writeSchema(b, s.Items, indent+2)
	}
	if s.AdditionalProperties != nil {
		fmt.Fprintf(b, "%sadditionalProperties:\n", pad)
		writeSchema(b, s.AdditionalProperties, indent+2)
	}
	if len(s.PropOrder) > 0 {
		fmt.Fprintf(b, "%sproperties:\n", pad)
		for _, name := range s.PropOrder {
			fmt.Fprintf(b, "%s  %s:\n", pad, yamlKey(name))
			writeSchema(b, s.Properties[name], indent+4)
		}
	}
}

func writeComponents(b *strings.Builder, comps *Components) {
	names := comps.Names()
	if len(names) == 0 {
		return
	}
	b.WriteString("components:\n")
	b.WriteString("  schemas:\n")
	for _, name := range names {
		fmt.Fprintf(b, "    %s:\n", yamlKey(name))
		writeSchema(b, comps.Get(name), 6)
	}
}

// yamlPlainOrQuoted leaves a scalar bare when made of characters plain YAML
// never misreads (paths, operationIds) and quotes anything else — notably a
// "#/components/..." $ref, whose "#" would start a comment.
func yamlPlainOrQuoted(s string) string {
	safe := true
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
		case strings.ContainsRune("/._-", r):
		default:
			safe = false
		}
	}
	if safe && s != "" {
		return s
	}
	return quoteYAML(s)
}

// yamlKey renders a mapping key the same way: a JSON field name may hold
// characters plain YAML rejects.
func yamlKey(s string) string {
	return yamlPlainOrQuoted(s)
}
