package openapigen

import (
	"fmt"
	"strings"
)

// openAPIHeader is prose that never changes between generations — a
// reader landing on openapi.yaml directly (not through the Sphinx annex)
// needs the security model and idempotency story right there, since ADR-0005
// and #236 are exactly the kind of thing an API consumer must not miss.
const openAPIHeader = `# Generated by ` + "`go run ./cmd/openapi-gen`" + ` from internal/server's route table
# (internal/server/openapigen parses handlers_*.go's Go source directly —
# see that package's doc comment for why: generic type parameters are not
# recoverable from a running binary). DO NOT EDIT BY HAND; regenerate
# instead. openapigen_test.go's TestGeneratedFilesAreUpToDate fails the
# build the day this file goes stale.
openapi: 3.0.3
info:
  title: blunderDB engine API
  version: "1"
  description: >-
    POST /v1/<family>.<method> over HTTP + JSON (NDJSON for a streaming
    list). SECURITY: this daemon performs NO authentication of its own — it
    trusts the X-Tenant-ID request header verbatim and MUST run behind an
    authenticating reverse-proxy (see ADR-0005 and doc/source/mode_headless.rst).
    X-Tenant-ID is the tenant's positive decimal integer; a name is refused
    with 400 invalid, never mapped to a tenant by this daemon. Idempotency:
    positions.save (and every other positions.* write) is naturally
    idempotent through its Zobrist content hash — saving the same position
    twice returns the same row, never a duplicate. collections.create,
    tournaments.create and anki.reviewCard have no such natural key (two
    calls are two distinct effects) and instead accept an optional
    Idempotency-Key request header (marked "x-idempotency-key: true" below):
    a retried call carrying the same key replays the first attempt's result
    instead of repeating its effect. Every other route neither needs nor
    accepts that header.
servers:
  - url: /v1
`

// Generate renders model as an OpenAPI 3.0.3 YAML document.
func GenerateOpenAPI(model *Model) string {
	comps := newComponents()
	var b strings.Builder
	b.WriteString(openAPIHeader)
	b.WriteString("paths:\n")

	for _, r := range model.Routes {
		writePathItem(&b, r, model.Types, comps)
	}

	writeComponents(&b, comps)
	return b.String()
}

func writePathItem(b *strings.Builder, r Route, types map[string]typeInfo, comps *Components) {
	fmt.Fprintf(b, "  %s:\n", yamlPlainOrQuoted(r.Pattern))
	fmt.Fprintf(b, "    %s:\n", strings.ToLower(r.Method))
	fmt.Fprintf(b, "      operationId: %s\n", yamlPlainOrQuoted(strings.TrimPrefix(strings.TrimPrefix(r.Pattern, "/v1/"), "/ops/")))
	fmt.Fprintf(b, "      tags: [%s]\n", r.Family)
	fmt.Fprintf(b, "      x-kind: %s\n", r.Kind)
	if r.IdempotencyKeySupported {
		b.WriteString("      x-idempotency-key: true\n")
	}
	if r.Kind == kindStream {
		b.WriteString("      x-streaming: true\n")
	}

	if reqSchema := resolveSchema(r.ReqType, types, comps); reqSchema != nil {
		b.WriteString("      requestBody:\n")
		b.WriteString("        content:\n")
		b.WriteString("          application/json:\n")
		b.WriteString("            schema:\n")
		writeSchema(b, reqSchema, 14)
	}

	b.WriteString("      responses:\n")
	b.WriteString("        \"200\":\n")
	b.WriteString("          description: OK\n")
	switch r.Kind {
	case kindStream:
		itemSchema := resolveSchema(r.ItemType, types, comps)
		b.WriteString("          content:\n")
		b.WriteString("            application/x-ndjson:\n")
		b.WriteString("              schema:\n")
		b.WriteString("                description: One JSON object per line (NDJSON), each shaped as below.\n")
		if itemSchema != nil {
			writeSchema(b, itemSchema, 16)
		}
	case kindJSON:
		respSchema := resolveSchema(r.RespType, types, comps)
		if respSchema != nil {
			b.WriteString("          content:\n")
			b.WriteString("            application/json:\n")
			b.WriteString("              schema:\n")
			writeSchema(b, respSchema, 16)
		}
	default:
		b.WriteString("          description: >-\n")
		b.WriteString("            Custom, hand-written handler; response shape not derived from this\n")
		b.WriteString("            generator's source analysis (a file upload/download, or a route\n")
		b.WriteString("            registered from a runtime table) — see internal/server for the actual\n")
		b.WriteString("            implementation.\n")
	}
}

// writeSchema writes s at the given indent (spaces), as a YAML mapping —
// either a bare "$ref" or the full inline object/array/scalar shape.
func writeSchema(b *strings.Builder, s *Schema, indent int) {
	pad := strings.Repeat(" ", indent)
	if s.Ref != "" {
		fmt.Fprintf(b, "%s$ref: %s\n", pad, yamlPlainOrQuoted(s.Ref))
		if s.Nullable {
			fmt.Fprintf(b, "%snullable: true\n", pad)
		}
		return
	}
	fmt.Fprintf(b, "%stype: %s\n", pad, s.Type)
	if s.Format != "" {
		fmt.Fprintf(b, "%sformat: %s\n", pad, s.Format)
	}
	if s.Nullable {
		fmt.Fprintf(b, "%snullable: true\n", pad)
	}
	if s.Description != "" {
		fmt.Fprintf(b, "%sdescription: %s\n", pad, yamlPlainOrQuoted(s.Description))
	}
	if s.Items != nil {
		fmt.Fprintf(b, "%sitems:\n", pad)
		writeSchema(b, s.Items, indent+2)
	}
	if s.AdditionalProperties != nil {
		fmt.Fprintf(b, "%sadditionalProperties:\n", pad)
		writeSchema(b, s.AdditionalProperties, indent+2)
	}
	if len(s.PropOrder) > 0 {
		fmt.Fprintf(b, "%sproperties:\n", pad)
		for _, name := range s.PropOrder {
			fmt.Fprintf(b, "%s  %s:\n", pad, yamlKey(name))
			writeSchema(b, s.Properties[name], indent+4)
		}
	}
}

func writeComponents(b *strings.Builder, comps *Components) {
	names := comps.Names()
	if len(names) == 0 {
		return
	}
	b.WriteString("components:\n")
	b.WriteString("  schemas:\n")
	for _, name := range names {
		fmt.Fprintf(b, "    %s:\n", yamlKey(name))
		writeSchema(b, comps.Get(name), 6)
	}
}

// yamlPlainOrQuoted renders a scalar as a bare YAML plain scalar when safe
// (a path or an operationId — restricted to characters plain YAML never
// misreads), quoting anything else defensively. In particular this always
// quotes a "#/components/..." $ref: a bare "#" starts a YAML comment, which
// would silently swallow the rest of the line and leave the key with no
// value at all.
func yamlPlainOrQuoted(s string) string {
	safe := true
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
		case strings.ContainsRune("/._-", r):
		default:
			safe = false
		}
	}
	if safe && s != "" {
		return s
	}
	return quoteYAML(s)
}

// yamlKey renders a mapping key — an OpenAPI component/property name — the
// same way, since a JSON field name can contain characters plain YAML does
// not accept unquoted (rare in this codebase's own Req/Resp structs, but a
// foreign qualified type's sanitized name always is plain already).
func yamlKey(s string) string {
	return yamlPlainOrQuoted(s)
}
