// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BearoffPlan(arg1, arg2) {
  return window['go']['gui']['App']['BearoffPlan'](arg1, arg2);
}

export function BearoffStatus() {
  return window['go']['gui']['App']['BearoffStatus']();
}

export function CancelBearoffGeneration() {
  return window['go']['gui']['App']['CancelBearoffGeneration']();
}

export function CancelCubeMatrix() {
  return window['go']['gui']['App']['CancelCubeMatrix']();
}

export function CancelEvaluationAtRest() {
  return window['go']['gui']['App']['CancelEvaluationAtRest']();
}

export function CancelGammonNetBatch() {
  return window['go']['gui']['App']['CancelGammonNetBatch']();
}

export function CheckForUpdate() {
  return window['go']['gui']['App']['CheckForUpdate']();
}

export function CollectImportableFiles(arg1) {
  return window['go']['gui']['App']['CollectImportableFiles'](arg1);
}

export function ComputeCubeMatrix(arg1, arg2, arg3, arg4) {
  return window['go']['gui']['App']['ComputeCubeMatrix'](arg1, arg2, arg3, arg4);
}

export function CopyImageToClipboard(arg1) {
  return window['go']['gui']['App']['CopyImageToClipboard'](arg1);
}

export function DeleteBearoffTable(arg1) {
  return window['go']['gui']['App']['DeleteBearoffTable'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['gui']['App']['DeleteFile'](arg1);
}

export function DiscardBearoffCheckpoint(arg1, arg2) {
  return window['go']['gui']['App']['DiscardBearoffCheckpoint'](arg1, arg2);
}

export function EnsureBearoffTables() {
  return window['go']['gui']['App']['EnsureBearoffTables']();
}

export function EvaluatePositionImmediate(arg1, arg2, arg3) {
  return window['go']['gui']['App']['EvaluatePositionImmediate'](arg1, arg2, arg3);
}

export function ExportIssuerIdentity(arg1) {
  return window['go']['gui']['App']['ExportIssuerIdentity'](arg1);
}

export function FolderWatchStatus() {
  return window['go']['gui']['App']['FolderWatchStatus']();
}

export function GenerateBearoffTable(arg1, arg2, arg3, arg4) {
  return window['go']['gui']['App']['GenerateBearoffTable'](arg1, arg2, arg3, arg4);
}

export function GetIssuerIdentity() {
  return window['go']['gui']['App']['GetIssuerIdentity']();
}

export function ImportIssuerIdentity(arg1, arg2) {
  return window['go']['gui']['App']['ImportIssuerIdentity'](arg1, arg2);
}

export function IsDirectory(arg1) {
  return window['go']['gui']['App']['IsDirectory'](arg1);
}

export function LooksLikeOGID(arg1) {
  return window['go']['gui']['App']['LooksLikeOGID'](arg1);
}

export function OpenBearoffFileDialog() {
  return window['go']['gui']['App']['OpenBearoffFileDialog']();
}

export function OpenDatabaseDialog() {
  return window['go']['gui']['App']['OpenDatabaseDialog']();
}

export function OpenExportDatabaseDialog() {
  return window['go']['gui']['App']['OpenExportDatabaseDialog']();
}

export function OpenExportMatDialog(arg1) {
  return window['go']['gui']['App']['OpenExportMatDialog'](arg1);
}

export function OpenImportDatabaseDialog() {
  return window['go']['gui']['App']['OpenImportDatabaseDialog']();
}

export function OpenLogsFolder() {
  return window['go']['gui']['App']['OpenLogsFolder']();
}

export function OpenPositionFilesDialog() {
  return window['go']['gui']['App']['OpenPositionFilesDialog']();
}

export function OpenPositionFolderDialog() {
  return window['go']['gui']['App']['OpenPositionFolderDialog']();
}

export function PathExists(arg1) {
  return window['go']['gui']['App']['PathExists'](arg1);
}

export function PauseBearoffGeneration() {
  return window['go']['gui']['App']['PauseBearoffGeneration']();
}

export function PickIdentityFile() {
  return window['go']['gui']['App']['PickIdentityFile']();
}

export function PrepareDemoDatabase() {
  return window['go']['gui']['App']['PrepareDemoDatabase']();
}

export function ReadFileContent(arg1) {
  return window['go']['gui']['App']['ReadFileContent'](arg1);
}

export function ReadLogTail(arg1) {
  return window['go']['gui']['App']['ReadLogTail'](arg1);
}

export function RegenerateIssuerIdentity(arg1) {
  return window['go']['gui']['App']['RegenerateIssuerIdentity'](arg1);
}

export function SaveBoardImageDialog(arg1, arg2) {
  return window['go']['gui']['App']['SaveBoardImageDialog'](arg1, arg2);
}

export function SaveBoardPNG(arg1, arg2) {
  return window['go']['gui']['App']['SaveBoardPNG'](arg1, arg2);
}

export function SaveBoardSVG(arg1, arg2) {
  return window['go']['gui']['App']['SaveBoardSVG'](arg1, arg2);
}

export function SaveDatabaseDialog() {
  return window['go']['gui']['App']['SaveDatabaseDialog']();
}

export function SetIssuerName(arg1) {
  return window['go']['gui']['App']['SetIssuerName'](arg1);
}

export function ShowAlert(arg1) {
  return window['go']['gui']['App']['ShowAlert'](arg1);
}

export function ShowQuestionDialog(arg1, arg2, arg3, arg4) {
  return window['go']['gui']['App']['ShowQuestionDialog'](arg1, arg2, arg3, arg4);
}

export function StartEvaluationAtRest(arg1, arg2, arg3, arg4) {
  return window['go']['gui']['App']['StartEvaluationAtRest'](arg1, arg2, arg3, arg4);
}

export function StartFolderWatch(arg1, arg2) {
  return window['go']['gui']['App']['StartFolderWatch'](arg1, arg2);
}

export function StartGammonNetBatch(arg1, arg2, arg3) {
  return window['go']['gui']['App']['StartGammonNetBatch'](arg1, arg2, arg3);
}

export function StartGammonNetStaleBatch(arg1, arg2, arg3) {
  return window['go']['gui']['App']['StartGammonNetStaleBatch'](arg1, arg2, arg3);
}

export function StartupFilePath() {
  return window['go']['gui']['App']['StartupFilePath']();
}

export function StopFolderWatch() {
  return window['go']['gui']['App']['StopFolderWatch']();
}

export function SuggestWatchFolder() {
  return window['go']['gui']['App']['SuggestWatchFolder']();
}
