// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';
import {domain} from '../models';

export function BearoffStatus():Promise<gui.BearoffStatus>;

export function CancelBearoffDownload():Promise<void>;

export function CollectImportableFiles(arg1:string):Promise<Array<string>>;

export function CopyImageToClipboard(arg1:string):Promise<string>;

export function DeleteBearoffDB():Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function DownloadBearoffDB():Promise<void>;

export function ExportIssuerIdentity(arg1:string):Promise<string>;

export function GetIssuerIdentity():Promise<domain.IssuerIdentityInfo>;

export function ImportIssuerIdentity(arg1:string,arg2:string):Promise<domain.IssuerIdentityInfo>;

export function IsDirectory(arg1:string):Promise<boolean>;

export function OpenBearoffFileDialog():Promise<string>;

export function OpenDatabaseDialog():Promise<string>;

export function OpenExportDatabaseDialog():Promise<string>;

export function OpenExportMatDialog(arg1:string):Promise<string>;

export function OpenImportDatabaseDialog():Promise<string>;

export function OpenPositionDialog():Promise<gui.FileDialogResponse>;

export function OpenPositionFilesDialog():Promise<Array<string>>;

export function OpenPositionFolderDialog():Promise<string>;

export function OpenXGFileDialog():Promise<string>;

export function PathExists(arg1:string):Promise<boolean>;

export function PickIdentityFile():Promise<domain.IdentityFilePick>;

export function PrepareDemoDatabase():Promise<string>;

export function ReadFileContent(arg1:string):Promise<gui.FileDialogResponse>;

export function RegenerateIssuerIdentity(arg1:string):Promise<domain.IssuerIdentityInfo>;

export function SaveDatabaseDialog():Promise<string>;

export function SetIssuerName(arg1:string):Promise<domain.IssuerIdentityInfo>;

export function ShowAlert(arg1:string):Promise<void>;

export function ShowQuestionDialog(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<string>;
