// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssistantAsk(arg1) {
  return window['go']['gui']['App']['AssistantAsk'](arg1);
}

export function AssistantCancel() {
  return window['go']['gui']['App']['AssistantCancel']();
}

export function AssistantConfirm(arg1) {
  return window['go']['gui']['App']['AssistantConfirm'](arg1);
}

export function AssistantHasKey(arg1) {
  return window['go']['gui']['App']['AssistantHasKey'](arg1);
}

export function AssistantPresets() {
  return window['go']['gui']['App']['AssistantPresets']();
}

export function AssistantReset() {
  return window['go']['gui']['App']['AssistantReset']();
}

export function AssistantSetKey(arg1, arg2) {
  return window['go']['gui']['App']['AssistantSetKey'](arg1, arg2);
}

export function BearoffPlan(arg1, arg2) {
  return window['go']['gui']['App']['BearoffPlan'](arg1, arg2);
}

export function BearoffStatus() {
  return window['go']['gui']['App']['BearoffStatus']();
}

export function CancelBearoffGeneration() {
  return window['go']['gui']['App']['CancelBearoffGeneration']();
}

export function CancelCubeMatrix() {
  return window['go']['gui']['App']['CancelCubeMatrix']();
}

export function CancelEvaluationAtRest() {
  return window['go']['gui']['App']['CancelEvaluationAtRest']();
}

export function CancelGammonNetBatch() {
  return window['go']['gui']['App']['CancelGammonNetBatch']();
}

export function CancelRollout() {
  return window['go']['gui']['App']['CancelRollout']();
}

export function CheckForUpdate() {
  return window['go']['gui']['App']['CheckForUpdate']();
}

export function CollectImportableFiles(arg1) {
  return window['go']['gui']['App']['CollectImportableFiles'](arg1);
}

export function ComputeCubeMatrix(arg1, arg2, arg3, arg4) {
  return window['go']['gui']['App']['ComputeCubeMatrix'](arg1, arg2, arg3, arg4);
}

export function ConfigureMCPHost(arg1) {
  return window['go']['gui']['App']['ConfigureMCPHost'](arg1);
}

export function CopyImageToClipboard(arg1) {
  return window['go']['gui']['App']['CopyImageToClipboard'](arg1);
}

export function CountRolloutIDs(arg1, arg2) {
  return window['go']['gui']['App']['CountRolloutIDs'](arg1, arg2);
}

export function DeleteBearoffTable(arg1) {
  return window['go']['gui']['App']['DeleteBearoffTable'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['gui']['App']['DeleteFile'](arg1);
}

export function DiscardBearoffCheckpoint(arg1, arg2) {
  return window['go']['gui']['App']['DiscardBearoffCheckpoint'](arg1, arg2);
}

export function EnsureBearoffTables() {
  return window['go']['gui']['App']['EnsureBearoffTables']();
}

export function EvaluatePositionImmediate(arg1, arg2, arg3) {
  return window['go']['gui']['App']['EvaluatePositionImmediate'](arg1, arg2, arg3);
}

export function ExportIssuerIdentity(arg1) {
  return window['go']['gui']['App']['ExportIssuerIdentity'](arg1);
}

export function FolderWatchStatus() {
  return window['go']['gui']['App']['FolderWatchStatus']();
}

export function GenerateBearoffQuestion(arg1) {
  return window['go']['gui']['App']['GenerateBearoffQuestion'](arg1);
}

export function GenerateBearoffTable(arg1, arg2, arg3, arg4) {
  return window['go']['gui']['App']['GenerateBearoffTable'](arg1, arg2, arg3, arg4);
}

export function GenerateEvaluationQuestion(arg1) {
  return window['go']['gui']['App']['GenerateEvaluationQuestion'](arg1);
}

export function GetIssuerIdentity() {
  return window['go']['gui']['App']['GetIssuerIdentity']();
}

export function GetMCPHostStatus() {
  return window['go']['gui']['App']['GetMCPHostStatus']();
}

export function ImportFiles(arg1) {
  return window['go']['gui']['App']['ImportFiles'](arg1);
}

export function ImportIssuerIdentity(arg1, arg2) {
  return window['go']['gui']['App']['ImportIssuerIdentity'](arg1, arg2);
}

export function IsDirectory(arg1) {
  return window['go']['gui']['App']['IsDirectory'](arg1);
}

export function LegalMoves(arg1) {
  return window['go']['gui']['App']['LegalMoves'](arg1);
}

export function LooksLikeOGID(arg1) {
  return window['go']['gui']['App']['LooksLikeOGID'](arg1);
}

export function MediaURL(arg1) {
  return window['go']['gui']['App']['MediaURL'](arg1);
}

export function OpenBearoffFileDialog() {
  return window['go']['gui']['App']['OpenBearoffFileDialog']();
}

export function OpenDatabaseDialog() {
  return window['go']['gui']['App']['OpenDatabaseDialog']();
}

export function OpenDirectionOutputDialog() {
  return window['go']['gui']['App']['OpenDirectionOutputDialog']();
}

export function OpenExportDatabaseDialog() {
  return window['go']['gui']['App']['OpenExportDatabaseDialog']();
}

export function OpenExportApkgDialog(arg1) {
  return window['go']['gui']['App']['OpenExportApkgDialog'](arg1);
}

export function OpenExportMatDialog(arg1) {
  return window['go']['gui']['App']['OpenExportMatDialog'](arg1);
}

export function OpenImportDatabaseDialog() {
  return window['go']['gui']['App']['OpenImportDatabaseDialog']();
}

export function OpenLocalPage(arg1) {
  return window['go']['gui']['App']['OpenLocalPage'](arg1);
}

export function OpenLogsFolder() {
  return window['go']['gui']['App']['OpenLogsFolder']();
}

export function OpenMETDialog() {
  return window['go']['gui']['App']['OpenMETDialog']();
}

export function OpenPositionFilesDialog() {
  return window['go']['gui']['App']['OpenPositionFilesDialog']();
}

export function OpenPositionFolderDialog() {
  return window['go']['gui']['App']['OpenPositionFolderDialog']();
}

export function OpenVideoExternally(arg1, arg2) {
  return window['go']['gui']['App']['OpenVideoExternally'](arg1, arg2);
}

export function PathExists(arg1) {
  return window['go']['gui']['App']['PathExists'](arg1);
}

export function PauseBearoffGeneration() {
  return window['go']['gui']['App']['PauseBearoffGeneration']();
}

export function PickIdentityFile() {
  return window['go']['gui']['App']['PickIdentityFile']();
}

export function PickTranscriptionVideo() {
  return window['go']['gui']['App']['PickTranscriptionVideo']();
}

export function PrepareDemoDatabase() {
  return window['go']['gui']['App']['PrepareDemoDatabase']();
}

export function ReadFileContent(arg1) {
  return window['go']['gui']['App']['ReadFileContent'](arg1);
}

export function ReadLogTail(arg1) {
  return window['go']['gui']['App']['ReadLogTail'](arg1);
}

export function RegenerateIssuerIdentity(arg1) {
  return window['go']['gui']['App']['RegenerateIssuerIdentity'](arg1);
}

export function ReleaseMedia(arg1) {
  return window['go']['gui']['App']['ReleaseMedia'](arg1);
}

export function RolloutPresets() {
  return window['go']['gui']['App']['RolloutPresets']();
}

export function RolloutStatus() {
  return window['go']['gui']['App']['RolloutStatus']();
}

export function SaveBoardImageDialog(arg1, arg2) {
  return window['go']['gui']['App']['SaveBoardImageDialog'](arg1, arg2);
}

export function SaveBoardPNG(arg1, arg2) {
  return window['go']['gui']['App']['SaveBoardPNG'](arg1, arg2);
}

export function SaveBoardSVG(arg1, arg2) {
  return window['go']['gui']['App']['SaveBoardSVG'](arg1, arg2);
}

export function SaveCSV(arg1, arg2) {
  return window['go']['gui']['App']['SaveCSV'](arg1, arg2);
}

export function SaveDatabaseDialog() {
  return window['go']['gui']['App']['SaveDatabaseDialog']();
}

export function SetIssuerName(arg1) {
  return window['go']['gui']['App']['SetIssuerName'](arg1);
}

export function ShowAlert(arg1) {
  return window['go']['gui']['App']['ShowAlert'](arg1);
}

export function ShowQuestionDialog(arg1, arg2, arg3, arg4) {
  return window['go']['gui']['App']['ShowQuestionDialog'](arg1, arg2, arg3, arg4);
}

export function StartEvaluationAtRest(arg1, arg2, arg3, arg4) {
  return window['go']['gui']['App']['StartEvaluationAtRest'](arg1, arg2, arg3, arg4);
}

export function StartFolderWatch(arg1, arg2) {
  return window['go']['gui']['App']['StartFolderWatch'](arg1, arg2);
}

export function StartGammonNetBatch(arg1, arg2, arg3) {
  return window['go']['gui']['App']['StartGammonNetBatch'](arg1, arg2, arg3);
}

export function StartGammonNetMatchBatch(arg1, arg2, arg3, arg4) {
  return window['go']['gui']['App']['StartGammonNetMatchBatch'](arg1, arg2, arg3, arg4);
}

export function StartGammonNetStaleBatch(arg1, arg2, arg3) {
  return window['go']['gui']['App']['StartGammonNetStaleBatch'](arg1, arg2, arg3);
}

export function StartRollout(arg1) {
  return window['go']['gui']['App']['StartRollout'](arg1);
}

export function StartRolloutFiltered(arg1, arg2) {
  return window['go']['gui']['App']['StartRolloutFiltered'](arg1, arg2);
}

export function StartRolloutIDs(arg1, arg2) {
  return window['go']['gui']['App']['StartRolloutIDs'](arg1, arg2);
}

export function StartupFilePath() {
  return window['go']['gui']['App']['StartupFilePath']();
}

export function StopFolderWatch() {
  return window['go']['gui']['App']['StopFolderWatch']();
}

export function SuggestWatchFolder() {
  return window['go']['gui']['App']['SuggestWatchFolder']();
}

export function VideoSourceKind(arg1) {
  return window['go']['gui']['App']['VideoSourceKind'](arg1);
}

export function YouTubeEmbedURL(arg1) {
  return window['go']['gui']['App']['YouTubeEmbedURL'](arg1);
}

export function YouTubeWatchURL(arg1) {
  return window['go']['gui']['App']['YouTubeWatchURL'](arg1);
}
