// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';
import {assistant} from '../models';
import {domain} from '../models';
import {gammonnet} from '../models';
import {rollout} from '../models';
import {race} from '../models';
import {training} from '../models';

export function AssistantAsk(arg1:gui.AssistantRequest):Promise<assistant.Turn>;

export function AssistantCancel():Promise<void>;

export function AssistantConfirm(arg1:boolean):Promise<assistant.Turn>;

export function AssistantHasKey(arg1:string):Promise<boolean>;

export function AssistantPresets():Promise<Array<assistant.Preset>>;

export function AssistantReset():Promise<void>;

export function AssistantSetKey(arg1:string,arg2:string):Promise<void>;

export function BearoffPlan(arg1:number,arg2:number):Promise<gui.BearoffPlan>;

export function BearoffStatus():Promise<gui.BearoffStatus>;

export function CancelBearoffGeneration():Promise<void>;

export function CancelCubeMatrix():Promise<void>;

export function CancelEvaluationAtRest():Promise<void>;

export function CancelGammonNetBatch():Promise<void>;

export function CancelRollout():Promise<void>;

export function CheckForUpdate():Promise<gui.UpdateCheckResult>;

export function CollectImportableFiles(arg1:string):Promise<Array<string>>;

export function ComputeCubeMatrix(arg1:domain.Position,arg2:number,arg3:number,arg4:number):Promise<gammonnet.CubeMatrix>;

export function ConfigureMCPHost(arg1:gui.MCPHostConfig):Promise<gui.MCPHostStatus>;

export function CopyImageToClipboard(arg1:string):Promise<string>;

export function CountRolloutIDs(arg1:Array<number>,arg2:rollout.Settings):Promise<number>;

export function DeleteBearoffTable(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function DiscardBearoffCheckpoint(arg1:number,arg2:number):Promise<void>;

export function EnsureBearoffTables():Promise<void>;

export function EvaluatePositionImmediate(arg1:domain.Position,arg2:number,arg3:number):Promise<gui.GammonNetEvalResult>;

export function ExportIssuerIdentity(arg1:string):Promise<string>;

export function FolderWatchStatus():Promise<gui.WatchStatus>;

export function GenerateBearoffQuestion(arg1:race.BearoffRequest):Promise<race.BearoffQuestion>;

export function GenerateBearoffTable(arg1:string,arg2:number,arg3:number,arg4:number):Promise<void>;

export function GenerateEvaluationQuestion(arg1:training.EvaluationRequest):Promise<training.EvaluationQuestion>;

export function GetIssuerIdentity():Promise<domain.IssuerIdentityInfo>;

export function GetMCPHostStatus():Promise<gui.MCPHostStatus>;

export function ImportFiles(arg1:Array<string>):Promise<gui.ImportFilesSummary>;

export function ImportIssuerIdentity(arg1:string,arg2:string):Promise<domain.IssuerIdentityInfo>;

export function IsDirectory(arg1:string):Promise<boolean>;

export function LegalMoves(arg1:domain.Position):Promise<Array<domain.LegalPlay>>;

export function LooksLikeOGID(arg1:string):Promise<boolean>;

export function OpenBearoffFileDialog():Promise<string>;

export function OpenDatabaseDialog():Promise<string>;

export function OpenDirectionOutputDialog():Promise<string>;

export function OpenExportDatabaseDialog():Promise<string>;

export function OpenExportMatDialog(arg1:string):Promise<string>;

export function OpenImportDatabaseDialog():Promise<string>;

export function OpenLocalPage(arg1:string):Promise<void>;

export function OpenLogsFolder():Promise<void>;

export function OpenMETDialog():Promise<string>;

export function OpenPositionFilesDialog():Promise<Array<string>>;

export function OpenPositionFolderDialog():Promise<string>;

export function PathExists(arg1:string):Promise<boolean>;

export function PauseBearoffGeneration():Promise<void>;

export function PickIdentityFile():Promise<domain.IdentityFilePick>;

export function PrepareDemoDatabase():Promise<string>;

export function ReadFileContent(arg1:string):Promise<gui.FileDialogResponse>;

export function ReadLogTail(arg1:number):Promise<Array<string>>;

export function RegenerateIssuerIdentity(arg1:string):Promise<domain.IssuerIdentityInfo>;

export function RolloutPresets():Promise<Array<gui.RolloutPreset>>;

export function RolloutStatus():Promise<gui.RolloutStatus>;

export function SaveBoardImageDialog(arg1:string,arg2:string):Promise<string>;

export function SaveBoardPNG(arg1:string,arg2:string):Promise<void>;

export function SaveBoardSVG(arg1:string,arg2:string):Promise<void>;

export function SaveCSV(arg1:string,arg2:string):Promise<string>;

export function SaveDatabaseDialog():Promise<string>;

export function SetIssuerName(arg1:string):Promise<domain.IssuerIdentityInfo>;

export function ShowAlert(arg1:string):Promise<void>;

export function ShowQuestionDialog(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<string>;

export function StartEvaluationAtRest(arg1:domain.Position,arg2:number,arg3:number,arg4:number):Promise<void>;

export function StartFolderWatch(arg1:string,arg2:number):Promise<gui.WatchStatus>;

export function StartGammonNetBatch(arg1:number,arg2:number,arg3:number):Promise<void>;

export function StartGammonNetMatchBatch(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function StartGammonNetStaleBatch(arg1:number,arg2:number,arg3:number):Promise<void>;

export function StartRollout(arg1:gui.RolloutRequest):Promise<number>;

export function StartRolloutFiltered(arg1:string,arg2:rollout.Settings):Promise<number>;

export function StartRolloutIDs(arg1:Array<number>,arg2:rollout.Settings):Promise<number>;

export function StartupFilePath():Promise<string>;

export function StopFolderWatch():Promise<void>;

export function SuggestWatchFolder():Promise<string>;
