// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';
import {domain} from '../models';
import {gammonnet} from '../models';

export function BearoffPlan(arg1:number,arg2:number):Promise<gui.BearoffPlan>;

export function BearoffStatus():Promise<gui.BearoffStatus>;

export function CancelBearoffGeneration():Promise<void>;

export function CancelCubeMatrix():Promise<void>;

export function CancelEvaluationAtRest():Promise<void>;

export function CancelGammonNetBatch():Promise<void>;

export function CheckForUpdate():Promise<gui.UpdateCheckResult>;

export function CollectImportableFiles(arg1:string):Promise<Array<string>>;

export function ComputeCubeMatrix(arg1:domain.Position,arg2:number,arg3:number,arg4:number):Promise<gammonnet.CubeMatrix>;

export function CopyImageToClipboard(arg1:string):Promise<string>;

export function DeleteBearoffTable(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function DiscardBearoffCheckpoint(arg1:number,arg2:number):Promise<void>;

export function EnsureBearoffTables():Promise<void>;

export function EvaluatePositionImmediate(arg1:domain.Position,arg2:number,arg3:number):Promise<gui.GammonNetEvalResult>;

export function ExportIssuerIdentity(arg1:string):Promise<string>;

export function FolderWatchStatus():Promise<gui.WatchStatus>;

export function GenerateBearoffTable(arg1:string,arg2:number,arg3:number,arg4:number):Promise<void>;

export function GetIssuerIdentity():Promise<domain.IssuerIdentityInfo>;

export function ImportIssuerIdentity(arg1:string,arg2:string):Promise<domain.IssuerIdentityInfo>;

export function IsDirectory(arg1:string):Promise<boolean>;

export function OpenBearoffFileDialog():Promise<string>;

export function OpenDatabaseDialog():Promise<string>;

export function OpenExportDatabaseDialog():Promise<string>;

export function OpenExportMatDialog(arg1:string):Promise<string>;

export function OpenImportDatabaseDialog():Promise<string>;

export function OpenLogsFolder():Promise<void>;

export function OpenPositionFilesDialog():Promise<Array<string>>;

export function OpenPositionFolderDialog():Promise<string>;

export function PathExists(arg1:string):Promise<boolean>;

export function PauseBearoffGeneration():Promise<void>;

export function PickIdentityFile():Promise<domain.IdentityFilePick>;

export function PrepareDemoDatabase():Promise<string>;

export function ReadFileContent(arg1:string):Promise<gui.FileDialogResponse>;

export function RegenerateIssuerIdentity(arg1:string):Promise<domain.IssuerIdentityInfo>;

export function SaveBoardImageDialog(arg1:string,arg2:string):Promise<string>;

export function SaveBoardPNG(arg1:string,arg2:string):Promise<void>;

export function SaveBoardSVG(arg1:string,arg2:string):Promise<void>;

export function SaveDatabaseDialog():Promise<string>;

export function SetIssuerName(arg1:string):Promise<domain.IssuerIdentityInfo>;

export function ShowAlert(arg1:string):Promise<void>;

export function ShowQuestionDialog(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<string>;

export function StartEvaluationAtRest(arg1:domain.Position,arg2:number,arg3:number,arg4:number):Promise<void>;

export function StartFolderWatch(arg1:string,arg2:number):Promise<gui.WatchStatus>;

export function StartGammonNetBatch(arg1:number,arg2:number,arg3:number):Promise<void>;

export function StartGammonNetStaleBatch(arg1:number,arg2:number,arg3:number):Promise<void>;

export function StartupFilePath():Promise<string>;

export function StopFolderWatch():Promise<void>;

export function SuggestWatchFolder():Promise<string>;
