// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BearoffStatus() {
  return window['go']['gui']['App']['BearoffStatus']();
}

export function CancelBearoffDownload() {
  return window['go']['gui']['App']['CancelBearoffDownload']();
}

export function CancelEvaluationAtRest() {
  return window['go']['gui']['App']['CancelEvaluationAtRest']();
}

export function CancelGammonNetBatch() {
  return window['go']['gui']['App']['CancelGammonNetBatch']();
}

export function CollectImportableFiles(arg1) {
  return window['go']['gui']['App']['CollectImportableFiles'](arg1);
}

export function CopyImageToClipboard(arg1) {
  return window['go']['gui']['App']['CopyImageToClipboard'](arg1);
}

export function DeleteBearoffDB() {
  return window['go']['gui']['App']['DeleteBearoffDB']();
}

export function DeleteFile(arg1) {
  return window['go']['gui']['App']['DeleteFile'](arg1);
}

export function DownloadBearoffDB() {
  return window['go']['gui']['App']['DownloadBearoffDB']();
}

export function EvaluatePositionImmediate(arg1, arg2, arg3) {
  return window['go']['gui']['App']['EvaluatePositionImmediate'](arg1, arg2, arg3);
}

export function ExportIssuerIdentity(arg1) {
  return window['go']['gui']['App']['ExportIssuerIdentity'](arg1);
}

export function GetIssuerIdentity() {
  return window['go']['gui']['App']['GetIssuerIdentity']();
}

export function ImportIssuerIdentity(arg1, arg2) {
  return window['go']['gui']['App']['ImportIssuerIdentity'](arg1, arg2);
}

export function IsDirectory(arg1) {
  return window['go']['gui']['App']['IsDirectory'](arg1);
}

export function OpenBearoffFileDialog() {
  return window['go']['gui']['App']['OpenBearoffFileDialog']();
}

export function OpenDatabaseDialog() {
  return window['go']['gui']['App']['OpenDatabaseDialog']();
}

export function OpenExportDatabaseDialog() {
  return window['go']['gui']['App']['OpenExportDatabaseDialog']();
}

export function OpenExportMatDialog(arg1) {
  return window['go']['gui']['App']['OpenExportMatDialog'](arg1);
}

export function OpenImportDatabaseDialog() {
  return window['go']['gui']['App']['OpenImportDatabaseDialog']();
}

export function OpenPositionDialog() {
  return window['go']['gui']['App']['OpenPositionDialog']();
}

export function OpenPositionFilesDialog() {
  return window['go']['gui']['App']['OpenPositionFilesDialog']();
}

export function OpenPositionFolderDialog() {
  return window['go']['gui']['App']['OpenPositionFolderDialog']();
}

export function OpenXGFileDialog() {
  return window['go']['gui']['App']['OpenXGFileDialog']();
}

export function PathExists(arg1) {
  return window['go']['gui']['App']['PathExists'](arg1);
}

export function PickIdentityFile() {
  return window['go']['gui']['App']['PickIdentityFile']();
}

export function PrepareDemoDatabase() {
  return window['go']['gui']['App']['PrepareDemoDatabase']();
}

export function ReadFileContent(arg1) {
  return window['go']['gui']['App']['ReadFileContent'](arg1);
}

export function RegenerateIssuerIdentity(arg1) {
  return window['go']['gui']['App']['RegenerateIssuerIdentity'](arg1);
}

export function SaveDatabaseDialog() {
  return window['go']['gui']['App']['SaveDatabaseDialog']();
}

export function SetIssuerName(arg1) {
  return window['go']['gui']['App']['SetIssuerName'](arg1);
}

export function ShowAlert(arg1) {
  return window['go']['gui']['App']['ShowAlert'](arg1);
}

export function ShowQuestionDialog(arg1, arg2, arg3, arg4) {
  return window['go']['gui']['App']['ShowQuestionDialog'](arg1, arg2, arg3, arg4);
}

export function StartEvaluationAtRest(arg1, arg2, arg3, arg4) {
  return window['go']['gui']['App']['StartEvaluationAtRest'](arg1, arg2, arg3, arg4);
}

export function StartGammonNetBatch(arg1, arg2, arg3) {
  return window['go']['gui']['App']['StartGammonNetBatch'](arg1, arg2, arg3);
}
