// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddComment(arg1, arg2) {
  return window['go']['database']['Database']['AddComment'](arg1, arg2);
}

export function AddMatchToTournament(arg1, arg2) {
  return window['go']['database']['Database']['AddMatchToTournament'](arg1, arg2);
}

export function AddPositionToCollection(arg1, arg2) {
  return window['go']['database']['Database']['AddPositionToCollection'](arg1, arg2);
}

export function AddPositionsToCollection(arg1, arg2) {
  return window['go']['database']['Database']['AddPositionsToCollection'](arg1, arg2);
}

export function AnalyzeImportDatabase(arg1) {
  return window['go']['database']['Database']['AnalyzeImportDatabase'](arg1);
}

export function CancelImport() {
  return window['go']['database']['Database']['CancelImport']();
}

export function CheckDatabaseVersion() {
  return window['go']['database']['Database']['CheckDatabaseVersion']();
}

export function CheckMatchExists(arg1) {
  return window['go']['database']['Database']['CheckMatchExists'](arg1);
}

export function CheckVersion(arg1) {
  return window['go']['database']['Database']['CheckVersion'](arg1);
}

export function ClearCommandHistory() {
  return window['go']['database']['Database']['ClearCommandHistory']();
}

export function ClearSessionState() {
  return window['go']['database']['Database']['ClearSessionState']();
}

export function Close() {
  return window['go']['database']['Database']['Close']();
}

export function CommitImportDatabase(arg1) {
  return window['go']['database']['Database']['CommitImportDatabase'](arg1);
}

export function ComputeEPCFromPosition(arg1) {
  return window['go']['database']['Database']['ComputeEPCFromPosition'](arg1);
}

export function ComputeStats(arg1) {
  return window['go']['database']['Database']['ComputeStats'](arg1);
}

export function Conn() {
  return window['go']['database']['Database']['Conn']();
}

export function CopyPositionToCollection(arg1, arg2) {
  return window['go']['database']['Database']['CopyPositionToCollection'](arg1, arg2);
}

export function CreateAnkiDeck(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['database']['Database']['CreateAnkiDeck'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateCollection(arg1, arg2) {
  return window['go']['database']['Database']['CreateCollection'](arg1, arg2);
}

export function CreateTournament(arg1, arg2, arg3) {
  return window['go']['database']['Database']['CreateTournament'](arg1, arg2, arg3);
}

export function DeleteAnalysis(arg1) {
  return window['go']['database']['Database']['DeleteAnalysis'](arg1);
}

export function DeleteAnkiDeck(arg1) {
  return window['go']['database']['Database']['DeleteAnkiDeck'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['database']['Database']['DeleteCollection'](arg1);
}

export function DeleteComment(arg1) {
  return window['go']['database']['Database']['DeleteComment'](arg1);
}

export function DeleteCommentEntry(arg1) {
  return window['go']['database']['Database']['DeleteCommentEntry'](arg1);
}

export function DeleteFilter(arg1) {
  return window['go']['database']['Database']['DeleteFilter'](arg1);
}

export function DeleteMatch(arg1) {
  return window['go']['database']['Database']['DeleteMatch'](arg1);
}

export function DeletePosition(arg1) {
  return window['go']['database']['Database']['DeletePosition'](arg1);
}

export function DeleteSearchHistoryEntry(arg1) {
  return window['go']['database']['Database']['DeleteSearchHistoryEntry'](arg1);
}

export function DeleteTournament(arg1) {
  return window['go']['database']['Database']['DeleteTournament'](arg1);
}

export function ExportCollections(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['database']['Database']['ExportCollections'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportDatabase(arg1) {
  return window['go']['database']['Database']['ExportDatabase'](arg1);
}

export function ExportTournaments(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['database']['Database']['ExportTournaments'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAllAnkiDecks() {
  return window['go']['database']['Database']['GetAllAnkiDecks']();
}

export function GetAllCollections() {
  return window['go']['database']['Database']['GetAllCollections']();
}

export function GetAllComments() {
  return window['go']['database']['Database']['GetAllComments']();
}

export function GetAllMatches() {
  return window['go']['database']['Database']['GetAllMatches']();
}

export function GetAllPlayerNames() {
  return window['go']['database']['Database']['GetAllPlayerNames']();
}

export function GetAllTournaments() {
  return window['go']['database']['Database']['GetAllTournaments']();
}

export function GetAnkiDeckPositions(arg1) {
  return window['go']['database']['Database']['GetAnkiDeckPositions'](arg1);
}

export function GetAnkiDeckStats(arg1) {
  return window['go']['database']['Database']['GetAnkiDeckStats'](arg1);
}

export function GetCollectionByID(arg1) {
  return window['go']['database']['Database']['GetCollectionByID'](arg1);
}

export function GetCollectionPositions(arg1) {
  return window['go']['database']['Database']['GetCollectionPositions'](arg1);
}

export function GetCommentsByPosition(arg1) {
  return window['go']['database']['Database']['GetCommentsByPosition'](arg1);
}

export function GetDatabaseStats() {
  return window['go']['database']['Database']['GetDatabaseStats']();
}

export function GetDatabaseVersion() {
  return window['go']['database']['Database']['GetDatabaseVersion']();
}

export function GetGamesByMatch(arg1) {
  return window['go']['database']['Database']['GetGamesByMatch'](arg1);
}

export function GetLastVisitedMatch() {
  return window['go']['database']['Database']['GetLastVisitedMatch']();
}

export function GetMatchByID(arg1) {
  return window['go']['database']['Database']['GetMatchByID'](arg1);
}

export function GetMatchDetailStats(arg1) {
  return window['go']['database']['Database']['GetMatchDetailStats'](arg1);
}

export function GetMatchMovePositions(arg1) {
  return window['go']['database']['Database']['GetMatchMovePositions'](arg1);
}

export function GetMatchTournament(arg1) {
  return window['go']['database']['Database']['GetMatchTournament'](arg1);
}

export function GetMovesByGame(arg1) {
  return window['go']['database']['Database']['GetMovesByGame'](arg1);
}

export function GetNextAnkiCard(arg1) {
  return window['go']['database']['Database']['GetNextAnkiCard'](arg1);
}

export function GetPositionCollections(arg1) {
  return window['go']['database']['Database']['GetPositionCollections'](arg1);
}

export function GetPositionIDsByMatch(arg1) {
  return window['go']['database']['Database']['GetPositionIDsByMatch'](arg1);
}

export function GetPositionIDsByStatsSelection(arg1, arg2) {
  return window['go']['database']['Database']['GetPositionIDsByStatsSelection'](arg1, arg2);
}

export function GetPositionIDsByTournament(arg1) {
  return window['go']['database']['Database']['GetPositionIDsByTournament'](arg1);
}

export function GetPositionIndexMap() {
  return window['go']['database']['Database']['GetPositionIndexMap']();
}

export function GetStatsDateRange() {
  return window['go']['database']['Database']['GetStatsDateRange']();
}

export function GetTournamentMatches(arg1) {
  return window['go']['database']['Database']['GetTournamentMatches'](arg1);
}

export function ImportBGFMatch(arg1) {
  return window['go']['database']['Database']['ImportBGFMatch'](arg1);
}

export function ImportBGFPosition(arg1) {
  return window['go']['database']['Database']['ImportBGFPosition'](arg1);
}

export function ImportBGFPositionFromText(arg1) {
  return window['go']['database']['Database']['ImportBGFPositionFromText'](arg1);
}

export function ImportDatabase(arg1) {
  return window['go']['database']['Database']['ImportDatabase'](arg1);
}

export function ImportGnuBGMatch(arg1) {
  return window['go']['database']['Database']['ImportGnuBGMatch'](arg1);
}

export function ImportGnuBGMatchFromText(arg1) {
  return window['go']['database']['Database']['ImportGnuBGMatchFromText'](arg1);
}

export function ImportXGMatch(arg1) {
  return window['go']['database']['Database']['ImportXGMatch'](arg1);
}

export function ImportXGPPosition(arg1) {
  return window['go']['database']['Database']['ImportXGPPosition'](arg1);
}

export function LoadAllPositions() {
  return window['go']['database']['Database']['LoadAllPositions']();
}

export function LoadAnalysis(arg1) {
  return window['go']['database']['Database']['LoadAnalysis'](arg1);
}

export function LoadCommandHistory() {
  return window['go']['database']['Database']['LoadCommandHistory']();
}

export function LoadComment(arg1) {
  return window['go']['database']['Database']['LoadComment'](arg1);
}

export function LoadEditPosition(arg1) {
  return window['go']['database']['Database']['LoadEditPosition'](arg1);
}

export function LoadExcludePosition(arg1) {
  return window['go']['database']['Database']['LoadExcludePosition'](arg1);
}

export function LoadFilters() {
  return window['go']['database']['Database']['LoadFilters']();
}

export function LoadMetadata() {
  return window['go']['database']['Database']['LoadMetadata']();
}

export function LoadPosition(arg1) {
  return window['go']['database']['Database']['LoadPosition'](arg1);
}

export function LoadPositionsByFilters(arg1) {
  return window['go']['database']['Database']['LoadPositionsByFilters'](arg1);
}

export function LoadPositionsByFiltersCore(arg1) {
  return window['go']['database']['Database']['LoadPositionsByFiltersCore'](arg1);
}

export function LoadSearchHistory() {
  return window['go']['database']['Database']['LoadSearchHistory']();
}

export function LoadSessionState() {
  return window['go']['database']['Database']['LoadSessionState']();
}

export function MergePlayers(arg1, arg2) {
  return window['go']['database']['Database']['MergePlayers'](arg1, arg2);
}

export function Migrate_1_0_0_to_1_1_0() {
  return window['go']['database']['Database']['Migrate_1_0_0_to_1_1_0']();
}

export function Migrate_1_1_0_to_1_2_0() {
  return window['go']['database']['Database']['Migrate_1_1_0_to_1_2_0']();
}

export function Migrate_1_2_0_to_1_3_0() {
  return window['go']['database']['Database']['Migrate_1_2_0_to_1_3_0']();
}

export function MovePositionBetweenCollections(arg1, arg2, arg3) {
  return window['go']['database']['Database']['MovePositionBetweenCollections'](arg1, arg2, arg3);
}

export function OpenDatabase(arg1) {
  return window['go']['database']['Database']['OpenDatabase'](arg1);
}

export function PositionExists(arg1) {
  return window['go']['database']['Database']['PositionExists'](arg1);
}

export function RemoveMatchFromTournament(arg1) {
  return window['go']['database']['Database']['RemoveMatchFromTournament'](arg1);
}

export function RemovePositionFromCollection(arg1, arg2) {
  return window['go']['database']['Database']['RemovePositionFromCollection'](arg1, arg2);
}

export function RemovePositionsFromCollection(arg1, arg2) {
  return window['go']['database']['Database']['RemovePositionsFromCollection'](arg1, arg2);
}

export function ReorderCollectionPositions(arg1, arg2) {
  return window['go']['database']['Database']['ReorderCollectionPositions'](arg1, arg2);
}

export function ReorderCollections(arg1) {
  return window['go']['database']['Database']['ReorderCollections'](arg1);
}

export function ReorderTournamentMatches(arg1, arg2) {
  return window['go']['database']['Database']['ReorderTournamentMatches'](arg1, arg2);
}

export function ResetAnkiDeck(arg1) {
  return window['go']['database']['Database']['ResetAnkiDeck'](arg1);
}

export function ReviewAnkiCard(arg1, arg2) {
  return window['go']['database']['Database']['ReviewAnkiCard'](arg1, arg2);
}

export function SaveAnalysis(arg1, arg2) {
  return window['go']['database']['Database']['SaveAnalysis'](arg1, arg2);
}

export function SaveCommand(arg1) {
  return window['go']['database']['Database']['SaveCommand'](arg1);
}

export function SaveComment(arg1, arg2) {
  return window['go']['database']['Database']['SaveComment'](arg1, arg2);
}

export function SaveEditPosition(arg1, arg2) {
  return window['go']['database']['Database']['SaveEditPosition'](arg1, arg2);
}

export function SaveExcludePosition(arg1, arg2) {
  return window['go']['database']['Database']['SaveExcludePosition'](arg1, arg2);
}

export function SaveFilter(arg1, arg2) {
  return window['go']['database']['Database']['SaveFilter'](arg1, arg2);
}

export function SaveLastVisitedPosition(arg1, arg2) {
  return window['go']['database']['Database']['SaveLastVisitedPosition'](arg1, arg2);
}

export function SaveMetadata(arg1) {
  return window['go']['database']['Database']['SaveMetadata'](arg1);
}

export function SavePosition(arg1) {
  return window['go']['database']['Database']['SavePosition'](arg1);
}

export function SaveSearchHistory(arg1, arg2, arg3) {
  return window['go']['database']['Database']['SaveSearchHistory'](arg1, arg2, arg3);
}

export function SaveSessionState(arg1) {
  return window['go']['database']['Database']['SaveSessionState'](arg1);
}

export function SearchComments(arg1) {
  return window['go']['database']['Database']['SearchComments'](arg1);
}

export function SetMatchTournamentByName(arg1, arg2) {
  return window['go']['database']['Database']['SetMatchTournamentByName'](arg1, arg2);
}

export function SetMigrationProgress(arg1) {
  return window['go']['database']['Database']['SetMigrationProgress'](arg1);
}

export function SetupDatabase(arg1) {
  return window['go']['database']['Database']['SetupDatabase'](arg1);
}

export function SwapMatchPlayers(arg1) {
  return window['go']['database']['Database']['SwapMatchPlayers'](arg1);
}

export function SyncAnkiDeck(arg1) {
  return window['go']['database']['Database']['SyncAnkiDeck'](arg1);
}

export function SyncAnkiDeckWithPositions(arg1, arg2) {
  return window['go']['database']['Database']['SyncAnkiDeckWithPositions'](arg1, arg2);
}

export function UpdateAnkiDeck(arg1, arg2, arg3) {
  return window['go']['database']['Database']['UpdateAnkiDeck'](arg1, arg2, arg3);
}

export function UpdateAnkiDeckParams(arg1, arg2, arg3, arg4) {
  return window['go']['database']['Database']['UpdateAnkiDeckParams'](arg1, arg2, arg3, arg4);
}

export function UpdateCollection(arg1, arg2, arg3) {
  return window['go']['database']['Database']['UpdateCollection'](arg1, arg2, arg3);
}

export function UpdateCommentEntry(arg1, arg2) {
  return window['go']['database']['Database']['UpdateCommentEntry'](arg1, arg2);
}

export function UpdateFilter(arg1, arg2, arg3) {
  return window['go']['database']['Database']['UpdateFilter'](arg1, arg2, arg3);
}

export function UpdateMatch(arg1, arg2, arg3, arg4) {
  return window['go']['database']['Database']['UpdateMatch'](arg1, arg2, arg3, arg4);
}

export function UpdateMatchComment(arg1, arg2) {
  return window['go']['database']['Database']['UpdateMatchComment'](arg1, arg2);
}

export function UpdatePosition(arg1) {
  return window['go']['database']['Database']['UpdatePosition'](arg1);
}

export function UpdateTournament(arg1, arg2, arg3, arg4) {
  return window['go']['database']['Database']['UpdateTournament'](arg1, arg2, arg3, arg4);
}

export function UpdateTournamentComment(arg1, arg2) {
  return window['go']['database']['Database']['UpdateTournamentComment'](arg1, arg2);
}
