// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {mets} from '../models';
import {context} from '../models';
import {database} from '../models';
import {transcript} from '../models';
import {sqlite} from '../models';
import {gammonnet} from '../models';
import {storage} from '../models';
import {domain} from '../models';
import {race} from '../models';
import {duel} from '../models';
import {direction} from '../models';
import {engine} from '../models';
import {tournoi} from '../models';
import {ingest} from '../models';
import {parser} from '../models';
import {rollout} from '../models';
import {rollouts} from '../models';

export function AbandonTranscription(arg1:number):Promise<void>;

export function AddComment(arg1:number,arg2:string):Promise<void>;

export function AddDirectionNote(arg1:number,arg2:string):Promise<service.DirectionView>;

export function AddLessonStep(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number):Promise<number>;

export function AddMatchToTournament(arg1:number,arg2:number):Promise<void>;

export function AddPair(arg1:number,arg2:string,arg3:number):Promise<service.DirectionView>;

export function AddParticipant(arg1:number,arg2:string,arg3:string,arg4:number):Promise<service.DirectionView>;

export function AddParticipantAtSlot(arg1:number,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string):Promise<service.DirectionView>;

export function AddPositionToCollection(arg1:number,arg2:number):Promise<void>;

export function AddPositionsToCollection(arg1:number,arg2:Array<number>):Promise<void>;

export function AnalysisMETStatus(arg1:number):Promise<mets.Status>;

export function AnalyzeImportDatabase(arg1:string):Promise<Record<string, any>>;

export function AnalyzeMatchWithGammonNet(arg1:context.Context,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number,arg7:any,arg8:any):Promise<database.GammonNetBatchSummary>;

export function AnalyzeMissingWithGammonNet(arg1:context.Context,arg2:number,arg3:number,arg4:number,arg5:number,arg6:any,arg7:any):Promise<database.GammonNetBatchSummary>;

export function AnalyzeStaleGammonNet(arg1:context.Context,arg2:number,arg3:number,arg4:number,arg5:number,arg6:any,arg7:any):Promise<database.GammonNetBatchSummary>;

export function ApplyTranscriptionGesture(arg1:number,arg2:transcript.Gesture):Promise<database.TranscriptionState>;

export function AttachMatchToSlot(arg1:number,arg2:string,arg3:number):Promise<void>;

export function AttachToRencontre(arg1:number,arg2:number):Promise<service.RencontreView>;

export function BeginImportBatch(arg1:string,arg2:string):Promise<number>;

export function Brackets(arg1:number):Promise<Array<service.BracketPhase>>;

export function BuryAnkiCard(arg1:number):Promise<void>;

export function CancelImport():Promise<void>;

export function CancelMatch(arg1:number,arg2:string):Promise<service.DirectionView>;

export function CancelSearch():Promise<void>;

export function CheckConstraints():Promise<Array<database.ConstraintViolation>>;

export function CheckCounters():Promise<database.CounterDrift>;

export function CheckDatabaseVersion():Promise<string>;

export function CheckMatchExists(arg1:string):Promise<number>;

export function CheckSchema():Promise<sqlite.SchemaDrift>;

export function CheckVersion(arg1:string):Promise<void>;

export function Checkpoint():Promise<void>;

export function ClearCommandHistory():Promise<void>;

export function ClearSessionState():Promise<void>;

export function Clock(arg1:number):Promise<service.ClockView>;

export function Close():Promise<void>;

export function CloseDirection(arg1:number):Promise<service.DirectionView>;

export function CloseTranscription(arg1:number):Promise<void>;

export function CollectionCoverage(arg1:Array<number>):Promise<Record<number, number>>;

export function CommitImportDatabase(arg1:string):Promise<Record<string, any>>;

export function CompareWithGammonNet(arg1:context.Context,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number,arg7:any):Promise<gammonnet.AnalysisComparison>;

export function ComputeDirectionalBiases(arg1:database.StatsFilter):Promise<storage.DirectionalBiases>;

export function ComputeDirectionalBiasesCtx(arg1:context.Context,arg2:database.StatsFilter):Promise<storage.DirectionalBiases>;

export function ComputeEPCFromPosition(arg1:domain.Position):Promise<race.Result>;

export function ComputeRecurringErrors(arg1:database.StatsFilter):Promise<storage.RecurringErrors>;

export function ComputeRecurringErrorsCtx(arg1:context.Context,arg2:database.StatsFilter):Promise<storage.RecurringErrors>;

export function ComputeStats(arg1:database.StatsFilter):Promise<database.StatsResult>;

export function ComputeStatsCtx(arg1:context.Context,arg2:database.StatsFilter):Promise<database.StatsResult>;

export function ComputeStudyEffect(arg1:database.StatsFilter):Promise<storage.StudyEffect>;

export function ComputeStudyEffectCtx(arg1:context.Context,arg2:database.StatsFilter):Promise<storage.StudyEffect>;

export function ComputeStudyPlan(arg1:database.StatsFilter):Promise<storage.StudyPlan>;

export function ComputeStudyPlanCtx(arg1:context.Context,arg2:database.StatsFilter):Promise<storage.StudyPlan>;

export function ComputeTrainingStats(arg1:database.StatsFilter,arg2:string):Promise<storage.TrainingStats>;

export function ComputeTrainingStatsCtx(arg1:context.Context,arg2:database.StatsFilter,arg3:string):Promise<storage.TrainingStats>;

export function ConfirmAllProposals(arg1:number):Promise<service.DirectionView>;

export function ConfirmProposal(arg1:number,arg2:string):Promise<service.DirectionView>;

export function ContributeDuel(arg1:number,arg2:number,arg3:number,arg4:string):Promise<database.DuelState>;

export function CopyPositionToCollection(arg1:number,arg2:number):Promise<void>;

export function CorrectResult(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number,arg6:string):Promise<service.DirectionView>;

export function CountAnkiDeckFilteredPositions(arg1:number,arg2:string):Promise<number>;

export function CountAnkiDeckPositions(arg1:number):Promise<number>;

export function CountCollectionPositions(arg1:number):Promise<number>;

export function CountMatchPositionsToAnalyze(arg1:number):Promise<number>;

export function CountMatches(arg1:storage.MatchListOpts):Promise<number>;

export function CountOrphans():Promise<database.OrphanCounts>;

export function CountPositions():Promise<number>;

export function CountPositionsByFilters(arg1:domain.SearchFilters):Promise<number>;

export function CountPositionsWithForeignAnalysis():Promise<number>;

export function CountPositionsWithStaleGammonNet(arg1:number):Promise<number>;

export function CountPositionsWithoutAnalysis():Promise<number>;

export function CountTrash():Promise<number>;

export function CreateAnkiDeck(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<number>;

export function CreateCollection(arg1:string,arg2:string):Promise<number>;

export function CreateDirection(arg1:number,arg2:string,arg3:number):Promise<void>;

export function CreateDuel(arg1:duel.Settings):Promise<database.DuelState>;

export function CreateLesson(arg1:string,arg2:string):Promise<number>;

export function CreateLivingCollection(arg1:string,arg2:string,arg3:string):Promise<number>;

export function CreateRencontre(arg1:string,arg2:string,arg3:string,arg4:number):Promise<service.RencontreView>;

export function CreateStudyDeck(arg1:string,arg2:Array<number>):Promise<number>;

export function CreateTournament(arg1:string,arg2:string,arg3:string):Promise<number>;

export function CreateTranscription(arg1:transcript.Header):Promise<database.TranscriptionState>;

export function DeleteAnalysis(arg1:number):Promise<void>;

export function DeleteAnkiDeck(arg1:number):Promise<void>;

export function DeleteCollection(arg1:number):Promise<void>;

export function DeleteComment(arg1:number):Promise<void>;

export function DeleteCommentEntry(arg1:number):Promise<void>;

export function DeleteDirection(arg1:number):Promise<void>;

export function DeleteFilter(arg1:number):Promise<void>;

export function DeleteLesson(arg1:number):Promise<void>;

export function DeleteMatch(arg1:number):Promise<void>;

export function DeletePosition(arg1:number):Promise<void>;

export function DeleteProtectedCopyPath(arg1:string):Promise<void>;

export function DeleteSearchHistoryEntry(arg1:number):Promise<void>;

export function DeleteTournament(arg1:number):Promise<void>;

export function DetachFromRencontre(arg1:number):Promise<void>;

export function DetachMatchFromSlot(arg1:number,arg2:string):Promise<void>;

export function DirectionFreeSlots(arg1:number):Promise<Array<service.FreeSlot>>;

export function DirectionJournalJSON(arg1:number):Promise<string>;

export function DirectionPageHTML(arg1:number):Promise<string>;

export function DirectionPairingSheetHTML(arg1:number,arg2:number):Promise<string>;

export function DirectionRounds(arg1:number):Promise<number>;

export function DirectionSearchIndex(arg1:number):Promise<Array<service.SearchEntry>>;

export function DirectionStore():Promise<direction.Store>;

export function DirectionUpcomingSheetHTML(arg1:number,arg2:string):Promise<string>;

export function Directory():Promise<Array<service.DirectoryEntry>>;

export function DirectoryCSV():Promise<string>;

export function DirectoryEntrants(arg1:number):Promise<Array<service.DirectoryEntry>>;

export function DirectorySources():Promise<Array<service.DirectorySource>>;

export function DiscardFromTrash(arg1:number):Promise<void>;

export function DuelOffer():Promise<database.DuelOffer>;

export function EditMatchTranscription(arg1:number):Promise<database.TranscriptionState>;

export function EmptyTrash(arg1:number):Promise<number>;

export function EnterForfeit(arg1:number,arg2:string,arg3:string,arg4:string):Promise<service.DirectionView>;

export function EnterParticipants(arg1:number,arg2:string):Promise<void>;

export function EnterResult(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number,arg6:string):Promise<service.DirectionView>;

export function EntrySuggestions():Promise<Array<service.EntrySuggestion>>;

export function EvaluateCollection(arg1:number,arg2:number):Promise<storage.CollectionEvaluation>;

export function ExplainDecision(arg1:number,arg2:string):Promise<engine.Explanation>;

export function ExportCollections(arg1:string,arg2:Array<number>,arg3:Record<string, string>,arg4:boolean,arg5:boolean,arg6:string,arg7:string):Promise<void>;

export function ExportDatabase(arg1:domain.ExportOptions):Promise<void>;

export function ExportDatabaseCtx(arg1:context.Context,arg2:domain.ExportOptions):Promise<void>;

export function ExportMatchMAT(arg1:number,arg2:string):Promise<void>;

export function ExportTournaments(arg1:string,arg2:Array<number>,arg3:Record<string, string>,arg4:boolean,arg5:boolean,arg6:string,arg7:string):Promise<void>;

export function ExportTranscriptionMAT(arg1:number,arg2:string):Promise<void>;

export function FindDuplicateMatches():Promise<Array<domain.DuplicateSuspect>>;

export function FinishImportBatch(arg1:number,arg2:domain.ImportReport):Promise<void>;

export function FinishTranscription(arg1:number):Promise<database.TranscriptionSaveResult>;

export function FinishedMatches(arg1:number,arg2:number):Promise<Array<service.TableCell>>;

export function FlagDuel(arg1:number):Promise<database.DuelState>;

export function ForfeitDuel(arg1:number,arg2:number,arg3:number):Promise<database.DuelState>;

export function FreeParticipants(arg1:number):Promise<Array<tournoi.Player>>;

export function FreezeCollection(arg1:number):Promise<number>;

export function GetAllAnkiDecks():Promise<Array<domain.AnkiDeck>>;

export function GetAllCollections():Promise<Array<database.Collection>>;

export function GetAllComments():Promise<Array<domain.CommentEntry>>;

export function GetAllMatches():Promise<Array<domain.Match>>;

export function GetAllPlayerNames():Promise<Array<database.PlayerFrequency>>;

export function GetAllTournaments():Promise<Array<domain.Tournament>>;

export function GetAnkiDeckPositions(arg1:number):Promise<Array<domain.Position>>;

export function GetAnkiDeckRetention(arg1:number):Promise<domain.AnkiRetention>;

export function GetAnkiDeckStats(arg1:number):Promise<domain.AnkiDeckStats>;

export function GetAnkiForecast(arg1:number,arg2:number):Promise<Array<domain.AnkiForecastDay>>;

export function GetAnkiReviewLog(arg1:number,arg2:number):Promise<Array<domain.AnkiReviewLog>>;

export function GetCollectionByID(arg1:number):Promise<database.Collection>;

export function GetCollectionPositions(arg1:number):Promise<Array<domain.Position>>;

export function GetCommentsByPosition(arg1:number):Promise<Array<domain.CommentEntry>>;

export function GetDatabaseStats():Promise<Record<string, any>>;

export function GetDatabaseStatsEstimate():Promise<Record<string, any>>;

export function GetDatabaseVersion():Promise<string>;

export function GetDirection(arg1:number):Promise<service.DirectionView>;

export function GetGamesByMatch(arg1:number):Promise<Array<domain.Game>>;

export function GetIssuanceInfo():Promise<domain.IssuanceInfo>;

export function GetLastVisitedMatch():Promise<domain.Match>;

export function GetLesson(arg1:number):Promise<domain.Lesson>;

export function GetLibrarySettings():Promise<storage.LibrarySettings>;

export function GetLinkedAnkiCard(arg1:number,arg2:number):Promise<domain.AnkiReviewCard>;

export function GetMatchByID(arg1:number):Promise<domain.Match>;

export function GetMatchDecisionLosses(arg1:number):Promise<Array<storage.DecisionLoss>>;

export function GetMatchDetailStats(arg1:number):Promise<database.MatchDetailStats>;

export function GetMatchMoveGrades(arg1:number):Promise<Array<storage.MoveGrade>>;

export function GetMatchMovePositions(arg1:number):Promise<Array<domain.MatchMovePosition>>;

export function GetMatchOrigin(arg1:number):Promise<duel.Origin>;

export function GetMatchReview(arg1:number):Promise<storage.MatchReview>;

export function GetMatchTimeSummary(arg1:number):Promise<storage.MatchTimeSummary>;

export function GetMatchTournament(arg1:number):Promise<domain.Tournament>;

export function GetMovesByGame(arg1:number):Promise<Array<domain.Move>>;

export function GetNextAnkiCard(arg1:number):Promise<domain.AnkiReviewCard>;

export function GetPlayerTable(arg1:database.StatsFilter):Promise<Array<database.PlayerRow>>;

export function GetPositionCollections(arg1:number):Promise<Array<database.Collection>>;

export function GetPositionIDsByMatch(arg1:number):Promise<Array<number>>;

export function GetPositionIDsByStatsSelection(arg1:database.StatsFilter,arg2:database.SelectionSpec):Promise<Array<number>>;

export function GetPositionIDsByTournament(arg1:number):Promise<Array<number>>;

export function GetPositionIndexMap():Promise<Record<number, number>>;

export function GetPositionProvenance(arg1:number):Promise<Array<domain.Match>>;

export function GetRandomAnkiCard(arg1:number,arg2:number):Promise<domain.AnkiReviewCard>;

export function GetRencontre(arg1:number):Promise<service.RencontreView>;

export function GetStatsBreakdownPositionCounts(arg1:database.StatsFilter):Promise<Record<string, Record<string, database.BreakdownPositionCount>>>;

export function GetStatsDateRange():Promise<database.StatsDateRange>;

export function GetTimeErrors():Promise<Array<storage.TimeErrorRow>>;

export function GetTournamentMatches(arg1:number):Promise<Array<domain.Match>>;

export function GetTournamentReview(arg1:number,arg2:string):Promise<storage.TournamentReview>;

export function GradeQuizChecker(arg1:number,arg2:domain.Board):Promise<engine.QuizVerdict>;

export function GradeQuizCheckerMove(arg1:number,arg2:string):Promise<engine.QuizVerdict>;

export function GradeQuizCube(arg1:number,arg2:string):Promise<engine.QuizVerdict>;

export function HasDirection(arg1:number):Promise<boolean>;

export function HeadToHead(arg1:string,arg2:string,arg3:database.StatsFilter):Promise<storage.HeadToHead>;

export function HeadToHeadCtx(arg1:context.Context,arg2:string,arg3:string,arg4:database.StatsFilter):Promise<storage.HeadToHead>;

export function History(arg1:number,arg2:string,arg3:string):Promise<Array<service.HistoryEntry>>;

export function ImportBGFMatch(arg1:string):Promise<number>;

export function ImportBGFPosition(arg1:string):Promise<number>;

export function ImportBGFPositionFromText(arg1:string):Promise<number>;

export function ImportDatabase(arg1:string):Promise<Record<string, any>>;

export function ImportFiles(arg1:Array<string>,arg2:database.ImportFilesOptions):Promise<Array<ingest.FileOutcome>>;

export function ImportGnuBGMatch(arg1:string):Promise<number>;

export function ImportGnuBGMatchFromText(arg1:string):Promise<number>;

export function ImportJournal(arg1:number):Promise<Array<domain.ImportFileEntry>>;

export function ImportMET(arg1:string):Promise<domain.MatchEquityTable>;

export function ImportOGXMMatch(arg1:string):Promise<number>;

export function ImportReport(arg1:number):Promise<domain.ImportBatch>;

export function ImportStudyQueue(arg1:number,arg2:number):Promise<Array<domain.StudyQueueEntry>>;

export function ImportXGMatch(arg1:string):Promise<number>;

export function ImportXGPPosition(arg1:string):Promise<number>;

export function IndexOfAnkiDeckFilteredPosition(arg1:number,arg2:string,arg3:number):Promise<number>;

export function IndexOfAnkiDeckPosition(arg1:number,arg2:number):Promise<number>;

export function IndexOfCollectionPosition(arg1:number,arg2:number):Promise<number>;

export function IndexOfPosition(arg1:number):Promise<number>;

export function IndexOfPositionByFilters(arg1:domain.SearchFilters,arg2:number):Promise<number>;

export function IsPositionOnPile(arg1:domain.Position):Promise<boolean>;

export function IsProtectedCopyPath(arg1:string):Promise<boolean>;

export function IsReadOnly():Promise<boolean>;

export function LastDecision(arg1:number):Promise<service.LastDecision>;

export function LessonDoneSteps(arg1:number):Promise<Record<number, string>>;

export function ListAliases(arg1:string):Promise<Array<storage.Alias>>;

export function ListAnkiDeckFilteredPositionIDs(arg1:number,arg2:string,arg3:number,arg4:number):Promise<Array<number>>;

export function ListAnkiDeckPositionIDs(arg1:number,arg2:number,arg3:number):Promise<Array<number>>;

export function ListCollectionPositionIDs(arg1:number,arg2:number,arg3:number):Promise<Array<number>>;

export function ListDirections():Promise<Array<service.DirectionSummary>>;

export function ListDuels():Promise<Array<duel.Summary>>;

export function ListImportBatches(arg1:number,arg2:number):Promise<Array<domain.ImportBatch>>;

export function ListLessons():Promise<Array<domain.Lesson>>;

export function ListMETs():Promise<Array<domain.MatchEquityTable>>;

export function ListMatches(arg1:storage.MatchListOpts):Promise<Array<domain.Match>>;

export function ListPositionIDs(arg1:number,arg2:number):Promise<Array<number>>;

export function ListRencontres():Promise<Array<service.RencontreView>>;

export function ListTranscriptions():Promise<Array<database.TranscriptionSummary>>;

export function ListTrash(arg1:string,arg2:number,arg3:number):Promise<Array<domain.TrashEntry>>;

export function LoadAllPositions():Promise<Array<domain.Position>>;

export function LoadAnalysis(arg1:number):Promise<domain.PositionAnalysis>;

export function LoadCommandHistory():Promise<Array<string>>;

export function LoadComment(arg1:number):Promise<string>;

export function LoadEditPosition(arg1:string):Promise<string>;

export function LoadExcludePosition(arg1:string):Promise<string>;

export function LoadFilters():Promise<Array<Record<string, any>>>;

export function LoadMetadata():Promise<Record<string, string>>;

export function LoadPosition(arg1:number):Promise<domain.Position>;

export function LoadPositionIDsByFilters(arg1:domain.SearchFilters):Promise<Array<number>>;

export function LoadPositionView(arg1:number):Promise<database.PositionView>;

export function LoadPositionsByFilters(arg1:domain.SearchFilters):Promise<Array<domain.Position>>;

export function LoadPositionsByFiltersCore(arg1:domain.SearchFilters,arg2:storage.ListOpts):Promise<Array<domain.Position>>;

export function LoadPositionsByFiltersCoreCtx(arg1:context.Context,arg2:domain.SearchFilters,arg3:storage.ListOpts):Promise<Array<domain.Position>>;

export function LoadPositionsByIDs(arg1:Array<number>):Promise<Array<domain.Position>>;

export function LoadRollouts(arg1:number):Promise<Array<domain.RolloutAnalysis>>;

export function LoadSearchHistory():Promise<Array<database.SearchHistory>>;

export function LoadSessionState():Promise<database.SessionState>;

export function LoadTrainingMissed(arg1:storage.TrainingMissedFilter):Promise<Array<number>>;

export function LoadTrainingNumberStats(arg1:string):Promise<Array<storage.TrainingNumberStat>>;

export function LoadTrainingSessions(arg1:string,arg2:number):Promise<Array<storage.TrainingSession>>;

export function MakeParticipantAbsent(arg1:number,arg2:string,arg3:string,arg4:number):Promise<service.DirectionView>;

export function MakeParticipantAvailable(arg1:number,arg2:string):Promise<service.DirectionView>;

export function MatchMAT(arg1:number):Promise<string>;

export function MatchTranscriptionLosses(arg1:number):Promise<database.TranscriptionLosses>;

export function MaterializeTranscription(arg1:transcript.Header,arg2:Array<transcript.Action>):Promise<database.TranscriptionSaveResult>;

export function MergePlayers(arg1:Array<string>,arg2:string):Promise<void>;

export function MoveMatchToTable(arg1:number,arg2:string,arg3:number):Promise<service.DirectionView>;

export function MovePositionBetweenCollections(arg1:number,arg2:number,arg3:number):Promise<void>;

export function OpenDatabase(arg1:string):Promise<void>;

export function OpenDuel(arg1:number):Promise<database.DuelState>;

export function OpenProtectedCopyPath(arg1:string,arg2:string):Promise<string>;

export function OpenTranscription(arg1:number):Promise<database.TranscriptionState>;

export function PRByWindow(arg1:database.StatsFilter,arg2:number):Promise<Array<storage.WindowStats>>;

export function PRByWindowCtx(arg1:context.Context,arg2:database.StatsFilter,arg3:number):Promise<Array<storage.WindowStats>>;

export function Pairs(arg1:number):Promise<Record<string, Array<storage.PairMember>>>;

export function ParseDirectoryCSV(arg1:number,arg2:string):Promise<service.DirectoryImport>;

export function ParsePositionText(arg1:string):Promise<parser.Result>;

export function Participants(arg1:number):Promise<Array<service.ParticipantRow>>;

export function PendingImportFiles(arg1:Array<string>):Promise<Array<string>>;

export function PendingTranscriptionAnalysis():Promise<database.TranscriptionAnalysisResume>;

export function PileCollectionID():Promise<number>;

export function PlanRollout(arg1:context.Context,arg2:domain.SearchFilters,arg3:rollout.Settings):Promise<database.RolloutPlan>;

export function PlanRolloutIDs(arg1:context.Context,arg2:Array<number>,arg3:rollout.Settings):Promise<database.RolloutPlan>;

export function PlayDuel(arg1:number,arg2:number,arg3:duel.Play):Promise<database.DuelState>;

export function PlayerContrast(arg1:string,arg2:string,arg3:database.StatsFilter):Promise<storage.PlayerContrast>;

export function PlayerContrastCtx(arg1:context.Context,arg2:string,arg3:string,arg4:database.StatsFilter):Promise<storage.PlayerContrast>;

export function PlayerRanking(arg1:database.StatsFilter,arg2:number):Promise<Array<storage.RankedPlayer>>;

export function PlayerRankingCtx(arg1:context.Context,arg2:database.StatsFilter,arg3:number):Promise<Array<storage.RankedPlayer>>;

export function PositionsToRollout(arg1:context.Context,arg2:domain.SearchFilters,arg3:rollout.Settings):Promise<Array<domain.Position>>;

export function PositionsToRolloutIDs(arg1:context.Context,arg2:Array<number>,arg3:rollout.Settings):Promise<Array<domain.Position>>;

export function PreviewAttachToRencontre(arg1:number,arg2:number):Promise<service.ConfigPreview>;

export function PreviewDirectionConfig(arg1:number,arg2:string):Promise<service.ConfigPreview>;

export function RankPositionIDsByFilters(arg1:domain.SearchFilters,arg2:number):Promise<Array<database.RankedID>>;

export function RankPositionsByFilters(arg1:domain.SearchFilters,arg2:number):Promise<Array<storage.SimilarPosition>>;

export function RebuildMatchStats():Promise<number>;

export function RecommendedTags():Promise<Array<string>>;

export function ReencodeAnalyses():Promise<database.ReencodeResult>;

export function RefreshSearchStatistics():Promise<void>;

export function RefuseReadOnly():Promise<void>;

export function ReinstateParticipant(arg1:number,arg2:string):Promise<service.DirectionView>;

export function RemoveAlias(arg1:string,arg2:string):Promise<boolean>;

export function RemoveAnkiCard(arg1:number):Promise<void>;

export function RemoveLessonStep(arg1:number):Promise<void>;

export function RemoveMatchFromTournament(arg1:number):Promise<void>;

export function RemovePositionFromCollection(arg1:number,arg2:number):Promise<void>;

export function RemovePositionsFromCollection(arg1:number,arg2:Array<number>):Promise<void>;

export function RencontreOf(arg1:number):Promise<number>;

export function RencontrePageHTML(arg1:number):Promise<string>;

export function RencontreSearchIndex(arg1:number):Promise<Array<service.SearchEntry>>;

export function RencontreTableGrid(arg1:number):Promise<service.HallView>;

export function ReopenDirection(arg1:number):Promise<service.DirectionView>;

export function ReorderCollectionPositions(arg1:number,arg2:Array<number>):Promise<void>;

export function ReorderCollections(arg1:Array<number>):Promise<void>;

export function ReorderLessonSteps(arg1:number,arg2:Array<number>):Promise<void>;

export function ReorderTournamentMatches(arg1:number,arg2:Array<number>):Promise<void>;

export function RepairAnalyses():Promise<number>;

export function RepairCrawfordSentinel():Promise<number>;

export function RepairGamePhases():Promise<number>;

export function ResetAnkiDeck(arg1:number):Promise<void>;

export function RestoreFromTrash(arg1:number):Promise<domain.TrashRestore>;

export function ResumeImportBatch(arg1:number):Promise<void>;

export function ReviewAnkiCard(arg1:number,arg2:number):Promise<domain.AnkiReviewCard>;

export function RolloutFiltered(arg1:context.Context,arg2:domain.SearchFilters,arg3:rollout.Settings,arg4:any):Promise<rollouts.Summary>;

export function RolloutPosition(arg1:context.Context,arg2:number,arg3:rollout.Settings,arg4:Array<string>,arg5:boolean,arg6:any):Promise<rollout.Result>;

export function RolloutPositions(arg1:context.Context,arg2:Array<domain.Position>,arg3:rollout.Settings,arg4:any):Promise<rollouts.Summary>;

export function RunRolloutPlan(arg1:context.Context,arg2:database.RolloutPlan,arg3:rollout.Settings,arg4:any):Promise<rollouts.Summary>;

export function SaveAnalysis(arg1:number,arg2:domain.PositionAnalysis):Promise<void>;

export function SaveCommand(arg1:string):Promise<void>;

export function SaveComment(arg1:number,arg2:string):Promise<void>;

export function SaveEditPosition(arg1:string,arg2:string):Promise<void>;

export function SaveExcludePosition(arg1:string,arg2:string):Promise<void>;

export function SaveFilter(arg1:string,arg2:string):Promise<void>;

export function SaveIndividualPosition(arg1:domain.Position):Promise<database.IndividualSaveResult>;

export function SaveLastVisitedPosition(arg1:number,arg2:number):Promise<void>;

export function SaveLibrarySettings(arg1:storage.LibrarySettings):Promise<void>;

export function SaveMetadata(arg1:Record<string, string>):Promise<void>;

export function SavePosition(arg1:domain.Position):Promise<number>;

export function SaveSearchHistory(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveSessionState(arg1:database.SessionState):Promise<void>;

export function SaveTrainingSession(arg1:storage.TrainingSession):Promise<number>;

export function ScoreMoves():Promise<number>;

export function SearchComments(arg1:string):Promise<Array<domain.CommentEntry>>;

export function SearchPositionIDs(arg1:domain.SearchFilters,arg2:number,arg3:number):Promise<Array<number>>;

export function SeasonCSV(arg1:service.SeasonQuery):Promise<string>;

export function SeasonRanking(arg1:service.SeasonQuery):Promise<service.SeasonView>;

export function SetAlias(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetAnkiCardSuspended(arg1:number,arg2:boolean):Promise<void>;

export function SetBeforeSwitch(arg1:any):Promise<void>;

export function SetCollectionFilter(arg1:number,arg2:string):Promise<void>;

export function SetCommentAuthor(arg1:string):Promise<void>;

export function SetCurrentMET(arg1:number):Promise<void>;

export function SetDirectionConfig(arg1:number,arg2:string):Promise<void>;

export function SetDirectionOutputDir(arg1:number,arg2:string):Promise<void>;

export function SetDirectionStrings(arg1:string,arg2:string):Promise<void>;

export function SetDirectionTables(arg1:number,arg2:Array<domain.TableSetting>):Promise<service.DirectionView>;

export function SetEventRooms(arg1:number,arg2:number,arg3:Array<string>):Promise<service.RencontreView>;

export function SetFilterPinned(arg1:number,arg2:boolean):Promise<void>;

export function SetLessonStepDone(arg1:number,arg2:boolean):Promise<void>;

export function SetMatchTournamentByName(arg1:number,arg2:string):Promise<void>;

export function SetMatchVideoSource(arg1:number,arg2:string):Promise<void>;

export function SetMigrationProgress(arg1:any):Promise<void>;

export function SetPositionStudied(arg1:number,arg2:boolean):Promise<void>;

export function SetRencontreBreaks(arg1:number,arg2:string):Promise<service.RencontreView>;

export function SetRencontreOutputDir(arg1:number,arg2:string):Promise<service.RencontreView>;

export function SetRencontreTableOutOfService(arg1:number,arg2:number,arg3:boolean):Promise<service.RencontreView>;

export function SetRencontreTables(arg1:number,arg2:Array<domain.TableSetting>):Promise<service.RencontreView>;

export function SetSkipDuplicates(arg1:boolean):Promise<void>;

export function SetupDatabase(arg1:string):Promise<void>;

export function SimilarPositions(arg1:number,arg2:number):Promise<Array<storage.SimilarPosition>>;

export function SinceLastGesture(arg1:number,arg2:number):Promise<Array<service.HistoryEntry>>;

export function SlotOfMatch(arg1:number):Promise<service.MatchSlot>;

export function Slots(arg1:number):Promise<Array<service.SlotRow>>;

export function Standings(arg1:number):Promise<service.StandingsView>;

export function StandingsCSV(arg1:number):Promise<string>;

export function StartMatchManually(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number):Promise<service.DirectionView>;

export function StartTranscriptionFromSlot(arg1:number,arg2:string):Promise<database.TranscriptionState>;

export function StatsMatchIDs(arg1:database.StatsFilter):Promise<Array<number>>;

export function StatsMatchIDsCtx(arg1:context.Context,arg2:database.StatsFilter):Promise<Array<number>>;

export function StatsReportHTML(arg1:database.StatsFilter,arg2:string,arg3:Record<number, string>):Promise<string>;

export function StatsReportHTMLCtx(arg1:context.Context,arg2:database.StatsFilter,arg3:string,arg4:Record<number, string>):Promise<string>;

export function StopDuel(arg1:number,arg2:number,arg3:boolean):Promise<database.DuelState>;

export function StudyBacklog(arg1:number):Promise<Array<domain.StudyQueueEntry>>;

export function StudyImpact(arg1:number):Promise<Array<database.StudyImpactRow>>;

export function StudyPlanPositionIDs(arg1:database.StatsFilter,arg2:number,arg3:number):Promise<Array<number>>;

export function StudyPlanQueue(arg1:database.StatsFilter,arg2:number):Promise<Array<domain.StudyQueueEntry>>;

export function StudyPositionIDs(arg1:database.StatsFilter,arg2:number,arg3:number):Promise<Array<number>>;

export function SuggestAliases(arg1:string):Promise<Array<storage.AliasSuggestion>>;

export function SuggestMatFilename(arg1:number):Promise<string>;

export function SuggestReferencePositions(arg1:database.StatsFilter,arg2:Array<number>,arg3:number):Promise<storage.ReferenceSuggestions>;

export function SuggestReferencePositionsCtx(arg1:context.Context,arg2:database.StatsFilter,arg3:Array<number>,arg4:number):Promise<storage.ReferenceSuggestions>;

export function SuggestTranscriptionMatFilename(arg1:number):Promise<string>;

export function SuspendDuel(arg1:number):Promise<void>;

export function SwapMatchPlayers(arg1:number):Promise<void>;

export function SyncAnkiDeck(arg1:number):Promise<storage.DeckSync>;

export function SyncAnkiDeckWithPositions(arg1:number,arg2:Array<number>):Promise<void>;

export function TableGrid(arg1:number):Promise<Array<service.TableCell>>;

export function TablePlan(arg1:number):Promise<direction.TablePlan>;

export function Tags():Promise<Array<domain.TagCount>>;

export function TogglePile(arg1:domain.Position):Promise<storage.PileToggle>;

export function TranscriptionMAT(arg1:number):Promise<string>;

export function TrashCollection(arg1:number):Promise<number>;

export function TrashCommentEntry(arg1:number):Promise<number>;

export function TrashMatch(arg1:number):Promise<number>;

export function TrashPosition(arg1:number):Promise<number>;

export function TrashRencontre(arg1:number):Promise<number>;

export function UnattachedMatches(arg1:number):Promise<Array<service.SlotSuggestion>>;

export function UpdateAnkiDeck(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateAnkiDeckParams(arg1:number,arg2:number,arg3:number,arg4:boolean,arg5:any):Promise<void>;

export function UpdateCollection(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateCommentEntry(arg1:number,arg2:string):Promise<void>;

export function UpdateFilter(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateLesson(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateLessonStep(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number):Promise<void>;

export function UpdateMatch(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateMatchComment(arg1:number,arg2:string):Promise<void>;

export function UpdatePair(arg1:number,arg2:string,arg3:string,arg4:number):Promise<service.DirectionView>;

export function UpdateParticipant(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number):Promise<service.DirectionView>;

export function UpdatePosition(arg1:domain.Position):Promise<void>;

export function UpdateRencontre(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number):Promise<service.RencontreView>;

export function UpdateTournament(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateTournamentComment(arg1:number,arg2:string):Promise<void>;

export function Vacuum():Promise<database.VacuumResult>;

export function WithdrawParticipant(arg1:number,arg2:string,arg3:boolean):Promise<service.DirectionView>;

export function WriteDirectionPage(arg1:number):Promise<string>;

export function WriteDirectionPairingSheet(arg1:number,arg2:number):Promise<string>;

export function WriteDirectionUpcomingSheet(arg1:number,arg2:string):Promise<string>;

export function WriteRencontrePage(arg1:number):Promise<string>;
