// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddComment(arg1, arg2) {
  return window['go']['database']['Database']['AddComment'](arg1, arg2);
}

export function AddMatchToTournament(arg1, arg2) {
  return window['go']['database']['Database']['AddMatchToTournament'](arg1, arg2);
}

export function AddPositionToCollection(arg1, arg2) {
  return window['go']['database']['Database']['AddPositionToCollection'](arg1, arg2);
}

export function AddPositionsToCollection(arg1, arg2) {
  return window['go']['database']['Database']['AddPositionsToCollection'](arg1, arg2);
}

export function AnalyzeImportDatabase(arg1) {
  return window['go']['database']['Database']['AnalyzeImportDatabase'](arg1);
}

export function AnalyzeMissingWithGammonNet(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['database']['Database']['AnalyzeMissingWithGammonNet'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function AnalyzeStaleGammonNet(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['database']['Database']['AnalyzeStaleGammonNet'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function BeginImportBatch(arg1, arg2) {
  return window['go']['database']['Database']['BeginImportBatch'](arg1, arg2);
}

export function BuryAnkiCard(arg1) {
  return window['go']['database']['Database']['BuryAnkiCard'](arg1);
}

export function CancelImport() {
  return window['go']['database']['Database']['CancelImport']();
}

export function CheckConstraints() {
  return window['go']['database']['Database']['CheckConstraints']();
}

export function CheckCounters() {
  return window['go']['database']['Database']['CheckCounters']();
}

export function CheckDatabaseVersion() {
  return window['go']['database']['Database']['CheckDatabaseVersion']();
}

export function CheckMatchExists(arg1) {
  return window['go']['database']['Database']['CheckMatchExists'](arg1);
}

export function CheckSchema() {
  return window['go']['database']['Database']['CheckSchema']();
}

export function CheckVersion(arg1) {
  return window['go']['database']['Database']['CheckVersion'](arg1);
}

export function Checkpoint() {
  return window['go']['database']['Database']['Checkpoint']();
}

export function ClearCommandHistory() {
  return window['go']['database']['Database']['ClearCommandHistory']();
}

export function ClearSessionState() {
  return window['go']['database']['Database']['ClearSessionState']();
}

export function Close() {
  return window['go']['database']['Database']['Close']();
}

export function CollectionCoverage(arg1) {
  return window['go']['database']['Database']['CollectionCoverage'](arg1);
}

export function CommitImportDatabase(arg1) {
  return window['go']['database']['Database']['CommitImportDatabase'](arg1);
}

export function CompareWithGammonNet(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['database']['Database']['CompareWithGammonNet'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ComputeEPCFromPosition(arg1) {
  return window['go']['database']['Database']['ComputeEPCFromPosition'](arg1);
}

export function ComputeStats(arg1) {
  return window['go']['database']['Database']['ComputeStats'](arg1);
}

export function ComputeStatsCtx(arg1, arg2) {
  return window['go']['database']['Database']['ComputeStatsCtx'](arg1, arg2);
}

export function CopyPositionToCollection(arg1, arg2) {
  return window['go']['database']['Database']['CopyPositionToCollection'](arg1, arg2);
}

export function CountOrphans() {
  return window['go']['database']['Database']['CountOrphans']();
}

export function CountPositionsWithForeignAnalysis() {
  return window['go']['database']['Database']['CountPositionsWithForeignAnalysis']();
}

export function CountPositionsWithStaleGammonNet(arg1) {
  return window['go']['database']['Database']['CountPositionsWithStaleGammonNet'](arg1);
}

export function CountPositionsWithoutAnalysis() {
  return window['go']['database']['Database']['CountPositionsWithoutAnalysis']();
}

export function CountTrash() {
  return window['go']['database']['Database']['CountTrash']();
}

export function CreateAnkiDeck(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['database']['Database']['CreateAnkiDeck'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateCollection(arg1, arg2) {
  return window['go']['database']['Database']['CreateCollection'](arg1, arg2);
}

export function CreateTournament(arg1, arg2, arg3) {
  return window['go']['database']['Database']['CreateTournament'](arg1, arg2, arg3);
}

export function DeleteAnalysis(arg1) {
  return window['go']['database']['Database']['DeleteAnalysis'](arg1);
}

export function DeleteAnkiDeck(arg1) {
  return window['go']['database']['Database']['DeleteAnkiDeck'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['database']['Database']['DeleteCollection'](arg1);
}

export function DeleteComment(arg1) {
  return window['go']['database']['Database']['DeleteComment'](arg1);
}

export function DeleteCommentEntry(arg1) {
  return window['go']['database']['Database']['DeleteCommentEntry'](arg1);
}

export function DeleteFilter(arg1) {
  return window['go']['database']['Database']['DeleteFilter'](arg1);
}

export function DeleteMatch(arg1) {
  return window['go']['database']['Database']['DeleteMatch'](arg1);
}

export function DeletePosition(arg1) {
  return window['go']['database']['Database']['DeletePosition'](arg1);
}

export function DeleteProtectedCopyPath(arg1) {
  return window['go']['database']['Database']['DeleteProtectedCopyPath'](arg1);
}

export function DeleteSearchHistoryEntry(arg1) {
  return window['go']['database']['Database']['DeleteSearchHistoryEntry'](arg1);
}

export function DeleteTournament(arg1) {
  return window['go']['database']['Database']['DeleteTournament'](arg1);
}

export function DiscardFromTrash(arg1) {
  return window['go']['database']['Database']['DiscardFromTrash'](arg1);
}

export function EmptyTrash(arg1) {
  return window['go']['database']['Database']['EmptyTrash'](arg1);
}

export function ExportCollections(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['database']['Database']['ExportCollections'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ExportDatabase(arg1) {
  return window['go']['database']['Database']['ExportDatabase'](arg1);
}

export function ExportDatabaseCtx(arg1, arg2) {
  return window['go']['database']['Database']['ExportDatabaseCtx'](arg1, arg2);
}

export function ExportMatchMAT(arg1, arg2) {
  return window['go']['database']['Database']['ExportMatchMAT'](arg1, arg2);
}

export function ExportTournaments(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['database']['Database']['ExportTournaments'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function FinishImportBatch(arg1, arg2) {
  return window['go']['database']['Database']['FinishImportBatch'](arg1, arg2);
}

export function GetAllAnkiDecks() {
  return window['go']['database']['Database']['GetAllAnkiDecks']();
}

export function GetAllCollections() {
  return window['go']['database']['Database']['GetAllCollections']();
}

export function GetAllComments() {
  return window['go']['database']['Database']['GetAllComments']();
}

export function GetAllMatches() {
  return window['go']['database']['Database']['GetAllMatches']();
}

export function GetAllPlayerNames() {
  return window['go']['database']['Database']['GetAllPlayerNames']();
}

export function GetAllTournaments() {
  return window['go']['database']['Database']['GetAllTournaments']();
}

export function GetAnkiDeckPositions(arg1) {
  return window['go']['database']['Database']['GetAnkiDeckPositions'](arg1);
}

export function GetAnkiDeckRetention(arg1) {
  return window['go']['database']['Database']['GetAnkiDeckRetention'](arg1);
}

export function GetAnkiDeckStats(arg1) {
  return window['go']['database']['Database']['GetAnkiDeckStats'](arg1);
}

export function GetAnkiForecast(arg1, arg2) {
  return window['go']['database']['Database']['GetAnkiForecast'](arg1, arg2);
}

export function GetAnkiReviewLog(arg1, arg2) {
  return window['go']['database']['Database']['GetAnkiReviewLog'](arg1, arg2);
}

export function GetCollectionByID(arg1) {
  return window['go']['database']['Database']['GetCollectionByID'](arg1);
}

export function GetCollectionPositions(arg1) {
  return window['go']['database']['Database']['GetCollectionPositions'](arg1);
}

export function GetCommentsByPosition(arg1) {
  return window['go']['database']['Database']['GetCommentsByPosition'](arg1);
}

export function GetDatabaseStats() {
  return window['go']['database']['Database']['GetDatabaseStats']();
}

export function GetDatabaseVersion() {
  return window['go']['database']['Database']['GetDatabaseVersion']();
}

export function GetGamesByMatch(arg1) {
  return window['go']['database']['Database']['GetGamesByMatch'](arg1);
}

export function GetIssuanceInfo() {
  return window['go']['database']['Database']['GetIssuanceInfo']();
}

export function GetLastVisitedMatch() {
  return window['go']['database']['Database']['GetLastVisitedMatch']();
}

export function GetMatchByID(arg1) {
  return window['go']['database']['Database']['GetMatchByID'](arg1);
}

export function GetMatchDetailStats(arg1) {
  return window['go']['database']['Database']['GetMatchDetailStats'](arg1);
}

export function GetMatchMovePositions(arg1) {
  return window['go']['database']['Database']['GetMatchMovePositions'](arg1);
}

export function GetMatchTournament(arg1) {
  return window['go']['database']['Database']['GetMatchTournament'](arg1);
}

export function GetMovesByGame(arg1) {
  return window['go']['database']['Database']['GetMovesByGame'](arg1);
}

export function GetNextAnkiCard(arg1) {
  return window['go']['database']['Database']['GetNextAnkiCard'](arg1);
}

export function GetPlayerTable(arg1) {
  return window['go']['database']['Database']['GetPlayerTable'](arg1);
}

export function GetPositionCollections(arg1) {
  return window['go']['database']['Database']['GetPositionCollections'](arg1);
}

export function GetPositionIDsByMatch(arg1) {
  return window['go']['database']['Database']['GetPositionIDsByMatch'](arg1);
}

export function GetPositionIDsByStatsSelection(arg1, arg2) {
  return window['go']['database']['Database']['GetPositionIDsByStatsSelection'](arg1, arg2);
}

export function GetPositionIDsByTournament(arg1) {
  return window['go']['database']['Database']['GetPositionIDsByTournament'](arg1);
}

export function GetPositionIndexMap() {
  return window['go']['database']['Database']['GetPositionIndexMap']();
}

export function GetPositionProvenance(arg1) {
  return window['go']['database']['Database']['GetPositionProvenance'](arg1);
}

export function GetRandomAnkiCard(arg1, arg2) {
  return window['go']['database']['Database']['GetRandomAnkiCard'](arg1, arg2);
}

export function GetStatsDateRange() {
  return window['go']['database']['Database']['GetStatsDateRange']();
}

export function GetTournamentMatches(arg1) {
  return window['go']['database']['Database']['GetTournamentMatches'](arg1);
}

export function ImportBGFMatch(arg1) {
  return window['go']['database']['Database']['ImportBGFMatch'](arg1);
}

export function ImportBGFPosition(arg1) {
  return window['go']['database']['Database']['ImportBGFPosition'](arg1);
}

export function ImportBGFPositionFromText(arg1) {
  return window['go']['database']['Database']['ImportBGFPositionFromText'](arg1);
}

export function ImportDatabase(arg1) {
  return window['go']['database']['Database']['ImportDatabase'](arg1);
}

export function ImportGnuBGMatch(arg1) {
  return window['go']['database']['Database']['ImportGnuBGMatch'](arg1);
}

export function ImportGnuBGMatchFromText(arg1) {
  return window['go']['database']['Database']['ImportGnuBGMatchFromText'](arg1);
}

export function ImportReport(arg1) {
  return window['go']['database']['Database']['ImportReport'](arg1);
}

export function ImportStudyQueue(arg1, arg2) {
  return window['go']['database']['Database']['ImportStudyQueue'](arg1, arg2);
}

export function ImportXGMatch(arg1) {
  return window['go']['database']['Database']['ImportXGMatch'](arg1);
}

export function ImportXGPPosition(arg1) {
  return window['go']['database']['Database']['ImportXGPPosition'](arg1);
}

export function IsProtectedCopyPath(arg1) {
  return window['go']['database']['Database']['IsProtectedCopyPath'](arg1);
}

export function IsReadOnly() {
  return window['go']['database']['Database']['IsReadOnly']();
}

export function ListImportBatches(arg1, arg2) {
  return window['go']['database']['Database']['ListImportBatches'](arg1, arg2);
}

export function ListPositionIDs() {
  return window['go']['database']['Database']['ListPositionIDs']();
}

export function ListTrash(arg1, arg2, arg3) {
  return window['go']['database']['Database']['ListTrash'](arg1, arg2, arg3);
}

export function LoadAllPositions() {
  return window['go']['database']['Database']['LoadAllPositions']();
}

export function GradeQuizChecker(arg1, arg2) {
  return window['go']['database']['Database']['GradeQuizChecker'](arg1, arg2);
}

export function GradeQuizCheckerMove(arg1, arg2) {
  return window['go']['database']['Database']['GradeQuizCheckerMove'](arg1, arg2);
}

export function GradeQuizCube(arg1, arg2) {
  return window['go']['database']['Database']['GradeQuizCube'](arg1, arg2);
}

export function LoadAnalysis(arg1) {
  return window['go']['database']['Database']['LoadAnalysis'](arg1);
}

export function LoadCommandHistory() {
  return window['go']['database']['Database']['LoadCommandHistory']();
}

export function LoadComment(arg1) {
  return window['go']['database']['Database']['LoadComment'](arg1);
}

export function LoadEditPosition(arg1) {
  return window['go']['database']['Database']['LoadEditPosition'](arg1);
}

export function LoadExcludePosition(arg1) {
  return window['go']['database']['Database']['LoadExcludePosition'](arg1);
}

export function LoadFilters() {
  return window['go']['database']['Database']['LoadFilters']();
}

export function LoadMetadata() {
  return window['go']['database']['Database']['LoadMetadata']();
}

export function LoadPosition(arg1) {
  return window['go']['database']['Database']['LoadPosition'](arg1);
}

export function LoadPositionIDsByFilters(arg1) {
  return window['go']['database']['Database']['LoadPositionIDsByFilters'](arg1);
}

export function LoadPositionsByFilters(arg1) {
  return window['go']['database']['Database']['LoadPositionsByFilters'](arg1);
}

export function LoadPositionsByFiltersCore(arg1, arg2) {
  return window['go']['database']['Database']['LoadPositionsByFiltersCore'](arg1, arg2);
}

export function LoadPositionsByFiltersCoreCtx(arg1, arg2, arg3) {
  return window['go']['database']['Database']['LoadPositionsByFiltersCoreCtx'](arg1, arg2, arg3);
}

export function LoadPositionsByIDs(arg1) {
  return window['go']['database']['Database']['LoadPositionsByIDs'](arg1);
}

export function LoadSearchHistory() {
  return window['go']['database']['Database']['LoadSearchHistory']();
}

export function LoadSessionState() {
  return window['go']['database']['Database']['LoadSessionState']();
}

export function MergePlayers(arg1, arg2) {
  return window['go']['database']['Database']['MergePlayers'](arg1, arg2);
}

export function MovePositionBetweenCollections(arg1, arg2, arg3) {
  return window['go']['database']['Database']['MovePositionBetweenCollections'](arg1, arg2, arg3);
}

export function OpenDatabase(arg1) {
  return window['go']['database']['Database']['OpenDatabase'](arg1);
}

export function OpenProtectedCopyPath(arg1, arg2) {
  return window['go']['database']['Database']['OpenProtectedCopyPath'](arg1, arg2);
}

export function ParsePositionText(arg1) {
  return window['go']['database']['Database']['ParsePositionText'](arg1);
}

export function RecommendedTags() {
  return window['go']['database']['Database']['RecommendedTags']();
}

export function RefreshSearchStatistics() {
  return window['go']['database']['Database']['RefreshSearchStatistics']();
}

export function RemoveAnkiCard(arg1) {
  return window['go']['database']['Database']['RemoveAnkiCard'](arg1);
}

export function RemoveMatchFromTournament(arg1) {
  return window['go']['database']['Database']['RemoveMatchFromTournament'](arg1);
}

export function RemovePositionFromCollection(arg1, arg2) {
  return window['go']['database']['Database']['RemovePositionFromCollection'](arg1, arg2);
}

export function RemovePositionsFromCollection(arg1, arg2) {
  return window['go']['database']['Database']['RemovePositionsFromCollection'](arg1, arg2);
}

export function ReorderCollectionPositions(arg1, arg2) {
  return window['go']['database']['Database']['ReorderCollectionPositions'](arg1, arg2);
}

export function ReorderCollections(arg1) {
  return window['go']['database']['Database']['ReorderCollections'](arg1);
}

export function ReorderTournamentMatches(arg1, arg2) {
  return window['go']['database']['Database']['ReorderTournamentMatches'](arg1, arg2);
}

export function RepairAnalyses() {
  return window['go']['database']['Database']['RepairAnalyses']();
}

export function RepairGamePhases() {
  return window['go']['database']['Database']['RepairGamePhases']();
}

export function ResetAnkiDeck(arg1) {
  return window['go']['database']['Database']['ResetAnkiDeck'](arg1);
}

export function RestoreFromTrash(arg1) {
  return window['go']['database']['Database']['RestoreFromTrash'](arg1);
}

export function ReviewAnkiCard(arg1, arg2) {
  return window['go']['database']['Database']['ReviewAnkiCard'](arg1, arg2);
}

export function SaveAnalysis(arg1, arg2) {
  return window['go']['database']['Database']['SaveAnalysis'](arg1, arg2);
}

export function SaveCommand(arg1) {
  return window['go']['database']['Database']['SaveCommand'](arg1);
}

export function SaveComment(arg1, arg2) {
  return window['go']['database']['Database']['SaveComment'](arg1, arg2);
}

export function SaveEditPosition(arg1, arg2) {
  return window['go']['database']['Database']['SaveEditPosition'](arg1, arg2);
}

export function SaveExcludePosition(arg1, arg2) {
  return window['go']['database']['Database']['SaveExcludePosition'](arg1, arg2);
}

export function SaveFilter(arg1, arg2) {
  return window['go']['database']['Database']['SaveFilter'](arg1, arg2);
}

export function SaveIndividualPosition(arg1) {
  return window['go']['database']['Database']['SaveIndividualPosition'](arg1);
}

export function SaveLastVisitedPosition(arg1, arg2) {
  return window['go']['database']['Database']['SaveLastVisitedPosition'](arg1, arg2);
}

export function SaveMetadata(arg1) {
  return window['go']['database']['Database']['SaveMetadata'](arg1);
}

export function SavePosition(arg1) {
  return window['go']['database']['Database']['SavePosition'](arg1);
}

export function SaveSearchHistory(arg1, arg2, arg3) {
  return window['go']['database']['Database']['SaveSearchHistory'](arg1, arg2, arg3);
}

export function SaveSessionState(arg1) {
  return window['go']['database']['Database']['SaveSessionState'](arg1);
}

export function SearchComments(arg1) {
  return window['go']['database']['Database']['SearchComments'](arg1);
}

export function SetAnkiCardSuspended(arg1, arg2) {
  return window['go']['database']['Database']['SetAnkiCardSuspended'](arg1, arg2);
}

export function SetMatchTournamentByName(arg1, arg2) {
  return window['go']['database']['Database']['SetMatchTournamentByName'](arg1, arg2);
}

export function SetMigrationProgress(arg1) {
  return window['go']['database']['Database']['SetMigrationProgress'](arg1);
}

export function SetupDatabase(arg1) {
  return window['go']['database']['Database']['SetupDatabase'](arg1);
}

export function SuggestMatFilename(arg1) {
  return window['go']['database']['Database']['SuggestMatFilename'](arg1);
}

export function SwapMatchPlayers(arg1) {
  return window['go']['database']['Database']['SwapMatchPlayers'](arg1);
}

export function SyncAnkiDeck(arg1) {
  return window['go']['database']['Database']['SyncAnkiDeck'](arg1);
}

export function SyncAnkiDeckWithPositions(arg1, arg2) {
  return window['go']['database']['Database']['SyncAnkiDeckWithPositions'](arg1, arg2);
}

export function Tags() {
  return window['go']['database']['Database']['Tags']();
}

export function TrashCollection(arg1) {
  return window['go']['database']['Database']['TrashCollection'](arg1);
}

export function TrashCommentEntry(arg1) {
  return window['go']['database']['Database']['TrashCommentEntry'](arg1);
}

export function TrashPosition(arg1) {
  return window['go']['database']['Database']['TrashPosition'](arg1);
}

export function UpdateAnkiDeck(arg1, arg2, arg3) {
  return window['go']['database']['Database']['UpdateAnkiDeck'](arg1, arg2, arg3);
}

export function UpdateAnkiDeckParams(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['database']['Database']['UpdateAnkiDeckParams'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateCollection(arg1, arg2, arg3) {
  return window['go']['database']['Database']['UpdateCollection'](arg1, arg2, arg3);
}

export function UpdateCommentEntry(arg1, arg2) {
  return window['go']['database']['Database']['UpdateCommentEntry'](arg1, arg2);
}

export function UpdateFilter(arg1, arg2, arg3) {
  return window['go']['database']['Database']['UpdateFilter'](arg1, arg2, arg3);
}

export function UpdateMatch(arg1, arg2, arg3, arg4) {
  return window['go']['database']['Database']['UpdateMatch'](arg1, arg2, arg3, arg4);
}

export function UpdateMatchComment(arg1, arg2) {
  return window['go']['database']['Database']['UpdateMatchComment'](arg1, arg2);
}

export function UpdatePosition(arg1) {
  return window['go']['database']['Database']['UpdatePosition'](arg1);
}

export function UpdateTournament(arg1, arg2, arg3, arg4) {
  return window['go']['database']['Database']['UpdateTournament'](arg1, arg2, arg3, arg4);
}

export function UpdateTournamentComment(arg1, arg2) {
  return window['go']['database']['Database']['UpdateTournamentComment'](arg1, arg2);
}

export function Vacuum() {
  return window['go']['database']['Database']['Vacuum']();
}
