// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {database} from '../models';
import {sql} from '../models';
import {parser} from '../models';

export function AddComment(arg1:number,arg2:string):Promise<void>;

export function AddMatchToTournament(arg1:number,arg2:number):Promise<void>;

export function AddPositionToCollection(arg1:number,arg2:number):Promise<void>;

export function AddPositionsToCollection(arg1:number,arg2:Array<number>):Promise<void>;

export function AnalyzeImportDatabase(arg1:string):Promise<Record<string, any>>;

export function CancelImport():Promise<void>;

export function CheckDatabaseVersion():Promise<string>;

export function CheckMatchExists(arg1:string):Promise<number>;

export function CheckVersion(arg1:string):Promise<void>;

export function ClearCommandHistory():Promise<void>;

export function ClearSessionState():Promise<void>;

export function Close():Promise<void>;

export function CommitImportDatabase(arg1:string):Promise<Record<string, any>>;

export function ComputeEPCFromPosition(arg1:domain.Position):Promise<Record<string, any>>;

export function ComputeStats(arg1:database.StatsFilter):Promise<database.StatsResult>;

export function Conn():Promise<sql.DB>;

export function CopyPositionToCollection(arg1:number,arg2:number):Promise<void>;

export function CreateAnkiDeck(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<number>;

export function CreateCollection(arg1:string,arg2:string):Promise<number>;

export function CreateTournament(arg1:string,arg2:string,arg3:string):Promise<number>;

export function DeleteAnalysis(arg1:number):Promise<void>;

export function DeleteAnkiDeck(arg1:number):Promise<void>;

export function DeleteCollection(arg1:number):Promise<void>;

export function DeleteComment(arg1:number):Promise<void>;

export function DeleteCommentEntry(arg1:number):Promise<void>;

export function DeleteFilter(arg1:number):Promise<void>;

export function DeleteMatch(arg1:number):Promise<void>;

export function DeletePosition(arg1:number):Promise<void>;

export function DeleteSearchHistoryEntry(arg1:number):Promise<void>;

export function DeleteTournament(arg1:number):Promise<void>;

export function ExportCollections(arg1:string,arg2:Array<number>,arg3:Record<string, string>,arg4:boolean,arg5:boolean):Promise<void>;

export function ExportDatabase(arg1:domain.ExportOptions):Promise<void>;

export function ExportTournaments(arg1:string,arg2:Array<number>,arg3:Record<string, string>,arg4:boolean,arg5:boolean):Promise<void>;

export function GetAllAnkiDecks():Promise<Array<domain.AnkiDeck>>;

export function GetAllCollections():Promise<Array<database.Collection>>;

export function GetAllComments():Promise<Array<domain.CommentEntry>>;

export function GetAllMatches():Promise<Array<domain.Match>>;

export function GetAllPlayerNames():Promise<Array<database.PlayerFrequency>>;

export function GetAllTournaments():Promise<Array<domain.Tournament>>;

export function GetAnkiDeckPositions(arg1:number):Promise<Array<domain.Position>>;

export function GetAnkiDeckStats(arg1:number):Promise<domain.AnkiDeckStats>;

export function GetCollectionByID(arg1:number):Promise<database.Collection>;

export function GetCollectionPositions(arg1:number):Promise<Array<domain.Position>>;

export function GetCommentsByPosition(arg1:number):Promise<Array<domain.CommentEntry>>;

export function GetDatabaseStats():Promise<Record<string, any>>;

export function GetDatabaseVersion():Promise<string>;

export function GetGamesByMatch(arg1:number):Promise<Array<domain.Game>>;

export function GetLastVisitedMatch():Promise<domain.Match>;

export function GetMatchByID(arg1:number):Promise<domain.Match>;

export function GetMatchDetailStats(arg1:number):Promise<database.MatchDetailStats>;

export function GetMatchMovePositions(arg1:number):Promise<Array<domain.MatchMovePosition>>;

export function GetMatchTournament(arg1:number):Promise<domain.Tournament>;

export function GetMovesByGame(arg1:number):Promise<Array<domain.Move>>;

export function GetNextAnkiCard(arg1:number):Promise<domain.AnkiReviewCard>;

export function GetPositionCollections(arg1:number):Promise<Array<database.Collection>>;

export function GetPositionIDsByMatch(arg1:number):Promise<Array<number>>;

export function GetPositionIDsByStatsSelection(arg1:database.StatsFilter,arg2:database.SelectionSpec):Promise<Array<number>>;

export function GetPositionIDsByTournament(arg1:number):Promise<Array<number>>;

export function GetPositionIndexMap():Promise<Record<number, number>>;

export function GetRandomAnkiCard(arg1:number,arg2:number):Promise<domain.AnkiReviewCard>;

export function GetStatsDateRange():Promise<database.StatsDateRange>;

export function GetTournamentMatches(arg1:number):Promise<Array<domain.Match>>;

export function ImportBGFMatch(arg1:string):Promise<number>;

export function ImportBGFPosition(arg1:string):Promise<number>;

export function ImportBGFPositionFromText(arg1:string):Promise<number>;

export function ImportDatabase(arg1:string):Promise<Record<string, any>>;

export function ImportGnuBGMatch(arg1:string):Promise<number>;

export function ImportGnuBGMatchFromText(arg1:string):Promise<number>;

export function ImportXGMatch(arg1:string):Promise<number>;

export function ImportXGPPosition(arg1:string):Promise<number>;

export function LoadAllPositions():Promise<Array<domain.Position>>;

export function LoadAnalysis(arg1:number):Promise<domain.PositionAnalysis>;

export function LoadCommandHistory():Promise<Array<string>>;

export function LoadComment(arg1:number):Promise<string>;

export function LoadEditPosition(arg1:string):Promise<string>;

export function LoadExcludePosition(arg1:string):Promise<string>;

export function LoadFilters():Promise<Array<Record<string, any>>>;

export function LoadMetadata():Promise<Record<string, string>>;

export function LoadPosition(arg1:number):Promise<domain.Position>;

export function LoadPositionsByFilters(arg1:domain.SearchFilters):Promise<Array<domain.Position>>;

export function LoadPositionsByFiltersCore(arg1:domain.SearchFilters):Promise<Array<domain.Position>>;

export function LoadSearchHistory():Promise<Array<database.SearchHistory>>;

export function LoadSessionState():Promise<database.SessionState>;

export function MergePlayers(arg1:Array<string>,arg2:string):Promise<void>;

export function Migrate_1_0_0_to_1_1_0():Promise<void>;

export function Migrate_1_1_0_to_1_2_0():Promise<void>;

export function Migrate_1_2_0_to_1_3_0():Promise<void>;

export function MovePositionBetweenCollections(arg1:number,arg2:number,arg3:number):Promise<void>;

export function OpenDatabase(arg1:string):Promise<void>;

export function ParsePositionText(arg1:string):Promise<parser.Result>;

export function PositionExists(arg1:domain.Position):Promise<Record<string, any>>;

export function RemoveMatchFromTournament(arg1:number):Promise<void>;

export function RemovePositionFromCollection(arg1:number,arg2:number):Promise<void>;

export function RemovePositionsFromCollection(arg1:number,arg2:Array<number>):Promise<void>;

export function ReorderCollectionPositions(arg1:number,arg2:Array<number>):Promise<void>;

export function ReorderCollections(arg1:Array<number>):Promise<void>;

export function ReorderTournamentMatches(arg1:number,arg2:Array<number>):Promise<void>;

export function ResetAnkiDeck(arg1:number):Promise<void>;

export function ReviewAnkiCard(arg1:number,arg2:number):Promise<domain.AnkiReviewCard>;

export function SaveAnalysis(arg1:number,arg2:domain.PositionAnalysis):Promise<void>;

export function SaveCommand(arg1:string):Promise<void>;

export function SaveComment(arg1:number,arg2:string):Promise<void>;

export function SaveEditPosition(arg1:string,arg2:string):Promise<void>;

export function SaveExcludePosition(arg1:string,arg2:string):Promise<void>;

export function SaveFilter(arg1:string,arg2:string):Promise<void>;

export function SaveIndividualPosition(arg1:domain.Position):Promise<database.IndividualSaveResult>;

export function SaveLastVisitedPosition(arg1:number,arg2:number):Promise<void>;

export function SaveMetadata(arg1:Record<string, string>):Promise<void>;

export function SavePosition(arg1:domain.Position):Promise<number>;

export function SaveSearchHistory(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveSessionState(arg1:database.SessionState):Promise<void>;

export function SearchComments(arg1:string):Promise<Array<domain.CommentEntry>>;

export function SetMatchTournamentByName(arg1:number,arg2:string):Promise<void>;

export function SetMigrationProgress(arg1:any):Promise<void>;

export function SetupDatabase(arg1:string):Promise<void>;

export function SwapMatchPlayers(arg1:number):Promise<void>;

export function SyncAnkiDeck(arg1:number):Promise<void>;

export function SyncAnkiDeckWithPositions(arg1:number,arg2:Array<number>):Promise<void>;

export function UpdateAnkiDeck(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateAnkiDeckParams(arg1:number,arg2:number,arg3:number,arg4:boolean):Promise<void>;

export function UpdateCollection(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateCommentEntry(arg1:number,arg2:string):Promise<void>;

export function UpdateFilter(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateMatch(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateMatchComment(arg1:number,arg2:string):Promise<void>;

export function UpdatePosition(arg1:domain.Position):Promise<void>;

export function UpdateTournament(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateTournamentComment(arg1:number,arg2:string):Promise<void>;
