// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {context} from '../models';
import {transcript} from '../models';
import {sqlite} from '../models';
import {gammonnet} from '../models';
import {domain} from '../models';
import {race} from '../models';
import {direction} from '../models';
import {engine} from '../models';
import {tournoi} from '../models';
import {storage} from '../models';
import {parser} from '../models';

export function AddComment(arg1:number,arg2:string):Promise<void>;

export function AddMatchToTournament(arg1:number,arg2:number):Promise<void>;

export function AddParticipant(arg1:number,arg2:string,arg3:string,arg4:number):Promise<database.DirectionView>;

export function AddPositionToCollection(arg1:number,arg2:number):Promise<void>;

export function AddPositionsToCollection(arg1:number,arg2:Array<number>):Promise<void>;

export function AnalyzeImportDatabase(arg1:string):Promise<Record<string, any>>;

export function AnalyzeMatchWithGammonNet(arg1:context.Context,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number,arg7:any,arg8:any):Promise<database.GammonNetBatchSummary>;

export function AnalyzeMissingWithGammonNet(arg1:context.Context,arg2:number,arg3:number,arg4:number,arg5:number,arg6:any,arg7:any):Promise<database.GammonNetBatchSummary>;

export function AnalyzeStaleGammonNet(arg1:context.Context,arg2:number,arg3:number,arg4:number,arg5:number,arg6:any,arg7:any):Promise<database.GammonNetBatchSummary>;

export function ApplyTranscriptionGesture(arg1:number,arg2:transcript.Gesture):Promise<database.TranscriptionState>;

export function BeginImportBatch(arg1:string,arg2:string):Promise<number>;

export function BuryAnkiCard(arg1:number):Promise<void>;

export function CancelImport():Promise<void>;

export function CancelMatch(arg1:number,arg2:string):Promise<database.DirectionView>;

export function CheckConstraints():Promise<Array<database.ConstraintViolation>>;

export function CheckCounters():Promise<database.CounterDrift>;

export function CheckDatabaseVersion():Promise<string>;

export function CheckMatchExists(arg1:string):Promise<number>;

export function CheckSchema():Promise<sqlite.SchemaDrift>;

export function CheckVersion(arg1:string):Promise<void>;

export function Checkpoint():Promise<void>;

export function ClearCommandHistory():Promise<void>;

export function ClearSessionState():Promise<void>;

export function Close():Promise<void>;

export function CloseTranscription(arg1:number):Promise<void>;

export function CollectionCoverage(arg1:Array<number>):Promise<Record<number, number>>;

export function CommitImportDatabase(arg1:string):Promise<Record<string, any>>;

export function CompareWithGammonNet(arg1:context.Context,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number,arg7:any):Promise<gammonnet.AnalysisComparison>;

export function ComputeEPCFromPosition(arg1:domain.Position):Promise<race.Result>;

export function ComputeStats(arg1:database.StatsFilter):Promise<database.StatsResult>;

export function ComputeStatsCtx(arg1:context.Context,arg2:database.StatsFilter):Promise<database.StatsResult>;

export function ConfirmAllProposals(arg1:number):Promise<database.DirectionView>;

export function ConfirmProposal(arg1:number,arg2:string):Promise<database.DirectionView>;

export function CopyPositionToCollection(arg1:number,arg2:number):Promise<void>;

export function CorrectResult(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number,arg6:string):Promise<database.DirectionView>;

export function CountMatchPositionsToAnalyze(arg1:number):Promise<number>;

export function CountOrphans():Promise<database.OrphanCounts>;

export function CountPositionsWithForeignAnalysis():Promise<number>;

export function CountPositionsWithStaleGammonNet(arg1:number):Promise<number>;

export function CountPositionsWithoutAnalysis():Promise<number>;

export function CountTrash():Promise<number>;

export function CreateAnkiDeck(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<number>;

export function CreateCollection(arg1:string,arg2:string):Promise<number>;

export function CreateDirection(arg1:number,arg2:string,arg3:number):Promise<void>;

export function CreateTournament(arg1:string,arg2:string,arg3:string):Promise<number>;

export function CreateTranscription(arg1:transcript.Header):Promise<database.TranscriptionState>;

export function DeleteAnalysis(arg1:number):Promise<void>;

export function DeleteAnkiDeck(arg1:number):Promise<void>;

export function DeleteCollection(arg1:number):Promise<void>;

export function DeleteComment(arg1:number):Promise<void>;

export function DeleteCommentEntry(arg1:number):Promise<void>;

export function DeleteDirection(arg1:number):Promise<void>;

export function DeleteFilter(arg1:number):Promise<void>;

export function DeleteMatch(arg1:number):Promise<void>;

export function DeletePosition(arg1:number):Promise<void>;

export function DeleteProtectedCopyPath(arg1:string):Promise<void>;

export function DeleteSearchHistoryEntry(arg1:number):Promise<void>;

export function DeleteTournament(arg1:number):Promise<void>;

export function DirectionStore():Promise<direction.Store>;

export function DiscardFromTrash(arg1:number):Promise<void>;

export function EmptyTrash(arg1:number):Promise<number>;

export function EnterForfeit(arg1:number,arg2:string,arg3:string,arg4:string):Promise<database.DirectionView>;

export function EnterParticipants(arg1:number,arg2:string):Promise<void>;

export function EnterResult(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number,arg6:string):Promise<database.DirectionView>;

export function EntrySuggestions():Promise<Array<database.EntrySuggestion>>;

export function ExplainDecision(arg1:number,arg2:string):Promise<engine.Explanation>;

export function ExportCollections(arg1:string,arg2:Array<number>,arg3:Record<string, string>,arg4:boolean,arg5:boolean,arg6:string,arg7:string):Promise<void>;

export function ExportDatabase(arg1:domain.ExportOptions):Promise<void>;

export function ExportDatabaseCtx(arg1:context.Context,arg2:domain.ExportOptions):Promise<void>;

export function ExportMatchMAT(arg1:number,arg2:string):Promise<void>;

export function ExportTournaments(arg1:string,arg2:Array<number>,arg3:Record<string, string>,arg4:boolean,arg5:boolean,arg6:string,arg7:string):Promise<void>;

export function ExportTranscriptionMAT(arg1:number,arg2:string):Promise<void>;

export function FinishImportBatch(arg1:number,arg2:domain.ImportReport):Promise<void>;

export function FinishedMatches(arg1:number,arg2:number):Promise<Array<database.TableCell>>;

export function FreeParticipants(arg1:number):Promise<Array<tournoi.Player>>;

export function GetAllAnkiDecks():Promise<Array<domain.AnkiDeck>>;

export function GetAllCollections():Promise<Array<database.Collection>>;

export function GetAllComments():Promise<Array<domain.CommentEntry>>;

export function GetAllMatches():Promise<Array<domain.Match>>;

export function GetAllPlayerNames():Promise<Array<database.PlayerFrequency>>;

export function GetAllTournaments():Promise<Array<domain.Tournament>>;

export function GetAnkiDeckPositions(arg1:number):Promise<Array<domain.Position>>;

export function GetAnkiDeckRetention(arg1:number):Promise<domain.AnkiRetention>;

export function GetAnkiDeckStats(arg1:number):Promise<domain.AnkiDeckStats>;

export function GetAnkiForecast(arg1:number,arg2:number):Promise<Array<domain.AnkiForecastDay>>;

export function GetAnkiReviewLog(arg1:number,arg2:number):Promise<Array<domain.AnkiReviewLog>>;

export function GetCollectionByID(arg1:number):Promise<database.Collection>;

export function GetCollectionPositions(arg1:number):Promise<Array<domain.Position>>;

export function GetCommentsByPosition(arg1:number):Promise<Array<domain.CommentEntry>>;

export function GetDatabaseStats():Promise<Record<string, any>>;

export function GetDatabaseVersion():Promise<string>;

export function GetDirection(arg1:number):Promise<database.DirectionView>;

export function GetGamesByMatch(arg1:number):Promise<Array<domain.Game>>;

export function GetIssuanceInfo():Promise<domain.IssuanceInfo>;

export function GetLastVisitedMatch():Promise<domain.Match>;

export function GetLibrarySettings():Promise<storage.LibrarySettings>;

export function GetLinkedAnkiCard(arg1:number,arg2:number):Promise<domain.AnkiReviewCard>;

export function GetMatchByID(arg1:number):Promise<domain.Match>;

export function GetMatchDetailStats(arg1:number):Promise<database.MatchDetailStats>;

export function GetMatchMovePositions(arg1:number):Promise<Array<domain.MatchMovePosition>>;

export function GetMatchTournament(arg1:number):Promise<domain.Tournament>;

export function GetMovesByGame(arg1:number):Promise<Array<domain.Move>>;

export function GetNextAnkiCard(arg1:number):Promise<domain.AnkiReviewCard>;

export function GetPlayerTable(arg1:database.StatsFilter):Promise<Array<database.PlayerRow>>;

export function GetPositionCollections(arg1:number):Promise<Array<database.Collection>>;

export function GetPositionIDsByMatch(arg1:number):Promise<Array<number>>;

export function GetPositionIDsByStatsSelection(arg1:database.StatsFilter,arg2:database.SelectionSpec):Promise<Array<number>>;

export function GetPositionIDsByTournament(arg1:number):Promise<Array<number>>;

export function GetPositionIndexMap():Promise<Record<number, number>>;

export function GetPositionProvenance(arg1:number):Promise<Array<domain.Match>>;

export function GetRandomAnkiCard(arg1:number,arg2:number):Promise<domain.AnkiReviewCard>;

export function GetStatsDateRange():Promise<database.StatsDateRange>;

export function GetTournamentMatches(arg1:number):Promise<Array<domain.Match>>;

export function GradeQuizChecker(arg1:number,arg2:domain.Board):Promise<engine.QuizVerdict>;

export function GradeQuizCheckerMove(arg1:number,arg2:string):Promise<engine.QuizVerdict>;

export function GradeQuizCube(arg1:number,arg2:string):Promise<engine.QuizVerdict>;

export function HasDirection(arg1:number):Promise<boolean>;

export function ImportBGFMatch(arg1:string):Promise<number>;

export function ImportBGFPosition(arg1:string):Promise<number>;

export function ImportBGFPositionFromText(arg1:string):Promise<number>;

export function ImportDatabase(arg1:string):Promise<Record<string, any>>;

export function ImportGnuBGMatch(arg1:string):Promise<number>;

export function ImportGnuBGMatchFromText(arg1:string):Promise<number>;

export function ImportReport(arg1:number):Promise<domain.ImportBatch>;

export function ImportStudyQueue(arg1:number,arg2:number):Promise<Array<domain.StudyQueueEntry>>;

export function ImportXGMatch(arg1:string):Promise<number>;

export function ImportXGPPosition(arg1:string):Promise<number>;

export function IsProtectedCopyPath(arg1:string):Promise<boolean>;

export function IsReadOnly():Promise<boolean>;

export function LastDecision(arg1:number):Promise<database.LastDecision>;

export function ListDirections():Promise<Array<database.DirectionSummary>>;

export function ListImportBatches(arg1:number,arg2:number):Promise<Array<domain.ImportBatch>>;

export function ListPositionIDs():Promise<Array<number>>;

export function ListTranscriptions():Promise<Array<database.TranscriptionSummary>>;

export function ListTrash(arg1:string,arg2:number,arg3:number):Promise<Array<domain.TrashEntry>>;

export function LoadAllPositions():Promise<Array<domain.Position>>;

export function LoadAnalysis(arg1:number):Promise<domain.PositionAnalysis>;

export function LoadCommandHistory():Promise<Array<string>>;

export function LoadComment(arg1:number):Promise<string>;

export function LoadEditPosition(arg1:string):Promise<string>;

export function LoadExcludePosition(arg1:string):Promise<string>;

export function LoadFilters():Promise<Array<Record<string, any>>>;

export function LoadMetadata():Promise<Record<string, string>>;

export function LoadPosition(arg1:number):Promise<domain.Position>;

export function LoadPositionIDsByFilters(arg1:domain.SearchFilters):Promise<Array<number>>;

export function LoadPositionsByFilters(arg1:domain.SearchFilters):Promise<Array<domain.Position>>;

export function LoadPositionsByFiltersCore(arg1:domain.SearchFilters,arg2:storage.ListOpts):Promise<Array<domain.Position>>;

export function LoadPositionsByFiltersCoreCtx(arg1:context.Context,arg2:domain.SearchFilters,arg3:storage.ListOpts):Promise<Array<domain.Position>>;

export function LoadPositionsByIDs(arg1:Array<number>):Promise<Array<domain.Position>>;

export function LoadSearchHistory():Promise<Array<database.SearchHistory>>;

export function LoadSessionState():Promise<database.SessionState>;

export function LoadTrainingNumberStats(arg1:string):Promise<Array<storage.TrainingNumberStat>>;

export function LoadTrainingSessions(arg1:string,arg2:number):Promise<Array<storage.TrainingSession>>;

export function MatchMAT(arg1:number):Promise<string>;

export function MergePlayers(arg1:Array<string>,arg2:string):Promise<void>;

export function MoveMatchToTable(arg1:number,arg2:string,arg3:number):Promise<database.DirectionView>;

export function MovePositionBetweenCollections(arg1:number,arg2:number,arg3:number):Promise<void>;

export function OpenDatabase(arg1:string):Promise<void>;

export function OpenProtectedCopyPath(arg1:string,arg2:string):Promise<string>;

export function OpenTranscription(arg1:number):Promise<database.TranscriptionState>;

export function ParsePositionText(arg1:string):Promise<parser.Result>;

export function Participants(arg1:number):Promise<Array<database.ParticipantRow>>;

export function PendingTranscriptionAnalysis():Promise<database.TranscriptionAnalysisResume>;

export function RankPositionIDsByFilters(arg1:domain.SearchFilters,arg2:number):Promise<Array<database.RankedID>>;

export function RankPositionsByFilters(arg1:domain.SearchFilters,arg2:number):Promise<Array<storage.SimilarPosition>>;

export function RecommendedTags():Promise<Array<string>>;

export function RefreshSearchStatistics():Promise<void>;

export function RemoveAnkiCard(arg1:number):Promise<void>;

export function RemoveMatchFromTournament(arg1:number):Promise<void>;

export function RemovePositionFromCollection(arg1:number,arg2:number):Promise<void>;

export function RemovePositionsFromCollection(arg1:number,arg2:Array<number>):Promise<void>;

export function ReorderCollectionPositions(arg1:number,arg2:Array<number>):Promise<void>;

export function ReorderCollections(arg1:Array<number>):Promise<void>;

export function ReorderTournamentMatches(arg1:number,arg2:Array<number>):Promise<void>;

export function RepairAnalyses():Promise<number>;

export function RepairGamePhases():Promise<number>;

export function ResetAnkiDeck(arg1:number):Promise<void>;

export function RestoreFromTrash(arg1:number):Promise<number>;

export function ReviewAnkiCard(arg1:number,arg2:number):Promise<domain.AnkiReviewCard>;

export function SaveAnalysis(arg1:number,arg2:domain.PositionAnalysis):Promise<void>;

export function SaveCommand(arg1:string):Promise<void>;

export function SaveComment(arg1:number,arg2:string):Promise<void>;

export function SaveEditPosition(arg1:string,arg2:string):Promise<void>;

export function SaveExcludePosition(arg1:string,arg2:string):Promise<void>;

export function SaveFilter(arg1:string,arg2:string):Promise<void>;

export function SaveIndividualPosition(arg1:domain.Position):Promise<database.IndividualSaveResult>;

export function SaveLastVisitedPosition(arg1:number,arg2:number):Promise<void>;

export function SaveLibrarySettings(arg1:storage.LibrarySettings):Promise<void>;

export function SaveMetadata(arg1:Record<string, string>):Promise<void>;

export function SavePosition(arg1:domain.Position):Promise<number>;

export function SaveSearchHistory(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveSessionState(arg1:database.SessionState):Promise<void>;

export function SaveTrainingSession(arg1:storage.TrainingSession):Promise<number>;

export function SaveTranscriptionAsMatch(arg1:number):Promise<database.TranscriptionSaveResult>;

export function SearchComments(arg1:string):Promise<Array<domain.CommentEntry>>;

export function SetAnkiCardSuspended(arg1:number,arg2:boolean):Promise<void>;

export function SetCollectionFilter(arg1:number,arg2:string):Promise<void>;

export function SetDirectionConfig(arg1:number,arg2:string):Promise<void>;

export function SetDirectionOutputDir(arg1:number,arg2:string):Promise<void>;

export function SetMatchTournamentByName(arg1:number,arg2:string):Promise<void>;

export function SetMigrationProgress(arg1:any):Promise<void>;

export function SetupDatabase(arg1:string):Promise<void>;

export function SimilarPositions(arg1:number,arg2:number):Promise<Array<storage.SimilarPosition>>;

export function StartMatchManually(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number):Promise<database.DirectionView>;

export function StudyImpact(arg1:number):Promise<Array<database.StudyImpactRow>>;

export function SuggestMatFilename(arg1:number):Promise<string>;

export function SuggestTranscriptionMatFilename(arg1:number):Promise<string>;

export function SwapMatchPlayers(arg1:number):Promise<void>;

export function SyncAnkiDeck(arg1:number):Promise<void>;

export function SyncAnkiDeckWithPositions(arg1:number,arg2:Array<number>):Promise<void>;

export function TableGrid(arg1:number):Promise<Array<database.TableCell>>;

export function Tags():Promise<Array<domain.TagCount>>;

export function TranscriptionMAT(arg1:number):Promise<string>;

export function TrashCollection(arg1:number):Promise<number>;

export function TrashCommentEntry(arg1:number):Promise<number>;

export function TrashPosition(arg1:number):Promise<number>;

export function UpdateAnkiDeck(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateAnkiDeckParams(arg1:number,arg2:number,arg3:number,arg4:boolean,arg5:any):Promise<void>;

export function UpdateCollection(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateCommentEntry(arg1:number,arg2:string):Promise<void>;

export function UpdateFilter(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateMatch(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateMatchComment(arg1:number,arg2:string):Promise<void>;

export function UpdateParticipant(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number):Promise<database.DirectionView>;

export function UpdatePosition(arg1:domain.Position):Promise<void>;

export function UpdateTournament(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateTournamentComment(arg1:number,arg2:string):Promise<void>;

export function Vacuum():Promise<database.VacuumResult>;

export function WithdrawParticipant(arg1:number,arg2:string,arg3:boolean):Promise<database.DirectionView>;
