// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbandonTranscription(arg1) {
  return window['go']['database']['Database']['AbandonTranscription'](arg1);
}

export function AddComment(arg1, arg2) {
  return window['go']['database']['Database']['AddComment'](arg1, arg2);
}

export function AddDirectionNote(arg1, arg2) {
  return window['go']['database']['Database']['AddDirectionNote'](arg1, arg2);
}

export function AddLessonStep(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['database']['Database']['AddLessonStep'](arg1, arg2, arg3, arg4, arg5);
}

export function AddMatchToTournament(arg1, arg2) {
  return window['go']['database']['Database']['AddMatchToTournament'](arg1, arg2);
}

export function AddPair(arg1, arg2, arg3) {
  return window['go']['database']['Database']['AddPair'](arg1, arg2, arg3);
}

export function AddParticipant(arg1, arg2, arg3, arg4) {
  return window['go']['database']['Database']['AddParticipant'](arg1, arg2, arg3, arg4);
}

export function AddParticipantAtSlot(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['database']['Database']['AddParticipantAtSlot'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddPositionToCollection(arg1, arg2) {
  return window['go']['database']['Database']['AddPositionToCollection'](arg1, arg2);
}

export function AddPositionsToCollection(arg1, arg2) {
  return window['go']['database']['Database']['AddPositionsToCollection'](arg1, arg2);
}

export function AnalysisMETStatus(arg1) {
  return window['go']['database']['Database']['AnalysisMETStatus'](arg1);
}

export function AnalyzeImportDatabase(arg1) {
  return window['go']['database']['Database']['AnalyzeImportDatabase'](arg1);
}

export function AnalyzeMatchWithGammonNet(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['database']['Database']['AnalyzeMatchWithGammonNet'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function AnalyzeMissingWithGammonNet(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['database']['Database']['AnalyzeMissingWithGammonNet'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function AnalyzeStaleGammonNet(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['database']['Database']['AnalyzeStaleGammonNet'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ApplyTranscriptionGesture(arg1, arg2) {
  return window['go']['database']['Database']['ApplyTranscriptionGesture'](arg1, arg2);
}

export function AttachMatchToSlot(arg1, arg2, arg3) {
  return window['go']['database']['Database']['AttachMatchToSlot'](arg1, arg2, arg3);
}

export function AttachToRencontre(arg1, arg2) {
  return window['go']['database']['Database']['AttachToRencontre'](arg1, arg2);
}

export function BeginImportBatch(arg1, arg2) {
  return window['go']['database']['Database']['BeginImportBatch'](arg1, arg2);
}

export function Brackets(arg1) {
  return window['go']['database']['Database']['Brackets'](arg1);
}

export function BuryAnkiCard(arg1) {
  return window['go']['database']['Database']['BuryAnkiCard'](arg1);
}

export function CancelImport() {
  return window['go']['database']['Database']['CancelImport']();
}

export function CancelMatch(arg1, arg2) {
  return window['go']['database']['Database']['CancelMatch'](arg1, arg2);
}

export function CancelSearch() {
  return window['go']['database']['Database']['CancelSearch']();
}

export function CheckConstraints() {
  return window['go']['database']['Database']['CheckConstraints']();
}

export function CheckCounters() {
  return window['go']['database']['Database']['CheckCounters']();
}

export function CheckDatabaseVersion() {
  return window['go']['database']['Database']['CheckDatabaseVersion']();
}

export function CheckMatchExists(arg1) {
  return window['go']['database']['Database']['CheckMatchExists'](arg1);
}

export function CheckSchema() {
  return window['go']['database']['Database']['CheckSchema']();
}

export function CheckVersion(arg1) {
  return window['go']['database']['Database']['CheckVersion'](arg1);
}

export function Checkpoint() {
  return window['go']['database']['Database']['Checkpoint']();
}

export function ClearCommandHistory() {
  return window['go']['database']['Database']['ClearCommandHistory']();
}

export function ClearSessionState() {
  return window['go']['database']['Database']['ClearSessionState']();
}

export function Clock(arg1) {
  return window['go']['database']['Database']['Clock'](arg1);
}

export function Close() {
  return window['go']['database']['Database']['Close']();
}

export function CloseDirection(arg1) {
  return window['go']['database']['Database']['CloseDirection'](arg1);
}

export function CloseTranscription(arg1) {
  return window['go']['database']['Database']['CloseTranscription'](arg1);
}

export function CollectionCoverage(arg1) {
  return window['go']['database']['Database']['CollectionCoverage'](arg1);
}

export function CommitImportDatabase(arg1) {
  return window['go']['database']['Database']['CommitImportDatabase'](arg1);
}

export function CompareWithGammonNet(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['database']['Database']['CompareWithGammonNet'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ComputeEPCFromPosition(arg1) {
  return window['go']['database']['Database']['ComputeEPCFromPosition'](arg1);
}

export function ComputeRecurringErrors(arg1) {
  return window['go']['database']['Database']['ComputeRecurringErrors'](arg1);
}

export function ComputeRecurringErrorsCtx(arg1, arg2) {
  return window['go']['database']['Database']['ComputeRecurringErrorsCtx'](arg1, arg2);
}

export function ComputeStats(arg1) {
  return window['go']['database']['Database']['ComputeStats'](arg1);
}

export function ComputeStatsCtx(arg1, arg2) {
  return window['go']['database']['Database']['ComputeStatsCtx'](arg1, arg2);
}

export function ComputeStudyPlan(arg1) {
  return window['go']['database']['Database']['ComputeStudyPlan'](arg1);
}

export function ComputeStudyPlanCtx(arg1, arg2) {
  return window['go']['database']['Database']['ComputeStudyPlanCtx'](arg1, arg2);
}

export function ComputeTrainingStats(arg1, arg2) {
  return window['go']['database']['Database']['ComputeTrainingStats'](arg1, arg2);
}

export function ComputeTrainingStatsCtx(arg1, arg2, arg3) {
  return window['go']['database']['Database']['ComputeTrainingStatsCtx'](arg1, arg2, arg3);
}

export function ConfirmAllProposals(arg1) {
  return window['go']['database']['Database']['ConfirmAllProposals'](arg1);
}

export function ConfirmProposal(arg1, arg2) {
  return window['go']['database']['Database']['ConfirmProposal'](arg1, arg2);
}

export function ContributeDuel(arg1, arg2, arg3, arg4) {
  return window['go']['database']['Database']['ContributeDuel'](arg1, arg2, arg3, arg4);
}

export function CopyPositionToCollection(arg1, arg2) {
  return window['go']['database']['Database']['CopyPositionToCollection'](arg1, arg2);
}

export function CorrectResult(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['database']['Database']['CorrectResult'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CountAnkiDeckPositions(arg1) {
  return window['go']['database']['Database']['CountAnkiDeckPositions'](arg1);
}

export function CountCollectionPositions(arg1) {
  return window['go']['database']['Database']['CountCollectionPositions'](arg1);
}

export function CountMatchPositionsToAnalyze(arg1) {
  return window['go']['database']['Database']['CountMatchPositionsToAnalyze'](arg1);
}

export function CountMatches(arg1) {
  return window['go']['database']['Database']['CountMatches'](arg1);
}

export function CountOrphans() {
  return window['go']['database']['Database']['CountOrphans']();
}

export function CountPositions() {
  return window['go']['database']['Database']['CountPositions']();
}

export function CountPositionsByFilters(arg1) {
  return window['go']['database']['Database']['CountPositionsByFilters'](arg1);
}

export function CountPositionsWithForeignAnalysis() {
  return window['go']['database']['Database']['CountPositionsWithForeignAnalysis']();
}

export function CountPositionsWithStaleGammonNet(arg1) {
  return window['go']['database']['Database']['CountPositionsWithStaleGammonNet'](arg1);
}

export function CountPositionsWithoutAnalysis() {
  return window['go']['database']['Database']['CountPositionsWithoutAnalysis']();
}

export function CountTrash() {
  return window['go']['database']['Database']['CountTrash']();
}

export function CreateAnkiDeck(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['database']['Database']['CreateAnkiDeck'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateCollection(arg1, arg2) {
  return window['go']['database']['Database']['CreateCollection'](arg1, arg2);
}

export function CreateDirection(arg1, arg2, arg3) {
  return window['go']['database']['Database']['CreateDirection'](arg1, arg2, arg3);
}

export function CreateDuel(arg1) {
  return window['go']['database']['Database']['CreateDuel'](arg1);
}

export function CreateLesson(arg1, arg2) {
  return window['go']['database']['Database']['CreateLesson'](arg1, arg2);
}

export function CreateRencontre(arg1, arg2, arg3, arg4) {
  return window['go']['database']['Database']['CreateRencontre'](arg1, arg2, arg3, arg4);
}

export function CreateStudyDeck(arg1, arg2) {
  return window['go']['database']['Database']['CreateStudyDeck'](arg1, arg2);
}

export function CreateTournament(arg1, arg2, arg3) {
  return window['go']['database']['Database']['CreateTournament'](arg1, arg2, arg3);
}

export function CreateTranscription(arg1) {
  return window['go']['database']['Database']['CreateTranscription'](arg1);
}

export function DeleteAnalysis(arg1) {
  return window['go']['database']['Database']['DeleteAnalysis'](arg1);
}

export function DeleteAnkiDeck(arg1) {
  return window['go']['database']['Database']['DeleteAnkiDeck'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['database']['Database']['DeleteCollection'](arg1);
}

export function DeleteComment(arg1) {
  return window['go']['database']['Database']['DeleteComment'](arg1);
}

export function DeleteCommentEntry(arg1) {
  return window['go']['database']['Database']['DeleteCommentEntry'](arg1);
}

export function DeleteDirection(arg1) {
  return window['go']['database']['Database']['DeleteDirection'](arg1);
}

export function DeleteFilter(arg1) {
  return window['go']['database']['Database']['DeleteFilter'](arg1);
}

export function DeleteLesson(arg1) {
  return window['go']['database']['Database']['DeleteLesson'](arg1);
}

export function DeleteMatch(arg1) {
  return window['go']['database']['Database']['DeleteMatch'](arg1);
}

export function DeletePosition(arg1) {
  return window['go']['database']['Database']['DeletePosition'](arg1);
}

export function DeleteProtectedCopyPath(arg1) {
  return window['go']['database']['Database']['DeleteProtectedCopyPath'](arg1);
}

export function DeleteSearchHistoryEntry(arg1) {
  return window['go']['database']['Database']['DeleteSearchHistoryEntry'](arg1);
}

export function DeleteTournament(arg1) {
  return window['go']['database']['Database']['DeleteTournament'](arg1);
}

export function DetachFromRencontre(arg1) {
  return window['go']['database']['Database']['DetachFromRencontre'](arg1);
}

export function DetachMatchFromSlot(arg1, arg2) {
  return window['go']['database']['Database']['DetachMatchFromSlot'](arg1, arg2);
}

export function DirectionFreeSlots(arg1) {
  return window['go']['database']['Database']['DirectionFreeSlots'](arg1);
}

export function DirectionJournalJSON(arg1) {
  return window['go']['database']['Database']['DirectionJournalJSON'](arg1);
}

export function DirectionPageHTML(arg1) {
  return window['go']['database']['Database']['DirectionPageHTML'](arg1);
}

export function DirectionPairingSheetHTML(arg1, arg2) {
  return window['go']['database']['Database']['DirectionPairingSheetHTML'](arg1, arg2);
}

export function DirectionRounds(arg1) {
  return window['go']['database']['Database']['DirectionRounds'](arg1);
}

export function DirectionSearchIndex(arg1) {
  return window['go']['database']['Database']['DirectionSearchIndex'](arg1);
}

export function DirectionStore() {
  return window['go']['database']['Database']['DirectionStore']();
}

export function DirectionUpcomingSheetHTML(arg1, arg2) {
  return window['go']['database']['Database']['DirectionUpcomingSheetHTML'](arg1, arg2);
}

export function Directory() {
  return window['go']['database']['Database']['Directory']();
}

export function DirectoryCSV() {
  return window['go']['database']['Database']['DirectoryCSV']();
}

export function DirectoryEntrants(arg1) {
  return window['go']['database']['Database']['DirectoryEntrants'](arg1);
}

export function DirectorySources() {
  return window['go']['database']['Database']['DirectorySources']();
}

export function DiscardFromTrash(arg1) {
  return window['go']['database']['Database']['DiscardFromTrash'](arg1);
}

export function DuelOffer() {
  return window['go']['database']['Database']['DuelOffer']();
}

export function EditMatchTranscription(arg1) {
  return window['go']['database']['Database']['EditMatchTranscription'](arg1);
}

export function EmptyTrash(arg1) {
  return window['go']['database']['Database']['EmptyTrash'](arg1);
}

export function EnterForfeit(arg1, arg2, arg3, arg4) {
  return window['go']['database']['Database']['EnterForfeit'](arg1, arg2, arg3, arg4);
}

export function EnterParticipants(arg1, arg2) {
  return window['go']['database']['Database']['EnterParticipants'](arg1, arg2);
}

export function EnterResult(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['database']['Database']['EnterResult'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function EntrySuggestions() {
  return window['go']['database']['Database']['EntrySuggestions']();
}

export function ExplainDecision(arg1, arg2) {
  return window['go']['database']['Database']['ExplainDecision'](arg1, arg2);
}

export function ExportCollections(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['database']['Database']['ExportCollections'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ExportDatabase(arg1) {
  return window['go']['database']['Database']['ExportDatabase'](arg1);
}

export function ExportDatabaseCtx(arg1, arg2) {
  return window['go']['database']['Database']['ExportDatabaseCtx'](arg1, arg2);
}

export function ExportMatchMAT(arg1, arg2) {
  return window['go']['database']['Database']['ExportMatchMAT'](arg1, arg2);
}

export function ExportTournaments(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['database']['Database']['ExportTournaments'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ExportTranscriptionMAT(arg1, arg2) {
  return window['go']['database']['Database']['ExportTranscriptionMAT'](arg1, arg2);
}

export function FindDuplicateMatches() {
  return window['go']['database']['Database']['FindDuplicateMatches']();
}

export function FinishImportBatch(arg1, arg2) {
  return window['go']['database']['Database']['FinishImportBatch'](arg1, arg2);
}

export function FinishTranscription(arg1) {
  return window['go']['database']['Database']['FinishTranscription'](arg1);
}

export function FinishedMatches(arg1, arg2) {
  return window['go']['database']['Database']['FinishedMatches'](arg1, arg2);
}

export function FlagDuel(arg1) {
  return window['go']['database']['Database']['FlagDuel'](arg1);
}

export function ForfeitDuel(arg1, arg2, arg3) {
  return window['go']['database']['Database']['ForfeitDuel'](arg1, arg2, arg3);
}

export function FreeParticipants(arg1) {
  return window['go']['database']['Database']['FreeParticipants'](arg1);
}

export function FreezeCollection(arg1) {
  return window['go']['database']['Database']['FreezeCollection'](arg1);
}

export function GetAllAnkiDecks() {
  return window['go']['database']['Database']['GetAllAnkiDecks']();
}

export function GetAllCollections() {
  return window['go']['database']['Database']['GetAllCollections']();
}

export function GetAllComments() {
  return window['go']['database']['Database']['GetAllComments']();
}

export function GetAllMatches() {
  return window['go']['database']['Database']['GetAllMatches']();
}

export function GetAllPlayerNames() {
  return window['go']['database']['Database']['GetAllPlayerNames']();
}

export function GetAllTournaments() {
  return window['go']['database']['Database']['GetAllTournaments']();
}

export function GetAnkiDeckPositions(arg1) {
  return window['go']['database']['Database']['GetAnkiDeckPositions'](arg1);
}

export function GetAnkiDeckRetention(arg1) {
  return window['go']['database']['Database']['GetAnkiDeckRetention'](arg1);
}

export function GetAnkiDeckStats(arg1) {
  return window['go']['database']['Database']['GetAnkiDeckStats'](arg1);
}

export function GetAnkiForecast(arg1, arg2) {
  return window['go']['database']['Database']['GetAnkiForecast'](arg1, arg2);
}

export function GetAnkiReviewLog(arg1, arg2) {
  return window['go']['database']['Database']['GetAnkiReviewLog'](arg1, arg2);
}

export function GetCollectionByID(arg1) {
  return window['go']['database']['Database']['GetCollectionByID'](arg1);
}

export function GetCollectionPositions(arg1) {
  return window['go']['database']['Database']['GetCollectionPositions'](arg1);
}

export function GetCommentsByPosition(arg1) {
  return window['go']['database']['Database']['GetCommentsByPosition'](arg1);
}

export function GetDatabaseStats() {
  return window['go']['database']['Database']['GetDatabaseStats']();
}

export function GetDatabaseStatsEstimate() {
  return window['go']['database']['Database']['GetDatabaseStatsEstimate']();
}

export function GetDatabaseVersion() {
  return window['go']['database']['Database']['GetDatabaseVersion']();
}

export function GetDirection(arg1) {
  return window['go']['database']['Database']['GetDirection'](arg1);
}

export function GetGamesByMatch(arg1) {
  return window['go']['database']['Database']['GetGamesByMatch'](arg1);
}

export function GetIssuanceInfo() {
  return window['go']['database']['Database']['GetIssuanceInfo']();
}

export function GetLastVisitedMatch() {
  return window['go']['database']['Database']['GetLastVisitedMatch']();
}

export function GetLesson(arg1) {
  return window['go']['database']['Database']['GetLesson'](arg1);
}

export function GetLibrarySettings() {
  return window['go']['database']['Database']['GetLibrarySettings']();
}

export function GetLinkedAnkiCard(arg1, arg2) {
  return window['go']['database']['Database']['GetLinkedAnkiCard'](arg1, arg2);
}

export function GetMatchByID(arg1) {
  return window['go']['database']['Database']['GetMatchByID'](arg1);
}

export function GetMatchDecisionLosses(arg1) {
  return window['go']['database']['Database']['GetMatchDecisionLosses'](arg1);
}

export function GetMatchReview(arg1) {
  return window['go']['database']['Database']['GetMatchReview'](arg1);
}

export function GetMatchDetailStats(arg1) {
  return window['go']['database']['Database']['GetMatchDetailStats'](arg1);
}

export function GetMatchMoveGrades(arg1) {
  return window['go']['database']['Database']['GetMatchMoveGrades'](arg1);
}

export function GetMatchMovePositions(arg1) {
  return window['go']['database']['Database']['GetMatchMovePositions'](arg1);
}

export function GetMatchOrigin(arg1) {
  return window['go']['database']['Database']['GetMatchOrigin'](arg1);
}

export function GetMatchTimeSummary(arg1) {
  return window['go']['database']['Database']['GetMatchTimeSummary'](arg1);
}

export function GetMatchTournament(arg1) {
  return window['go']['database']['Database']['GetMatchTournament'](arg1);
}

export function GetMovesByGame(arg1) {
  return window['go']['database']['Database']['GetMovesByGame'](arg1);
}

export function GetNextAnkiCard(arg1) {
  return window['go']['database']['Database']['GetNextAnkiCard'](arg1);
}

export function GetPlayerTable(arg1) {
  return window['go']['database']['Database']['GetPlayerTable'](arg1);
}

export function GetPositionCollections(arg1) {
  return window['go']['database']['Database']['GetPositionCollections'](arg1);
}

export function GetPositionIDsByMatch(arg1) {
  return window['go']['database']['Database']['GetPositionIDsByMatch'](arg1);
}

export function GetPositionIDsByStatsSelection(arg1, arg2) {
  return window['go']['database']['Database']['GetPositionIDsByStatsSelection'](arg1, arg2);
}

export function GetPositionIDsByTournament(arg1) {
  return window['go']['database']['Database']['GetPositionIDsByTournament'](arg1);
}

export function GetPositionIndexMap() {
  return window['go']['database']['Database']['GetPositionIndexMap']();
}

export function GetPositionProvenance(arg1) {
  return window['go']['database']['Database']['GetPositionProvenance'](arg1);
}

export function GetRandomAnkiCard(arg1, arg2) {
  return window['go']['database']['Database']['GetRandomAnkiCard'](arg1, arg2);
}

export function GetRencontre(arg1) {
  return window['go']['database']['Database']['GetRencontre'](arg1);
}

export function GetStatsDateRange() {
  return window['go']['database']['Database']['GetStatsDateRange']();
}

export function GetTimeErrors() {
  return window['go']['database']['Database']['GetTimeErrors']();
}

export function GetTournamentMatches(arg1) {
  return window['go']['database']['Database']['GetTournamentMatches'](arg1);
}

export function GradeQuizChecker(arg1, arg2) {
  return window['go']['database']['Database']['GradeQuizChecker'](arg1, arg2);
}

export function GradeQuizCheckerMove(arg1, arg2) {
  return window['go']['database']['Database']['GradeQuizCheckerMove'](arg1, arg2);
}

export function GradeQuizCube(arg1, arg2) {
  return window['go']['database']['Database']['GradeQuizCube'](arg1, arg2);
}

export function HasDirection(arg1) {
  return window['go']['database']['Database']['HasDirection'](arg1);
}

export function HeadToHead(arg1, arg2, arg3) {
  return window['go']['database']['Database']['HeadToHead'](arg1, arg2, arg3);
}

export function HeadToHeadCtx(arg1, arg2, arg3, arg4) {
  return window['go']['database']['Database']['HeadToHeadCtx'](arg1, arg2, arg3, arg4);
}

export function History(arg1, arg2, arg3) {
  return window['go']['database']['Database']['History'](arg1, arg2, arg3);
}

export function ImportBGFMatch(arg1) {
  return window['go']['database']['Database']['ImportBGFMatch'](arg1);
}

export function ImportBGFPosition(arg1) {
  return window['go']['database']['Database']['ImportBGFPosition'](arg1);
}

export function ImportBGFPositionFromText(arg1) {
  return window['go']['database']['Database']['ImportBGFPositionFromText'](arg1);
}

export function ImportDatabase(arg1) {
  return window['go']['database']['Database']['ImportDatabase'](arg1);
}

export function ImportFiles(arg1, arg2) {
  return window['go']['database']['Database']['ImportFiles'](arg1, arg2);
}

export function ImportGnuBGMatch(arg1) {
  return window['go']['database']['Database']['ImportGnuBGMatch'](arg1);
}

export function ImportGnuBGMatchFromText(arg1) {
  return window['go']['database']['Database']['ImportGnuBGMatchFromText'](arg1);
}

export function ImportJournal(arg1) {
  return window['go']['database']['Database']['ImportJournal'](arg1);
}

export function ImportMET(arg1) {
  return window['go']['database']['Database']['ImportMET'](arg1);
}

export function ImportOGXMMatch(arg1) {
  return window['go']['database']['Database']['ImportOGXMMatch'](arg1);
}

export function ImportReport(arg1) {
  return window['go']['database']['Database']['ImportReport'](arg1);
}

export function ImportStudyQueue(arg1, arg2) {
  return window['go']['database']['Database']['ImportStudyQueue'](arg1, arg2);
}

export function ImportXGMatch(arg1) {
  return window['go']['database']['Database']['ImportXGMatch'](arg1);
}

export function ImportXGPPosition(arg1) {
  return window['go']['database']['Database']['ImportXGPPosition'](arg1);
}

export function IndexOfAnkiDeckPosition(arg1, arg2) {
  return window['go']['database']['Database']['IndexOfAnkiDeckPosition'](arg1, arg2);
}

export function IndexOfCollectionPosition(arg1, arg2) {
  return window['go']['database']['Database']['IndexOfCollectionPosition'](arg1, arg2);
}

export function IndexOfPosition(arg1) {
  return window['go']['database']['Database']['IndexOfPosition'](arg1);
}

export function IndexOfPositionByFilters(arg1, arg2) {
  return window['go']['database']['Database']['IndexOfPositionByFilters'](arg1, arg2);
}

export function IsPositionOnPile(arg1) {
  return window['go']['database']['Database']['IsPositionOnPile'](arg1);
}

export function IsProtectedCopyPath(arg1) {
  return window['go']['database']['Database']['IsProtectedCopyPath'](arg1);
}

export function IsReadOnly() {
  return window['go']['database']['Database']['IsReadOnly']();
}

export function LastDecision(arg1) {
  return window['go']['database']['Database']['LastDecision'](arg1);
}

export function LessonDoneSteps(arg1) {
  return window['go']['database']['Database']['LessonDoneSteps'](arg1);
}

export function ListAliases(arg1) {
  return window['go']['database']['Database']['ListAliases'](arg1);
}

export function ListAnkiDeckPositionIDs(arg1, arg2, arg3) {
  return window['go']['database']['Database']['ListAnkiDeckPositionIDs'](arg1, arg2, arg3);
}

export function ListCollectionPositionIDs(arg1, arg2, arg3) {
  return window['go']['database']['Database']['ListCollectionPositionIDs'](arg1, arg2, arg3);
}

export function ListDirections() {
  return window['go']['database']['Database']['ListDirections']();
}

export function ListDuels() {
  return window['go']['database']['Database']['ListDuels']();
}

export function ListImportBatches(arg1, arg2) {
  return window['go']['database']['Database']['ListImportBatches'](arg1, arg2);
}

export function ListLessons() {
  return window['go']['database']['Database']['ListLessons']();
}

export function ListMETs() {
  return window['go']['database']['Database']['ListMETs']();
}

export function ListMatches(arg1) {
  return window['go']['database']['Database']['ListMatches'](arg1);
}

export function ListPositionIDs(arg1, arg2) {
  return window['go']['database']['Database']['ListPositionIDs'](arg1, arg2);
}

export function ListRencontres() {
  return window['go']['database']['Database']['ListRencontres']();
}

export function ListTranscriptions() {
  return window['go']['database']['Database']['ListTranscriptions']();
}

export function ListTrash(arg1, arg2, arg3) {
  return window['go']['database']['Database']['ListTrash'](arg1, arg2, arg3);
}

export function LoadAllPositions() {
  return window['go']['database']['Database']['LoadAllPositions']();
}

export function LoadAnalysis(arg1) {
  return window['go']['database']['Database']['LoadAnalysis'](arg1);
}

export function LoadCommandHistory() {
  return window['go']['database']['Database']['LoadCommandHistory']();
}

export function LoadComment(arg1) {
  return window['go']['database']['Database']['LoadComment'](arg1);
}

export function LoadEditPosition(arg1) {
  return window['go']['database']['Database']['LoadEditPosition'](arg1);
}

export function LoadExcludePosition(arg1) {
  return window['go']['database']['Database']['LoadExcludePosition'](arg1);
}

export function LoadFilters() {
  return window['go']['database']['Database']['LoadFilters']();
}

export function LoadMetadata() {
  return window['go']['database']['Database']['LoadMetadata']();
}

export function LoadPosition(arg1) {
  return window['go']['database']['Database']['LoadPosition'](arg1);
}

export function LoadPositionIDsByFilters(arg1) {
  return window['go']['database']['Database']['LoadPositionIDsByFilters'](arg1);
}

export function LoadPositionView(arg1) {
  return window['go']['database']['Database']['LoadPositionView'](arg1);
}

export function LoadPositionsByFilters(arg1) {
  return window['go']['database']['Database']['LoadPositionsByFilters'](arg1);
}

export function LoadPositionsByFiltersCore(arg1, arg2) {
  return window['go']['database']['Database']['LoadPositionsByFiltersCore'](arg1, arg2);
}

export function LoadPositionsByFiltersCoreCtx(arg1, arg2, arg3) {
  return window['go']['database']['Database']['LoadPositionsByFiltersCoreCtx'](arg1, arg2, arg3);
}

export function LoadPositionsByIDs(arg1) {
  return window['go']['database']['Database']['LoadPositionsByIDs'](arg1);
}

export function LoadRollouts(arg1) {
  return window['go']['database']['Database']['LoadRollouts'](arg1);
}

export function LoadSearchHistory() {
  return window['go']['database']['Database']['LoadSearchHistory']();
}

export function LoadSessionState() {
  return window['go']['database']['Database']['LoadSessionState']();
}

export function LoadTrainingMissed(arg1) {
  return window['go']['database']['Database']['LoadTrainingMissed'](arg1);
}

export function LoadTrainingNumberStats(arg1) {
  return window['go']['database']['Database']['LoadTrainingNumberStats'](arg1);
}

export function LoadTrainingSessions(arg1, arg2) {
  return window['go']['database']['Database']['LoadTrainingSessions'](arg1, arg2);
}

export function MakeParticipantAbsent(arg1, arg2, arg3, arg4) {
  return window['go']['database']['Database']['MakeParticipantAbsent'](arg1, arg2, arg3, arg4);
}

export function MakeParticipantAvailable(arg1, arg2) {
  return window['go']['database']['Database']['MakeParticipantAvailable'](arg1, arg2);
}

export function MatchMAT(arg1) {
  return window['go']['database']['Database']['MatchMAT'](arg1);
}

export function MatchTranscriptionLosses(arg1) {
  return window['go']['database']['Database']['MatchTranscriptionLosses'](arg1);
}

export function MaterializeTranscription(arg1, arg2) {
  return window['go']['database']['Database']['MaterializeTranscription'](arg1, arg2);
}

export function MergePlayers(arg1, arg2) {
  return window['go']['database']['Database']['MergePlayers'](arg1, arg2);
}

export function MoveMatchToTable(arg1, arg2, arg3) {
  return window['go']['database']['Database']['MoveMatchToTable'](arg1, arg2, arg3);
}

export function MovePositionBetweenCollections(arg1, arg2, arg3) {
  return window['go']['database']['Database']['MovePositionBetweenCollections'](arg1, arg2, arg3);
}

export function OpenDatabase(arg1) {
  return window['go']['database']['Database']['OpenDatabase'](arg1);
}

export function OpenDuel(arg1) {
  return window['go']['database']['Database']['OpenDuel'](arg1);
}

export function OpenProtectedCopyPath(arg1, arg2) {
  return window['go']['database']['Database']['OpenProtectedCopyPath'](arg1, arg2);
}

export function OpenTranscription(arg1) {
  return window['go']['database']['Database']['OpenTranscription'](arg1);
}

export function PRByWindow(arg1, arg2) {
  return window['go']['database']['Database']['PRByWindow'](arg1, arg2);
}

export function PRByWindowCtx(arg1, arg2, arg3) {
  return window['go']['database']['Database']['PRByWindowCtx'](arg1, arg2, arg3);
}

export function Pairs(arg1) {
  return window['go']['database']['Database']['Pairs'](arg1);
}

export function ParseDirectoryCSV(arg1, arg2) {
  return window['go']['database']['Database']['ParseDirectoryCSV'](arg1, arg2);
}

export function ParsePositionText(arg1) {
  return window['go']['database']['Database']['ParsePositionText'](arg1);
}

export function Participants(arg1) {
  return window['go']['database']['Database']['Participants'](arg1);
}

export function PendingImportFiles(arg1) {
  return window['go']['database']['Database']['PendingImportFiles'](arg1);
}

export function PendingTranscriptionAnalysis() {
  return window['go']['database']['Database']['PendingTranscriptionAnalysis']();
}

export function PileCollectionID() {
  return window['go']['database']['Database']['PileCollectionID']();
}

export function PlanRollout(arg1, arg2, arg3) {
  return window['go']['database']['Database']['PlanRollout'](arg1, arg2, arg3);
}

export function PlanRolloutIDs(arg1, arg2, arg3) {
  return window['go']['database']['Database']['PlanRolloutIDs'](arg1, arg2, arg3);
}

export function PlayDuel(arg1, arg2, arg3) {
  return window['go']['database']['Database']['PlayDuel'](arg1, arg2, arg3);
}

export function PlayerContrast(arg1, arg2, arg3) {
  return window['go']['database']['Database']['PlayerContrast'](arg1, arg2, arg3);
}

export function PlayerContrastCtx(arg1, arg2, arg3, arg4) {
  return window['go']['database']['Database']['PlayerContrastCtx'](arg1, arg2, arg3, arg4);
}

export function PlayerRanking(arg1, arg2) {
  return window['go']['database']['Database']['PlayerRanking'](arg1, arg2);
}

export function PlayerRankingCtx(arg1, arg2, arg3) {
  return window['go']['database']['Database']['PlayerRankingCtx'](arg1, arg2, arg3);
}

export function PositionsToRollout(arg1, arg2, arg3) {
  return window['go']['database']['Database']['PositionsToRollout'](arg1, arg2, arg3);
}

export function PositionsToRolloutIDs(arg1, arg2, arg3) {
  return window['go']['database']['Database']['PositionsToRolloutIDs'](arg1, arg2, arg3);
}

export function PreviewAttachToRencontre(arg1, arg2) {
  return window['go']['database']['Database']['PreviewAttachToRencontre'](arg1, arg2);
}

export function PreviewDirectionConfig(arg1, arg2) {
  return window['go']['database']['Database']['PreviewDirectionConfig'](arg1, arg2);
}

export function RankPositionIDsByFilters(arg1, arg2) {
  return window['go']['database']['Database']['RankPositionIDsByFilters'](arg1, arg2);
}

export function RankPositionsByFilters(arg1, arg2) {
  return window['go']['database']['Database']['RankPositionsByFilters'](arg1, arg2);
}

export function RebuildMatchStats() {
  return window['go']['database']['Database']['RebuildMatchStats']();
}

export function RecommendedTags() {
  return window['go']['database']['Database']['RecommendedTags']();
}

export function ReencodeAnalyses() {
  return window['go']['database']['Database']['ReencodeAnalyses']();
}

export function RefreshSearchStatistics() {
  return window['go']['database']['Database']['RefreshSearchStatistics']();
}

export function RefuseReadOnly() {
  return window['go']['database']['Database']['RefuseReadOnly']();
}

export function ReinstateParticipant(arg1, arg2) {
  return window['go']['database']['Database']['ReinstateParticipant'](arg1, arg2);
}

export function RemoveAlias(arg1, arg2) {
  return window['go']['database']['Database']['RemoveAlias'](arg1, arg2);
}

export function RemoveAnkiCard(arg1) {
  return window['go']['database']['Database']['RemoveAnkiCard'](arg1);
}

export function RemoveLessonStep(arg1) {
  return window['go']['database']['Database']['RemoveLessonStep'](arg1);
}

export function RemoveMatchFromTournament(arg1) {
  return window['go']['database']['Database']['RemoveMatchFromTournament'](arg1);
}

export function RemovePositionFromCollection(arg1, arg2) {
  return window['go']['database']['Database']['RemovePositionFromCollection'](arg1, arg2);
}

export function RemovePositionsFromCollection(arg1, arg2) {
  return window['go']['database']['Database']['RemovePositionsFromCollection'](arg1, arg2);
}

export function RencontreOf(arg1) {
  return window['go']['database']['Database']['RencontreOf'](arg1);
}

export function RencontrePageHTML(arg1) {
  return window['go']['database']['Database']['RencontrePageHTML'](arg1);
}

export function RencontreSearchIndex(arg1) {
  return window['go']['database']['Database']['RencontreSearchIndex'](arg1);
}

export function RencontreTableGrid(arg1) {
  return window['go']['database']['Database']['RencontreTableGrid'](arg1);
}

export function ReopenDirection(arg1) {
  return window['go']['database']['Database']['ReopenDirection'](arg1);
}

export function ReorderCollectionPositions(arg1, arg2) {
  return window['go']['database']['Database']['ReorderCollectionPositions'](arg1, arg2);
}

export function ReorderCollections(arg1) {
  return window['go']['database']['Database']['ReorderCollections'](arg1);
}

export function ReorderLessonSteps(arg1, arg2) {
  return window['go']['database']['Database']['ReorderLessonSteps'](arg1, arg2);
}

export function ReorderTournamentMatches(arg1, arg2) {
  return window['go']['database']['Database']['ReorderTournamentMatches'](arg1, arg2);
}

export function RepairAnalyses() {
  return window['go']['database']['Database']['RepairAnalyses']();
}

export function RepairCrawfordSentinel() {
  return window['go']['database']['Database']['RepairCrawfordSentinel']();
}

export function RepairGamePhases() {
  return window['go']['database']['Database']['RepairGamePhases']();
}

export function ResetAnkiDeck(arg1) {
  return window['go']['database']['Database']['ResetAnkiDeck'](arg1);
}

export function RestoreFromTrash(arg1) {
  return window['go']['database']['Database']['RestoreFromTrash'](arg1);
}

export function ResumeImportBatch(arg1) {
  return window['go']['database']['Database']['ResumeImportBatch'](arg1);
}

export function ReviewAnkiCard(arg1, arg2) {
  return window['go']['database']['Database']['ReviewAnkiCard'](arg1, arg2);
}

export function RolloutFiltered(arg1, arg2, arg3, arg4) {
  return window['go']['database']['Database']['RolloutFiltered'](arg1, arg2, arg3, arg4);
}

export function RolloutPosition(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['database']['Database']['RolloutPosition'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RolloutPositions(arg1, arg2, arg3, arg4) {
  return window['go']['database']['Database']['RolloutPositions'](arg1, arg2, arg3, arg4);
}

export function RunRolloutPlan(arg1, arg2, arg3, arg4) {
  return window['go']['database']['Database']['RunRolloutPlan'](arg1, arg2, arg3, arg4);
}

export function SaveAnalysis(arg1, arg2) {
  return window['go']['database']['Database']['SaveAnalysis'](arg1, arg2);
}

export function SaveCommand(arg1) {
  return window['go']['database']['Database']['SaveCommand'](arg1);
}

export function SaveComment(arg1, arg2) {
  return window['go']['database']['Database']['SaveComment'](arg1, arg2);
}

export function SaveEditPosition(arg1, arg2) {
  return window['go']['database']['Database']['SaveEditPosition'](arg1, arg2);
}

export function SaveExcludePosition(arg1, arg2) {
  return window['go']['database']['Database']['SaveExcludePosition'](arg1, arg2);
}

export function SaveFilter(arg1, arg2) {
  return window['go']['database']['Database']['SaveFilter'](arg1, arg2);
}

export function SaveIndividualPosition(arg1) {
  return window['go']['database']['Database']['SaveIndividualPosition'](arg1);
}

export function SaveLastVisitedPosition(arg1, arg2) {
  return window['go']['database']['Database']['SaveLastVisitedPosition'](arg1, arg2);
}

export function SaveLibrarySettings(arg1) {
  return window['go']['database']['Database']['SaveLibrarySettings'](arg1);
}

export function SaveMetadata(arg1) {
  return window['go']['database']['Database']['SaveMetadata'](arg1);
}

export function SavePosition(arg1) {
  return window['go']['database']['Database']['SavePosition'](arg1);
}

export function SaveSearchHistory(arg1, arg2, arg3) {
  return window['go']['database']['Database']['SaveSearchHistory'](arg1, arg2, arg3);
}

export function SaveSessionState(arg1) {
  return window['go']['database']['Database']['SaveSessionState'](arg1);
}

export function SaveTrainingSession(arg1) {
  return window['go']['database']['Database']['SaveTrainingSession'](arg1);
}

export function ScoreMoves() {
  return window['go']['database']['Database']['ScoreMoves']();
}

export function SearchComments(arg1) {
  return window['go']['database']['Database']['SearchComments'](arg1);
}

export function SearchPositionIDs(arg1, arg2, arg3) {
  return window['go']['database']['Database']['SearchPositionIDs'](arg1, arg2, arg3);
}

export function SeasonCSV(arg1) {
  return window['go']['database']['Database']['SeasonCSV'](arg1);
}

export function SeasonRanking(arg1) {
  return window['go']['database']['Database']['SeasonRanking'](arg1);
}

export function SetAlias(arg1, arg2, arg3) {
  return window['go']['database']['Database']['SetAlias'](arg1, arg2, arg3);
}

export function SetAnkiCardSuspended(arg1, arg2) {
  return window['go']['database']['Database']['SetAnkiCardSuspended'](arg1, arg2);
}

export function SetBeforeSwitch(arg1) {
  return window['go']['database']['Database']['SetBeforeSwitch'](arg1);
}

export function SetCollectionFilter(arg1, arg2) {
  return window['go']['database']['Database']['SetCollectionFilter'](arg1, arg2);
}

export function SetCommentAuthor(arg1) {
  return window['go']['database']['Database']['SetCommentAuthor'](arg1);
}

export function SetCurrentMET(arg1) {
  return window['go']['database']['Database']['SetCurrentMET'](arg1);
}

export function SetDirectionConfig(arg1, arg2) {
  return window['go']['database']['Database']['SetDirectionConfig'](arg1, arg2);
}

export function SetDirectionOutputDir(arg1, arg2) {
  return window['go']['database']['Database']['SetDirectionOutputDir'](arg1, arg2);
}

export function SetDirectionStrings(arg1, arg2) {
  return window['go']['database']['Database']['SetDirectionStrings'](arg1, arg2);
}

export function SetDirectionTables(arg1, arg2) {
  return window['go']['database']['Database']['SetDirectionTables'](arg1, arg2);
}

export function SetEventRooms(arg1, arg2, arg3) {
  return window['go']['database']['Database']['SetEventRooms'](arg1, arg2, arg3);
}

export function SetFilterPinned(arg1, arg2) {
  return window['go']['database']['Database']['SetFilterPinned'](arg1, arg2);
}

export function SetLessonStepDone(arg1, arg2) {
  return window['go']['database']['Database']['SetLessonStepDone'](arg1, arg2);
}

export function SetMatchTournamentByName(arg1, arg2) {
  return window['go']['database']['Database']['SetMatchTournamentByName'](arg1, arg2);
}

export function SetMigrationProgress(arg1) {
  return window['go']['database']['Database']['SetMigrationProgress'](arg1);
}

export function SetPositionStudied(arg1, arg2) {
  return window['go']['database']['Database']['SetPositionStudied'](arg1, arg2);
}

export function SetRencontreBreaks(arg1, arg2) {
  return window['go']['database']['Database']['SetRencontreBreaks'](arg1, arg2);
}

export function SetRencontreOutputDir(arg1, arg2) {
  return window['go']['database']['Database']['SetRencontreOutputDir'](arg1, arg2);
}

export function SetRencontreTableOutOfService(arg1, arg2, arg3) {
  return window['go']['database']['Database']['SetRencontreTableOutOfService'](arg1, arg2, arg3);
}

export function SetRencontreTables(arg1, arg2) {
  return window['go']['database']['Database']['SetRencontreTables'](arg1, arg2);
}

export function SetSkipDuplicates(arg1) {
  return window['go']['database']['Database']['SetSkipDuplicates'](arg1);
}

export function SetupDatabase(arg1) {
  return window['go']['database']['Database']['SetupDatabase'](arg1);
}

export function SimilarPositions(arg1, arg2) {
  return window['go']['database']['Database']['SimilarPositions'](arg1, arg2);
}

export function SinceLastGesture(arg1, arg2) {
  return window['go']['database']['Database']['SinceLastGesture'](arg1, arg2);
}

export function SlotOfMatch(arg1) {
  return window['go']['database']['Database']['SlotOfMatch'](arg1);
}

export function Slots(arg1) {
  return window['go']['database']['Database']['Slots'](arg1);
}

export function Standings(arg1) {
  return window['go']['database']['Database']['Standings'](arg1);
}

export function StandingsCSV(arg1) {
  return window['go']['database']['Database']['StandingsCSV'](arg1);
}

export function StartMatchManually(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['database']['Database']['StartMatchManually'](arg1, arg2, arg3, arg4, arg5);
}

export function StartTranscriptionFromSlot(arg1, arg2) {
  return window['go']['database']['Database']['StartTranscriptionFromSlot'](arg1, arg2);
}

export function StatsReportHTML(arg1, arg2, arg3) {
  return window['go']['database']['Database']['StatsReportHTML'](arg1, arg2, arg3);
}

export function StatsReportHTMLCtx(arg1, arg2, arg3, arg4) {
  return window['go']['database']['Database']['StatsReportHTMLCtx'](arg1, arg2, arg3, arg4);
}

export function StopDuel(arg1, arg2, arg3) {
  return window['go']['database']['Database']['StopDuel'](arg1, arg2, arg3);
}

export function StudyBacklog(arg1) {
  return window['go']['database']['Database']['StudyBacklog'](arg1);
}

export function StudyImpact(arg1) {
  return window['go']['database']['Database']['StudyImpact'](arg1);
}

export function StudyPlanPositionIDs(arg1, arg2, arg3) {
  return window['go']['database']['Database']['StudyPlanPositionIDs'](arg1, arg2, arg3);
}

export function StudyPlanQueue(arg1, arg2) {
  return window['go']['database']['Database']['StudyPlanQueue'](arg1, arg2);
}

export function StudyPositionIDs(arg1, arg2, arg3) {
  return window['go']['database']['Database']['StudyPositionIDs'](arg1, arg2, arg3);
}

export function SuggestAliases(arg1) {
  return window['go']['database']['Database']['SuggestAliases'](arg1);
}

export function SuggestMatFilename(arg1) {
  return window['go']['database']['Database']['SuggestMatFilename'](arg1);
}

export function SuggestReferencePositions(arg1, arg2, arg3) {
  return window['go']['database']['Database']['SuggestReferencePositions'](arg1, arg2, arg3);
}

export function SuggestReferencePositionsCtx(arg1, arg2, arg3, arg4) {
  return window['go']['database']['Database']['SuggestReferencePositionsCtx'](arg1, arg2, arg3, arg4);
}

export function SuggestTranscriptionMatFilename(arg1) {
  return window['go']['database']['Database']['SuggestTranscriptionMatFilename'](arg1);
}

export function SuspendDuel(arg1) {
  return window['go']['database']['Database']['SuspendDuel'](arg1);
}

export function SwapMatchPlayers(arg1) {
  return window['go']['database']['Database']['SwapMatchPlayers'](arg1);
}

export function SyncAnkiDeck(arg1) {
  return window['go']['database']['Database']['SyncAnkiDeck'](arg1);
}

export function SyncAnkiDeckWithPositions(arg1, arg2) {
  return window['go']['database']['Database']['SyncAnkiDeckWithPositions'](arg1, arg2);
}

export function TableGrid(arg1) {
  return window['go']['database']['Database']['TableGrid'](arg1);
}

export function TablePlan(arg1) {
  return window['go']['database']['Database']['TablePlan'](arg1);
}

export function Tags() {
  return window['go']['database']['Database']['Tags']();
}

export function TogglePile(arg1) {
  return window['go']['database']['Database']['TogglePile'](arg1);
}

export function TranscriptionMAT(arg1) {
  return window['go']['database']['Database']['TranscriptionMAT'](arg1);
}

export function TrashCollection(arg1) {
  return window['go']['database']['Database']['TrashCollection'](arg1);
}

export function TrashCommentEntry(arg1) {
  return window['go']['database']['Database']['TrashCommentEntry'](arg1);
}

export function TrashPosition(arg1) {
  return window['go']['database']['Database']['TrashPosition'](arg1);
}

export function TrashRencontre(arg1) {
  return window['go']['database']['Database']['TrashRencontre'](arg1);
}

export function UnattachedMatches(arg1) {
  return window['go']['database']['Database']['UnattachedMatches'](arg1);
}

export function UpdateAnkiDeck(arg1, arg2, arg3) {
  return window['go']['database']['Database']['UpdateAnkiDeck'](arg1, arg2, arg3);
}

export function UpdateAnkiDeckParams(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['database']['Database']['UpdateAnkiDeckParams'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateCollection(arg1, arg2, arg3) {
  return window['go']['database']['Database']['UpdateCollection'](arg1, arg2, arg3);
}

export function UpdateCommentEntry(arg1, arg2) {
  return window['go']['database']['Database']['UpdateCommentEntry'](arg1, arg2);
}

export function UpdateFilter(arg1, arg2, arg3) {
  return window['go']['database']['Database']['UpdateFilter'](arg1, arg2, arg3);
}

export function UpdateLesson(arg1, arg2, arg3) {
  return window['go']['database']['Database']['UpdateLesson'](arg1, arg2, arg3);
}

export function UpdateLessonStep(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['database']['Database']['UpdateLessonStep'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateMatch(arg1, arg2, arg3, arg4) {
  return window['go']['database']['Database']['UpdateMatch'](arg1, arg2, arg3, arg4);
}

export function UpdateMatchComment(arg1, arg2) {
  return window['go']['database']['Database']['UpdateMatchComment'](arg1, arg2);
}

export function UpdatePair(arg1, arg2, arg3, arg4) {
  return window['go']['database']['Database']['UpdatePair'](arg1, arg2, arg3, arg4);
}

export function UpdateParticipant(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['database']['Database']['UpdateParticipant'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdatePosition(arg1) {
  return window['go']['database']['Database']['UpdatePosition'](arg1);
}

export function UpdateRencontre(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['database']['Database']['UpdateRencontre'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateTournament(arg1, arg2, arg3, arg4) {
  return window['go']['database']['Database']['UpdateTournament'](arg1, arg2, arg3, arg4);
}

export function UpdateTournamentComment(arg1, arg2) {
  return window['go']['database']['Database']['UpdateTournamentComment'](arg1, arg2);
}

export function Vacuum() {
  return window['go']['database']['Database']['Vacuum']();
}

export function WithdrawParticipant(arg1, arg2, arg3) {
  return window['go']['database']['Database']['WithdrawParticipant'](arg1, arg2, arg3);
}

export function WriteDirectionPage(arg1) {
  return window['go']['database']['Database']['WriteDirectionPage'](arg1);
}

export function WriteDirectionPairingSheet(arg1, arg2) {
  return window['go']['database']['Database']['WriteDirectionPairingSheet'](arg1, arg2);
}

export function WriteDirectionUpcomingSheet(arg1, arg2) {
  return window['go']['database']['Database']['WriteDirectionUpcomingSheet'](arg1, arg2);
}

export function WriteRencontrePage(arg1) {
  return window['go']['database']['Database']['WriteRencontrePage'](arg1);
}
