// Package webui embeds the built web front and serves it (issue #295, fiche
// J.5, ADR-0039).
//
// The assets are VERSIONED here rather than built at release time. A binary
// built from a tag must contain the page that tag describes, and `go build
// ./cmd/serve` on a machine with no Node must produce a working daemon — both
// of which a build-time step would break. It is the same discipline the in-app
// help bundles (ADR-0034), openapi.yaml and the Python client already follow:
// generated, committed, regenerated by a make target.
//
// The counterpart is stated in ADR-0039 and repeated here because it is the
// one thing that can go wrong: NOTHING detects a stale dist. `make web` is to
// be run whenever frontend/src/web/ changes.
package webui

import (
	"embed"
	"io/fs"
	"net/http"
	"strings"
)

//go:embed all:dist
var assets embed.FS

// Prefix is where the daemon mounts the page. It is not configurable: a
// movable mount point would be one more thing a deployment can get wrong, and
// the page's own asset links are relative so it only has to be consistent.
const Prefix = "/app/"

// Handler serves the embedded page under Prefix.
//
// Unknown paths under the prefix fall back to the page itself rather than
// 404: the front is one page, and a user who bookmarks a deep link should
// land on it rather than on an error. Nothing here reads a database or a
// tenant — these are files.
func Handler() http.Handler {
	sub, err := fs.Sub(assets, "dist")
	if err != nil {
		// Unreachable: the directory is embedded at compile time. Serving
		// nothing is still better than panicking a daemon at startup.
		return http.NotFoundHandler()
	}
	files := http.FileServer(http.FS(sub))
	return http.StripPrefix(strings.TrimSuffix(Prefix, "/"), http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		path := strings.TrimPrefix(r.URL.Path, "/")
		if path == "" || path == "index.html" {
			serveIndex(w, r, sub)
			return
		}
		if _, err := fs.Stat(sub, path); err != nil {
			serveIndex(w, r, sub)
			return
		}
		files.ServeHTTP(w, r)
	}))
}

func serveIndex(w http.ResponseWriter, r *http.Request, sub fs.FS) {
	data, err := fs.ReadFile(sub, "web.html")
	if err != nil {
		http.NotFound(w, r)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	// The page is one file with hashed asset names beside it: it must not be
	// cached, they may be cached forever. Getting this backwards is how a user
	// ends up running last week's page against this week's daemon.
	w.Header().Set("Cache-Control", "no-store")
	_, _ = w.Write(data)
}
