// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDatabaseDialog():Promise<string>;

export function OpenPositionDialog():Promise<string>;

export function SaveDatabaseDialog():Promise<string>;
