// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAnalysis(arg1) {
  return window['go']['main']['Database']['DeleteAnalysis'](arg1);
}

export function DeleteComment(arg1) {
  return window['go']['main']['Database']['DeleteComment'](arg1);
}

export function DeletePosition(arg1) {
  return window['go']['main']['Database']['DeletePosition'](arg1);
}

export function LoadAllPositions() {
  return window['go']['main']['Database']['LoadAllPositions']();
}

export function LoadAnalysis(arg1) {
  return window['go']['main']['Database']['LoadAnalysis'](arg1);
}

export function LoadComment(arg1) {
  return window['go']['main']['Database']['LoadComment'](arg1);
}

export function LoadPosition(arg1) {
  return window['go']['main']['Database']['LoadPosition'](arg1);
}

export function LoadPositionsByCheckerPosition(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17) {
  return window['go']['main']['Database']['LoadPositionsByCheckerPosition'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17);
}

export function PositionExists(arg1) {
  return window['go']['main']['Database']['PositionExists'](arg1);
}

export function SaveAnalysis(arg1, arg2) {
  return window['go']['main']['Database']['SaveAnalysis'](arg1, arg2);
}

export function SaveComment(arg1, arg2) {
  return window['go']['main']['Database']['SaveComment'](arg1, arg2);
}

export function SavePosition(arg1) {
  return window['go']['main']['Database']['SavePosition'](arg1);
}

export function SetupDatabase(arg1) {
  return window['go']['main']['Database']['SetupDatabase'](arg1);
}

export function UpdatePosition(arg1) {
  return window['go']['main']['Database']['UpdatePosition'](arg1);
}
