// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadPosition(arg1:number):Promise<main.Position>;

export function SavePosition(arg1:main.Position):Promise<void>;

export function SetupDatabase(arg1:string):Promise<void>;
