// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadPosition(arg1) {
  return window['go']['main']['Database']['LoadPosition'](arg1);
}

export function SavePosition(arg1) {
  return window['go']['main']['Database']['SavePosition'](arg1);
}

export function SetupDatabase(arg1) {
  return window['go']['main']['Database']['SetupDatabase'](arg1);
}
