// Package gui is the Wails desktop application: the bound App struct the
// frontend calls through wailsjs, and Run (run.go), the bootstrap. Host
// capabilities (clipboard, fonts, config dir) are detected, never assumed
// (ADR-0004). Restart `wails dev` after adding or renaming a bound method.
package gui

import (
	"bytes"
	"compress/gzip"
	"context"
	_ "embed"
	"encoding/base64"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	goruntime "runtime"
	"strings"
	"sync"

	"github.com/wailsapp/wails/v2/pkg/runtime"

	"github.com/kevung/blunderdb/internal/applog"
	"github.com/kevung/blunderdb/pkg/blunderdb/database"
	"github.com/kevung/blunderdb/pkg/blunderdb/engine/training"
	"github.com/kevung/blunderdb/pkg/blunderdb/ingest"
)

// demoDBGz is the sample database for the guided tours, generated by
// scripts/build-demo-db.sh (rerun after every DatabaseVersion bump).
//
//go:embed demo.db.gz
var demoDBGz []byte

// App struct
type App struct {
	ctx context.Context
	// db is used only by jobs that need both the database and Wails events
	// (the gammonNet batch); other App methods stay database-free.
	db *database.Database

	// gnEvalMu/gnEvalCancel govern the Eval panel's at-rest search
	// (gammonnet_eval.go); gnLivePool is its shared searcher.
	gnEvalMu     sync.Mutex
	gnEvalCancel context.CancelFunc
	gnLivePool   gammonNetLivePool

	// gnBatchMu/gnBatchCancel: the same for the batch (gammonnet_batch.go).
	gnBatchMu     sync.Mutex
	gnBatchCancel context.CancelFunc
	// gnBatchDone is closed once the batch has actually stopped (nil when
	// none runs): a cancelled batch still writes its in-flight results, so
	// shutdown must wait on it before closing the database.
	gnBatchDone chan struct{}

	// trainingGen is built once, lazily (it costs megabytes); trainingErr
	// keeps why it failed so later questions refuse by name.
	trainingOnce sync.Once
	trainingGen  *training.Generator
	trainingErr  error

	// startupFilePath is the database the OS passed on the command line (file
	// association), set by run.go; empty on an ordinary launch.
	startupFilePath string

	// folderWatch is the watched folder's loop (watch.go).
	folderWatch folderWatch
}

// NewApp creates a new App application struct.
func NewApp(db *database.Database) *App {
	return &App{db: db}
}

// PrepareDemoDatabase decompresses the sample database to a fresh temporary
// file, for the normal open-database flow, and returns its path.
func (a *App) PrepareDemoDatabase() (string, error) {
	gz, err := gzip.NewReader(bytes.NewReader(demoDBGz))
	if err != nil {
		return "", fmt.Errorf("reading demo database: %w", err)
	}
	defer gz.Close()

	data, err := io.ReadAll(gz)
	if err != nil {
		return "", fmt.Errorf("decompressing demo database: %w", err)
	}

	f, err := os.CreateTemp("", "blunderdb-demo-*.db")
	if err != nil {
		return "", fmt.Errorf("creating temp demo database: %w", err)
	}
	defer f.Close()

	if _, err := f.Write(data); err != nil {
		return "", fmt.Errorf("writing temp demo database: %w", err)
	}
	return f.Name(), nil
}

func (a *App) SaveDatabaseDialog() (string, error) {
	filePath, err := runtime.SaveFileDialog(a.ctx, runtime.SaveDialogOptions{
		Title:                "New Database File",
		Filters:              []runtime.FileFilter{{DisplayName: "Database Files (*.db)", Pattern: "*.db"}},
		CanCreateDirectories: true,
	})
	if err != nil || filePath == "" {
		return filePath, err
	}
	// Ensure .db extension is present
	if !strings.HasSuffix(strings.ToLower(filePath), ".db") {
		filePath += ".db"
	}
	return filePath, nil
}

func (a *App) OpenDatabaseDialog() (string, error) {
	// Also list password-protected copies, which are blunderDB databases too.
	return runtime.OpenFileDialog(a.ctx, runtime.OpenDialogOptions{
		Title: "Open Database File",
		Filters: []runtime.FileFilter{
			{DisplayName: "blunderDB databases (*.db, *.dbx)", Pattern: "*.db;*.dbx"},
			{DisplayName: "Database Files (*.db)", Pattern: "*.db"},
			{DisplayName: "Protected copies (*.dbx)", Pattern: "*.dbx"},
		},
	})
}

func (a *App) OpenImportDatabaseDialog() (string, error) {
	return runtime.OpenFileDialog(a.ctx, runtime.OpenDialogOptions{
		Title:   "Import Database File",
		Filters: []runtime.FileFilter{{DisplayName: "Database Files (*.db)", Pattern: "*.db"}},
	})
}

func (a *App) OpenExportDatabaseDialog() (string, error) {
	filePath, err := runtime.SaveFileDialog(a.ctx, runtime.SaveDialogOptions{
		Title:                "Export Database File",
		Filters:              []runtime.FileFilter{{DisplayName: "Database Files (*.db)", Pattern: "*.db"}},
		CanCreateDirectories: true,
	})
	if err != nil || filePath == "" {
		return filePath, err
	}
	// Ensure .db extension is present
	if !strings.HasSuffix(strings.ToLower(filePath), ".db") {
		filePath += ".db"
	}
	return filePath, nil
}

// OpenExportMatDialog opens a save dialog pre-filled with defaultName
// (Database.SuggestMatFilename), ensures a .mat extension, "" on cancel.
func (a *App) OpenExportMatDialog(defaultName string) (string, error) {
	filePath, err := runtime.SaveFileDialog(a.ctx, runtime.SaveDialogOptions{
		Title:                "Export Match (.mat)",
		DefaultFilename:      defaultName,
		Filters:              []runtime.FileFilter{{DisplayName: "Jellyfish Match Files (*.mat)", Pattern: "*.mat"}},
		CanCreateDirectories: true,
	})
	if err != nil || filePath == "" {
		return filePath, err
	}
	if !strings.HasSuffix(strings.ToLower(filePath), ".mat") {
		filePath += ".mat"
	}
	return filePath, nil
}

// deletableExtensions is DeleteFile's allow-list: both of blunderDB's own
// database file shapes, never an arbitrary suffix.
var deletableExtensions = map[string]bool{".db": true, ".dbx": true}

// DeleteFile removes a database file the frontend created and abandoned. It
// requires an absolute path (the cwd is not the caller's) and a regular file.
func (a *App) DeleteFile(filePath string) error {
	ext := strings.ToLower(filepath.Ext(filePath))
	if !deletableExtensions[ext] {
		return newGUIError(CodeInvalid, "only .db or .dbx files can be deleted")
	}
	if !filepath.IsAbs(filePath) {
		return newGUIError(CodeInvalid, "path must be absolute")
	}
	info, err := os.Lstat(filePath)
	if err != nil {
		if os.IsNotExist(err) {
			return newGUIError(CodeNotFound, "file not found: "+filePath)
		}
		return newGUIError(CodeInternal, err.Error())
	}
	if !info.Mode().IsRegular() {
		return newGUIError(CodeInvalid, "not a regular file: "+filePath)
	}
	if err := os.Remove(filePath); err != nil {
		return newGUIError(CodeInternal, err.Error())
	}
	return nil
}

// maxReadFileBytes bounds ReadFileContent, which loads the file into one JS
// string: a huge file would stall or crash the webview.
const maxReadFileBytes = 64 << 20

// FileDialogResponse is what ReadFileContent returns; Cancelled tells a
// dismissed dialog apart from an I/O error.
type FileDialogResponse struct {
	FilePath  string `json:"file_path"`
	Content   string `json:"content"`
	Error     string `json:"error,omitempty"`     // Optional field to capture any errors
	Cancelled bool   `json:"cancelled,omitempty"` // true when the user dismissed the dialog with no selection
}

// readFileCapped reads path into a FileDialogResponse, refusing anything
// over maxReadFileBytes rather than loading it.
func readFileCapped(filePath string) (*FileDialogResponse, error) {
	info, err := os.Stat(filePath)
	if err != nil {
		return &FileDialogResponse{FilePath: filePath, Error: err.Error()}, newGUIError(CodeNotFound, err.Error())
	}
	if info.Size() > maxReadFileBytes {
		msg := fmt.Sprintf("file too large (%.1f MiB, max %.0f MiB)", float64(info.Size())/(1<<20), float64(maxReadFileBytes)/(1<<20))
		return &FileDialogResponse{FilePath: filePath, Error: msg}, newGUIError(CodeInvalid, msg)
	}
	content, err := os.ReadFile(filePath)
	if err != nil {
		return &FileDialogResponse{FilePath: filePath, Error: err.Error()}, newGUIError(CodeInternal, err.Error())
	}
	return &FileDialogResponse{
		FilePath: filePath,
		Content:  string(content),
	}, nil
}

// OpenPositionFilesDialog opens a multi-file selection dialog for position and match files.
func (a *App) OpenPositionFilesDialog() ([]string, error) {
	return runtime.OpenMultipleFilesDialog(a.ctx, runtime.OpenDialogOptions{
		Title: "Import Position or Match Files",
		Filters: []runtime.FileFilter{
			{DisplayName: "All Supported Files (*.txt, *.xg, *.xgp, *.sgf, *.mat, *.bgf)", Pattern: "*.txt;*.xg;*.xgp;*.sgf;*.mat;*.bgf"},
			{DisplayName: "Position Files (*.txt)", Pattern: "*.txt"},
			{DisplayName: "XG Match Files (*.xg)", Pattern: "*.xg"},
			{DisplayName: "XG Position Files (*.xgp)", Pattern: "*.xgp"},
			{DisplayName: "GnuBG Match Files (*.sgf)", Pattern: "*.sgf"},
			{DisplayName: "Jellyfish Match Files (*.mat)", Pattern: "*.mat"},
			{DisplayName: "BGBlitz Match Files (*.bgf)", Pattern: "*.bgf"},
			{DisplayName: "All Files (*.*)", Pattern: "*.*"},
		},
	})
}

// OpenPositionFolderDialog opens a directory selection dialog for importing all files within.
func (a *App) OpenPositionFolderDialog() (string, error) {
	return runtime.OpenDirectoryDialog(a.ctx, runtime.OpenDialogOptions{
		Title: "Select Folder to Import",
	})
}

// OpenDirectionOutputDialog asks for the folder the tournament display page
// is written into. Chosen once per Direction and remembered; after that the
// display refreshes without a gesture.
func (a *App) OpenDirectionOutputDialog() (string, error) {
	return runtime.OpenDirectoryDialog(a.ctx, runtime.OpenDialogOptions{
		Title: "Tournament Display Folder",
	})
}

// IsDirectory returns true if the given path is a directory.
func (a *App) IsDirectory(path string) bool {
	info, err := os.Stat(path)
	if err != nil {
		return false
	}
	return info.IsDir()
}

// PathExists reports whether path resolves on disk now. It decides nothing:
// the caller tells a gone path from a transient open failure.
func (a *App) PathExists(path string) bool {
	if path == "" {
		return false
	}
	_, err := os.Stat(path)
	return err == nil
}

// CollectImportableFiles recursively walks dirPath and returns all supported position/match files.
func (a *App) CollectImportableFiles(dirPath string) ([]string, error) {
	var files []string
	err := filepath.Walk(dirPath, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil // skip files/dirs we can't access
		}
		if info.IsDir() {
			return nil
		}
		if ingest.IsImportable(path) {
			files = append(files, path)
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("failed to walk directory: %w", err)
	}
	return files, nil
}

// ReadFileContent reads and returns the content of a file as a string,
// refusing anything over maxReadFileBytes.
func (a *App) ReadFileContent(filePath string) (*FileDialogResponse, error) {
	return readFileCapped(filePath)
}

func (a *App) ShowAlert(message string) {
	_, _ = runtime.MessageDialog(a.ctx, runtime.MessageDialogOptions{
		Type:    runtime.InfoDialog,
		Title:   "Alert",
		Message: message,
	})
}

// ShowQuestionDialog displays a question dialog with custom buttons and returns which button was clicked.
func (a *App) ShowQuestionDialog(title, message string, buttons []string, defaultButton string) (string, error) {
	return runtime.MessageDialog(a.ctx, runtime.MessageDialogOptions{
		Type:          runtime.QuestionDialog,
		Title:         title,
		Message:       message,
		Buttons:       buttons,
		DefaultButton: defaultButton,
	})
}

// startup is called when the app starts. The context is saved
// so we can call the runtime methods
func (a *App) startup(ctx context.Context) {
	a.ctx = ctx
	// Generate the missing bearoff tables silently in the background
	// (ADR-0027; about six seconds of one core on first launch).
	a.EnsureBearoffTables()
}

// StartupFilePath returns the database file the OS passed on the command
// line, or "" on an ordinary launch.
func (a *App) StartupFilePath() string {
	return a.startupFilePath
}

// OpenLogsFolder opens applog.Dir() in the file manager, creating it if
// needed.
func (a *App) OpenLogsFolder() error {
	dir := applog.Dir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return newGUIError(CodeInternal, err.Error())
	}
	if err := openFolder(dir); err != nil {
		return newGUIError(CodeInternal, err.Error())
	}
	return nil
}

// ReadLogTail returns the last lines of the log file, oldest first; a missing
// file (nothing logged yet) returns nothing, not an error.
func (a *App) ReadLogTail(lines int) ([]string, error) {
	out, err := applog.TailLines(lines)
	if err != nil {
		return nil, newGUIError(CodeInternal, err.Error())
	}
	return out, nil
}

// openFolder opens dir in the platform's file manager, passing dir as an
// argument, never through a shell.
func openFolder(dir string) error {
	var cmd *exec.Cmd
	switch goruntime.GOOS {
	case "darwin":
		cmd = exec.Command("open", dir)
	case "windows":
		cmd = exec.Command("explorer", dir)
	default:
		cmd = exec.Command("xdg-open", dir)
	}
	return cmd.Run()
}

// CopyImageToClipboard copies a base64 PNG to the clipboard, the fallback
// after the WebView's own write (ADR-0004). If no clipboard works it saves the
// PNG and returns its path ("" = clipboard reached); it errors only when even
// that fails.
func (a *App) CopyImageToClipboard(base64Data string) (string, error) {
	pngData, err := base64.StdEncoding.DecodeString(base64Data)
	if err != nil {
		return "", fmt.Errorf("failed to decode base64 data: %w", err)
	}

	switch goruntime.GOOS {
	case "linux":
		return copyImageLinux(pngData)

	case "darwin":
		// The path travels as an environment variable, never interpolated
		// into the script (a `"` or backslash would break it).
		if err := copyImageViaTempFile(pngData, func(path string) *exec.Cmd {
			cmd := exec.Command("osascript", "-e",
				`set the clipboard to (read (POSIX file (system attribute "BLUNDERDB_CLIPBOARD_PATH")) as «class PNGf»)`)
			cmd.Env = append(os.Environ(), "BLUNDERDB_CLIPBOARD_PATH="+path)
			return cmd
		}); err != nil {
			return saveImageFallback(pngData)
		}
		return "", nil

	case "windows":
		// As on darwin: the path travels as an environment variable.
		if err := copyImageViaTempFile(pngData, func(path string) *exec.Cmd {
			cmd := exec.Command("powershell", "-NoProfile", "-Command",
				`Add-Type -AssemblyName System.Windows.Forms; [System.Windows.Forms.Clipboard]::SetImage([System.Drawing.Image]::FromFile($env:BLUNDERDB_CLIPBOARD_PATH))`)
			cmd.Env = append(os.Environ(), "BLUNDERDB_CLIPBOARD_PATH="+path)
			return cmd
		}); err != nil {
			return saveImageFallback(pngData)
		}
		return "", nil

	default:
		return saveImageFallback(pngData)
	}
}

// copyImageViaTempFile writes the PNG to a temp file and runs the command built
// by buildCmd against it (macOS/Windows clipboard tools read from a file path).
func copyImageViaTempFile(pngData []byte, buildCmd func(path string) *exec.Cmd) error {
	tmpFile, err := os.CreateTemp("", "blunderdb-clipboard-*.png")
	if err != nil {
		return fmt.Errorf("failed to create temp file: %w", err)
	}
	defer os.Remove(tmpFile.Name())
	if _, err := tmpFile.Write(pngData); err != nil {
		tmpFile.Close()
		return fmt.Errorf("failed to write temp file: %w", err)
	}
	tmpFile.Close()
	if err := buildCmd(tmpFile.Name()).Run(); err != nil {
		return fmt.Errorf("clipboard command failed: %w", err)
	}
	return nil
}
