// Package gui is the Wails desktop application: the bound App struct (dialogs,
// clipboard, drag-drop, the demo/bearoff downloads) that the Svelte frontend
// calls through wailsjs, plus Run (run.go), the bootstrap Wails itself
// invokes with the embedded frontend assets and app icon. It is the only
// caller of package database that also has to cope with host quirks — a
// missing clipboard tool, absent fonts, an unwritable config dir — detected
// and degraded per ADR-0004 rather than assumed present; Dockerfile.hostile
// exercises those fallbacks in CI.
//
// Bound methods are regenerated into frontend/wailsjs by `wails dev`/`wails
// build`; restart `wails dev` after adding or renaming one.
package gui

import (
	"bytes"
	"compress/gzip"
	"context"
	_ "embed"
	"encoding/base64"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	goruntime "runtime"
	"strings"
	"sync"

	"github.com/wailsapp/wails/v2/pkg/runtime"

	"github.com/kevung/blunderdb/internal/applog"
	"github.com/kevung/blunderdb/pkg/blunderdb/database"
)

// demoDBGz is a small, self-contained sample database embedded gzip-compressed
// so the guided tours and first-time users have real content to explore: three
// matches under fictional names (two of them in a tournament), collections,
// tagged comments and an Anki deck with a review journal. It is generated by
// scripts/build-demo-db.sh — rerun it after every DatabaseVersion bump;
// demo_test.go checks the version and that no real person is named (#162).
//
//go:embed demo.db.gz
var demoDBGz []byte

// App struct
type App struct {
	ctx context.Context
	// db is used by the gammonNet batch job (#129) only — every other Wails
	// method on App stays database-free by design (the frontend orchestrates
	// calls across App/Database/Config, each bound independently). The batch
	// is the first operation that genuinely needs both database access and
	// Wails event emission in the same place, so it earns the exception
	// rather than inventing a fourth bound object.
	db *database.Database

	// gnEvalMu/gnEvalCancel govern the Eval panel's background "at rest"
	// tier (gammonnet_eval.go, #196/C.9): one search in flight at a time, a
	// new gesture cancels it. gnLivePool is the searcher its up to three
	// per-gesture searches share and reuse (gammonNetLivePool's own doc
	// comment). All three used to be package-level vars — every App
	// instance (a fresh one per test, per CLAUDE.md's CLI/GUI/server
	// parity notwithstanding) shared one global search-in-flight flag and
	// one global pool; moved here so instances are actually independent.
	gnEvalMu     sync.Mutex
	gnEvalCancel context.CancelFunc
	gnLivePool   gammonNetLivePool

	// gnBatchMu/gnBatchCancel are the same shape for the background batch
	// job (gammonnet_batch.go) — also moved off package vars for the same
	// reason.
	gnBatchMu     sync.Mutex
	gnBatchCancel context.CancelFunc

	// startupFilePath is the database file the OS handed this process on the
	// command line — a .desktop's Exec=blunderDB %f, a Windows/macOS file
	// association double-click (#241) — set by run.go right after
	// construction, never by the frontend. Empty on an ordinary launch.
	startupFilePath string
}

// NewApp creates a new App application struct.
func NewApp(db *database.Database) *App {
	return &App{db: db}
}

// PrepareDemoDatabase decompresses the embedded sample database to a fresh
// temporary file and returns its path. The frontend then opens it through the
// normal open-database flow, so loading the demo behaves exactly like opening
// any other database (a fresh copy each time, never mutating the embedded data).
func (a *App) PrepareDemoDatabase() (string, error) {
	gz, err := gzip.NewReader(bytes.NewReader(demoDBGz))
	if err != nil {
		return "", fmt.Errorf("reading demo database: %w", err)
	}
	defer gz.Close()

	data, err := io.ReadAll(gz)
	if err != nil {
		return "", fmt.Errorf("decompressing demo database: %w", err)
	}

	f, err := os.CreateTemp("", "blunderdb-demo-*.db")
	if err != nil {
		return "", fmt.Errorf("creating temp demo database: %w", err)
	}
	defer f.Close()

	if _, err := f.Write(data); err != nil {
		return "", fmt.Errorf("writing temp demo database: %w", err)
	}
	return f.Name(), nil
}

func (a *App) SaveDatabaseDialog() (string, error) {
	filePath, err := runtime.SaveFileDialog(a.ctx, runtime.SaveDialogOptions{
		Title:                "New Database File",
		Filters:              []runtime.FileFilter{{DisplayName: "Database Files (*.db)", Pattern: "*.db"}},
		CanCreateDirectories: true,
	})
	if err != nil || filePath == "" {
		return filePath, err
	}
	// Ensure .db extension is present
	if !strings.HasSuffix(strings.ToLower(filePath), ".db") {
		filePath += ".db"
	}
	return filePath, nil
}

func (a *App) OpenDatabaseDialog() (string, error) {
	// A password-protected copy is a blunderDB database too — it just needs its password
	// before it becomes one. Filtering on *.db alone made those files invisible in this
	// dialog, so a recipient had no way to open what they had been given.
	return runtime.OpenFileDialog(a.ctx, runtime.OpenDialogOptions{
		Title: "Open Database File",
		Filters: []runtime.FileFilter{
			{DisplayName: "blunderDB databases (*.db, *.dbx)", Pattern: "*.db;*.dbx"},
			{DisplayName: "Database Files (*.db)", Pattern: "*.db"},
			{DisplayName: "Protected copies (*.dbx)", Pattern: "*.dbx"},
		},
	})
}

func (a *App) OpenImportDatabaseDialog() (string, error) {
	return runtime.OpenFileDialog(a.ctx, runtime.OpenDialogOptions{
		Title:   "Import Database File",
		Filters: []runtime.FileFilter{{DisplayName: "Database Files (*.db)", Pattern: "*.db"}},
	})
}

func (a *App) OpenExportDatabaseDialog() (string, error) {
	filePath, err := runtime.SaveFileDialog(a.ctx, runtime.SaveDialogOptions{
		Title:                "Export Database File",
		Filters:              []runtime.FileFilter{{DisplayName: "Database Files (*.db)", Pattern: "*.db"}},
		CanCreateDirectories: true,
	})
	if err != nil || filePath == "" {
		return filePath, err
	}
	// Ensure .db extension is present
	if !strings.HasSuffix(strings.ToLower(filePath), ".db") {
		filePath += ".db"
	}
	return filePath, nil
}

// OpenExportMatDialog opens a save dialog for a match .mat export, pre-filled
// with defaultName (built server-side by Database.SuggestMatFilename so the GUI
// and CLI agree on the name). It ensures a .mat extension and returns "" if the
// user cancels.
func (a *App) OpenExportMatDialog(defaultName string) (string, error) {
	filePath, err := runtime.SaveFileDialog(a.ctx, runtime.SaveDialogOptions{
		Title:                "Export Match (.mat)",
		DefaultFilename:      defaultName,
		Filters:              []runtime.FileFilter{{DisplayName: "Jellyfish Match Files (*.mat)", Pattern: "*.mat"}},
		CanCreateDirectories: true,
	})
	if err != nil || filePath == "" {
		return filePath, err
	}
	if !strings.HasSuffix(strings.ToLower(filePath), ".mat") {
		filePath += ".mat"
	}
	return filePath, nil
}

// deletableExtensions is DeleteFile's allow-list: both of blunderDB's own
// database file shapes, never an arbitrary suffix (#241).
var deletableExtensions = map[string]bool{".db": true, ".dbx": true}

// DeleteFile removes a database file the frontend created and no longer
// wants (an abandoned "New Database" file, a cancelled export). It used to
// check only the suffix of whatever string it was handed — a relative path
// resolves against a cwd the caller does not control, and any string ending
// in ".db" passed regardless of what it pointed at. It now additionally
// requires an absolute path (so there is no ambient cwd to reason about) and
// that the target is a regular file, not a directory or something stranger
// (#241).
func (a *App) DeleteFile(filePath string) error {
	ext := strings.ToLower(filepath.Ext(filePath))
	if !deletableExtensions[ext] {
		return newGUIError(CodeInvalid, "only .db or .dbx files can be deleted")
	}
	if !filepath.IsAbs(filePath) {
		return newGUIError(CodeInvalid, "path must be absolute")
	}
	info, err := os.Lstat(filePath)
	if err != nil {
		if os.IsNotExist(err) {
			return newGUIError(CodeNotFound, "file not found: "+filePath)
		}
		return newGUIError(CodeInternal, err.Error())
	}
	if !info.Mode().IsRegular() {
		return newGUIError(CodeInvalid, "not a regular file: "+filePath)
	}
	if err := os.Remove(filePath); err != nil {
		return newGUIError(CodeInternal, err.Error())
	}
	return nil
}

// maxReadFileBytes bounds ReadFileContent: it loads the whole file into one
// JS string, so an unexpectedly huge file (a wrong pick, or a directory
// symlink trick) must be refused with a clear message rather than attempted
// — a multi-gigabyte read can stall or crash the webview well before it
// reaches the frontend at all (#241). Position/match text files are
// realistically kilobytes to a few megabytes; 64 MiB is generous headroom.
const maxReadFileBytes = 64 << 20

// FileDialogResponse is the wire shape ReadFileContent returns.
// Cancelled distinguishes "the user picked nothing" from a genuine failure
// (Error non-empty) — both used to collapse onto the same Error field, so a
// dialog the user simply dismissed looked identical to an I/O error to
// anything that checked Error != "" (#241).
type FileDialogResponse struct {
	FilePath  string `json:"file_path"`
	Content   string `json:"content"`
	Error     string `json:"error,omitempty"`     // Optional field to capture any errors
	Cancelled bool   `json:"cancelled,omitempty"` // true when the user dismissed the dialog with no selection
}

// readFileCapped reads path into a FileDialogResponse, refusing anything
// over maxReadFileBytes rather than loading it (#241).
func readFileCapped(filePath string) (*FileDialogResponse, error) {
	info, err := os.Stat(filePath)
	if err != nil {
		return &FileDialogResponse{FilePath: filePath, Error: err.Error()}, newGUIError(CodeNotFound, err.Error())
	}
	if info.Size() > maxReadFileBytes {
		msg := fmt.Sprintf("file too large (%.1f MiB, max %.0f MiB)", float64(info.Size())/(1<<20), float64(maxReadFileBytes)/(1<<20))
		return &FileDialogResponse{FilePath: filePath, Error: msg}, newGUIError(CodeInvalid, msg)
	}
	content, err := os.ReadFile(filePath)
	if err != nil {
		return &FileDialogResponse{FilePath: filePath, Error: err.Error()}, newGUIError(CodeInternal, err.Error())
	}
	return &FileDialogResponse{
		FilePath: filePath,
		Content:  string(content),
	}, nil
}

// OpenPositionFilesDialog opens a multi-file selection dialog for position and match files.
func (a *App) OpenPositionFilesDialog() ([]string, error) {
	return runtime.OpenMultipleFilesDialog(a.ctx, runtime.OpenDialogOptions{
		Title: "Import Position or Match Files",
		Filters: []runtime.FileFilter{
			{DisplayName: "All Supported Files (*.txt, *.xg, *.xgp, *.sgf, *.mat, *.bgf)", Pattern: "*.txt;*.xg;*.xgp;*.sgf;*.mat;*.bgf"},
			{DisplayName: "Position Files (*.txt)", Pattern: "*.txt"},
			{DisplayName: "XG Match Files (*.xg)", Pattern: "*.xg"},
			{DisplayName: "XG Position Files (*.xgp)", Pattern: "*.xgp"},
			{DisplayName: "GnuBG Match Files (*.sgf)", Pattern: "*.sgf"},
			{DisplayName: "Jellyfish Match Files (*.mat)", Pattern: "*.mat"},
			{DisplayName: "BGBlitz Match Files (*.bgf)", Pattern: "*.bgf"},
			{DisplayName: "All Files (*.*)", Pattern: "*.*"},
		},
	})
}

// OpenPositionFolderDialog opens a directory selection dialog for importing all files within.
func (a *App) OpenPositionFolderDialog() (string, error) {
	return runtime.OpenDirectoryDialog(a.ctx, runtime.OpenDialogOptions{
		Title: "Select Folder to Import",
	})
}

// supportedImportExtensions lists file extensions supported for position/match import.
var supportedImportExtensions = map[string]bool{
	".txt": true,
	".xg":  true,
	".xgp": true,
	".sgf": true,
	".mat": true,
	".bgf": true,
}

// IsDirectory returns true if the given path is a directory.
func (a *App) IsDirectory(path string) bool {
	info, err := os.Stat(path)
	if err != nil {
		return false
	}
	return info.IsDir()
}

// PathExists is a thin filesystem capability probe: it reports whether path
// currently resolves to something on disk. It reports facts only and decides
// nothing — the caller (e.g. last-database reopen at startup) uses it to tell a
// *definitively* gone path (forget it) from one that merely failed to open for a
// transient reason such as an unmounted disk or a lock held by another instance
// (keep it). A false here means "not present now", never "permanently invalid".
func (a *App) PathExists(path string) bool {
	if path == "" {
		return false
	}
	_, err := os.Stat(path)
	return err == nil
}

// CollectImportableFiles recursively walks dirPath and returns all supported position/match files.
func (a *App) CollectImportableFiles(dirPath string) ([]string, error) {
	var files []string
	err := filepath.Walk(dirPath, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil // skip files/dirs we can't access
		}
		if info.IsDir() {
			return nil
		}
		ext := strings.ToLower(filepath.Ext(path))
		if supportedImportExtensions[ext] {
			files = append(files, path)
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("failed to walk directory: %w", err)
	}
	return files, nil
}

// ReadFileContent reads and returns the content of a file as a string,
// refusing anything over maxReadFileBytes (#241).
func (a *App) ReadFileContent(filePath string) (*FileDialogResponse, error) {
	return readFileCapped(filePath)
}

func (a *App) ShowAlert(message string) {
	_, _ = runtime.MessageDialog(a.ctx, runtime.MessageDialogOptions{
		Type:    runtime.InfoDialog,
		Title:   "Alert",
		Message: message,
	})
}

// ShowQuestionDialog displays a question dialog with custom buttons and returns which button was clicked.
func (a *App) ShowQuestionDialog(title, message string, buttons []string, defaultButton string) (string, error) {
	return runtime.MessageDialog(a.ctx, runtime.MessageDialogOptions{
		Type:          runtime.QuestionDialog,
		Title:         title,
		Message:       message,
		Buttons:       buttons,
		DefaultButton: defaultButton,
	})
}

// startup is called when the app starts. The context is saved
// so we can call the runtime methods
func (a *App) startup(ctx context.Context) {
	a.ctx = ctx
	// The bearoff tables are generated on this machine, not shipped
	// (ADR-0027). Make whatever is missing, in the background and without a
	// word: a first launch spends about six seconds of one core while the user
	// gets on with what they opened the application for. The Eval panel is the
	// only place that mentions it, and only when a position needs a table that
	// is not ready yet.
	a.EnsureBearoffTables()
}

// StartupFilePath returns the database file path the OS handed this process
// on the command line, or "" on an ordinary launch with none (#241). The
// frontend calls this once at boot and opens it in preference to (or
// alongside) the last-used database from Config.
func (a *App) StartupFilePath() string {
	return a.startupFilePath
}

// OpenLogsFolder opens the directory holding blunderDB's GUI log file
// (applog.Dir()) in the platform's file manager, creating it first if this
// is a fresh install that has not logged anything yet (#241).
func (a *App) OpenLogsFolder() error {
	dir := applog.Dir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return newGUIError(CodeInternal, err.Error())
	}
	if err := openFolder(dir); err != nil {
		return newGUIError(CodeInternal, err.Error())
	}
	return nil
}

// openFolder opens dir in the platform's file manager: xdg-open on Linux,
// `open` on macOS, `explorer` on Windows — each invoked with dir as its own
// exec.Command argument, never string-interpolated into a shell command
// line (#241).
func openFolder(dir string) error {
	var cmd *exec.Cmd
	switch goruntime.GOOS {
	case "darwin":
		cmd = exec.Command("open", dir)
	case "windows":
		cmd = exec.Command("explorer", dir)
	default:
		cmd = exec.Command("xdg-open", dir)
	}
	return cmd.Run()
}

// CopyImageToClipboard takes base64-encoded PNG data and copies it to the system
// clipboard. The image clipboard is an Optional host capability (docs/adr/0004):
// this is the *last* line of defence, reached only after the frontend's native
// WebView clipboard write has already been tried and declined. When no clipboard
// path works it does not fail the user's gesture — it saves the PNG to a file and
// returns that path (empty string means the image reached the clipboard directly),
// so the caller can tell the user where to find it. It errors only when even the
// file fallback fails (e.g. no writable location).
func (a *App) CopyImageToClipboard(base64Data string) (string, error) {
	pngData, err := base64.StdEncoding.DecodeString(base64Data)
	if err != nil {
		return "", fmt.Errorf("failed to decode base64 data: %w", err)
	}

	switch goruntime.GOOS {
	case "linux":
		return copyImageLinux(pngData)

	case "darwin":
		// The path flows in as an environment variable, read back with
		// AppleScript's `system attribute`, rather than interpolated into
		// the script text (#241) — the previous version built the script
		// with fmt.Sprintf around the path, which is safe only as long as
		// the path (today, always our own os.CreateTemp name) never
		// contains a `"` or backslash AppleScript's string literal would
		// choke on.
		if err := copyImageViaTempFile(pngData, func(path string) *exec.Cmd {
			cmd := exec.Command("osascript", "-e",
				`set the clipboard to (read (POSIX file (system attribute "BLUNDERDB_CLIPBOARD_PATH")) as «class PNGf»)`)
			cmd.Env = append(os.Environ(), "BLUNDERDB_CLIPBOARD_PATH="+path)
			return cmd
		}); err != nil {
			return saveImageFallback(pngData)
		}
		return "", nil

	case "windows":
		// Same reasoning as the darwin branch above: the path travels as an
		// environment variable PowerShell reads back with $env:, never
		// interpolated into the -Command string (#241).
		if err := copyImageViaTempFile(pngData, func(path string) *exec.Cmd {
			cmd := exec.Command("powershell", "-NoProfile", "-Command",
				`Add-Type -AssemblyName System.Windows.Forms; [System.Windows.Forms.Clipboard]::SetImage([System.Drawing.Image]::FromFile($env:BLUNDERDB_CLIPBOARD_PATH))`)
			cmd.Env = append(os.Environ(), "BLUNDERDB_CLIPBOARD_PATH="+path)
			return cmd
		}); err != nil {
			return saveImageFallback(pngData)
		}
		return "", nil

	default:
		return saveImageFallback(pngData)
	}
}

// copyImageViaTempFile writes the PNG to a temp file and runs the command built
// by buildCmd against it (macOS/Windows clipboard tools read from a file path).
func copyImageViaTempFile(pngData []byte, buildCmd func(path string) *exec.Cmd) error {
	tmpFile, err := os.CreateTemp("", "blunderdb-clipboard-*.png")
	if err != nil {
		return fmt.Errorf("failed to create temp file: %w", err)
	}
	defer os.Remove(tmpFile.Name())
	if _, err := tmpFile.Write(pngData); err != nil {
		tmpFile.Close()
		return fmt.Errorf("failed to write temp file: %w", err)
	}
	tmpFile.Close()
	if err := buildCmd(tmpFile.Name()).Run(); err != nil {
		return fmt.Errorf("clipboard command failed: %w", err)
	}
	return nil
}
