// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CollectImportableFiles(arg1:string):Promise<Array<string>>;

export function DeleteFile(arg1:string):Promise<void>;

export function OpenDatabaseDialog():Promise<string>;

export function OpenExportDatabaseDialog():Promise<string>;

export function OpenImportDatabaseDialog():Promise<string>;

export function OpenPositionDialog():Promise<main.FileDialogResponse>;

export function OpenPositionFilesDialog():Promise<Array<string>>;

export function OpenPositionFolderDialog():Promise<string>;

export function OpenXGFileDialog():Promise<string>;

export function ReadFileContent(arg1:string):Promise<main.FileDialogResponse>;

export function SaveDatabaseDialog():Promise<string>;

export function ShowAlert(arg1:string):Promise<void>;
