// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLastDatabasePath() {
  return window['go']['main']['Config']['GetLastDatabasePath']();
}

export function LoadConfig() {
  return window['go']['main']['Config']['LoadConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['Config']['SaveConfig'](arg1);
}

export function SaveLastDatabasePath(arg1) {
  return window['go']['main']['Config']['SaveLastDatabasePath'](arg1);
}

export function SaveWindowDimensions(arg1, arg2) {
  return window['go']['main']['Config']['SaveWindowDimensions'](arg1, arg2);
}
