// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBearoffTsPath() {
  return window['go']['main']['Config']['GetBearoffTsPath']();
}

export function GetBoardColors() {
  return window['go']['main']['Config']['GetBoardColors']();
}

export function GetEpcChallenge() {
  return window['go']['main']['Config']['GetEpcChallenge']();
}

export function GetGammonNetAnalysisPly() {
  return window['go']['main']['Config']['GetGammonNetAnalysisPly']();
}

export function GetGammonNetAutoAnalyze() {
  return window['go']['main']['Config']['GetGammonNetAutoAnalyze']();
}

export function GetGammonNetCandidates() {
  return window['go']['main']['Config']['GetGammonNetCandidates']();
}

export function GetGammonNetDisplayPly() {
  return window['go']['main']['Config']['GetGammonNetDisplayPly']();
}

export function GetGammonNetPruneK() {
  return window['go']['main']['Config']['GetGammonNetPruneK']();
}

export function GetLanguage() {
  return window['go']['main']['Config']['GetLanguage']();
}

export function GetLastDatabasePath() {
  return window['go']['main']['Config']['GetLastDatabasePath']();
}

export function GetPanelPosition() {
  return window['go']['main']['Config']['GetPanelPosition']();
}

export function GetStatsFilter() {
  return window['go']['main']['Config']['GetStatsFilter']();
}

export function GetTourSeen() {
  return window['go']['main']['Config']['GetTourSeen']();
}

export function GetUIScale() {
  return window['go']['main']['Config']['GetUIScale']();
}

export function LoadConfig() {
  return window['go']['main']['Config']['LoadConfig']();
}

export function SaveBearoffTsPath(arg1) {
  return window['go']['main']['Config']['SaveBearoffTsPath'](arg1);
}

export function SaveBoardColors(arg1) {
  return window['go']['main']['Config']['SaveBoardColors'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['Config']['SaveConfig'](arg1);
}

export function SaveEpcChallenge(arg1) {
  return window['go']['main']['Config']['SaveEpcChallenge'](arg1);
}

export function SaveGammonNetAnalysisPly(arg1) {
  return window['go']['main']['Config']['SaveGammonNetAnalysisPly'](arg1);
}

export function SaveGammonNetAutoAnalyze(arg1) {
  return window['go']['main']['Config']['SaveGammonNetAutoAnalyze'](arg1);
}

export function SaveGammonNetCandidates(arg1) {
  return window['go']['main']['Config']['SaveGammonNetCandidates'](arg1);
}

export function SaveGammonNetDisplayPly(arg1) {
  return window['go']['main']['Config']['SaveGammonNetDisplayPly'](arg1);
}

export function SaveGammonNetPruneK(arg1) {
  return window['go']['main']['Config']['SaveGammonNetPruneK'](arg1);
}

export function SaveLanguage(arg1) {
  return window['go']['main']['Config']['SaveLanguage'](arg1);
}

export function SaveLastDatabasePath(arg1) {
  return window['go']['main']['Config']['SaveLastDatabasePath'](arg1);
}

export function SavePanelPosition(arg1) {
  return window['go']['main']['Config']['SavePanelPosition'](arg1);
}

export function SaveStatsFilter(arg1) {
  return window['go']['main']['Config']['SaveStatsFilter'](arg1);
}

export function SaveTourSeen(arg1) {
  return window['go']['main']['Config']['SaveTourSeen'](arg1);
}

export function SaveUIScale(arg1) {
  return window['go']['main']['Config']['SaveUIScale'](arg1);
}

export function SaveWindowDimensions(arg1, arg2) {
  return window['go']['main']['Config']['SaveWindowDimensions'](arg1, arg2);
}
