// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetBearoffCores():Promise<number>;

export function GetBearoffRate():Promise<number>;

export function GetBearoffTSPath():Promise<string>;

export function GetBoardColors():Promise<main.BoardColors>;

export function GetCheckForUpdates():Promise<boolean>;

export function GetEpcChallenge():Promise<boolean>;

export function GetGammonNetAnalysisPly():Promise<number>;

export function GetGammonNetAutoAnalyze():Promise<boolean>;

export function GetGammonNetCandidates():Promise<number>;

export function GetGammonNetDisplayPly():Promise<number>;

export function GetGammonNetPruneK():Promise<number>;

export function GetHiddenTabs():Promise<Array<string>>;

export function GetLanguage():Promise<string>;

export function GetLastDatabasePath():Promise<string>;

export function GetPanelHeight():Promise<number>;

export function GetPanelPosition():Promise<string>;

export function GetPanelWidth():Promise<number>;

export function GetStatsFilter():Promise<main.StatsFilterPersisted>;

export function GetTabOrder():Promise<Array<string>>;

export function GetTheme():Promise<string>;

export function GetTourSeen():Promise<boolean>;

export function GetUIScale():Promise<number>;

export function GetWatchFolder():Promise<boolean>;

export function LoadConfig():Promise<main.Config>;

export function SaveBearoffCores(arg1:number):Promise<void>;

export function SaveBearoffRate(arg1:number):Promise<void>;

export function SaveBearoffTSPath(arg1:string):Promise<void>;

export function SaveBoardColors(arg1:main.BoardColors):Promise<void>;

export function SaveCheckForUpdates(arg1:boolean):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SaveEpcChallenge(arg1:boolean):Promise<void>;

export function SaveGammonNetAnalysisPly(arg1:number):Promise<void>;

export function SaveGammonNetAutoAnalyze(arg1:boolean):Promise<void>;

export function SaveGammonNetCandidates(arg1:number):Promise<void>;

export function SaveGammonNetDisplayPly(arg1:number):Promise<void>;

export function SaveGammonNetPruneK(arg1:number):Promise<void>;

export function SaveHiddenTabs(arg1:Array<string>):Promise<void>;

export function SaveLanguage(arg1:string):Promise<void>;

export function SaveLastDatabasePath(arg1:string):Promise<void>;

export function SavePanelHeight(arg1:number):Promise<void>;

export function SavePanelPosition(arg1:string):Promise<void>;

export function SavePanelWidth(arg1:number):Promise<void>;

export function SaveStatsFilter(arg1:main.StatsFilterPersisted):Promise<void>;

export function SaveTabOrder(arg1:Array<string>):Promise<void>;

export function SaveTheme(arg1:string):Promise<void>;

export function SaveTourSeen(arg1:boolean):Promise<void>;

export function SaveUIScale(arg1:number):Promise<void>;

export function SaveWatchFolder(arg1:boolean,arg2:string,arg3:number):Promise<void>;

export function SaveWindowDimensions(arg1:number,arg2:number):Promise<void>;
