// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddMatchToTournament(arg1:number,arg2:number):Promise<void>;

export function AddPositionToCollection(arg1:number,arg2:number):Promise<void>;

export function AddPositionsToCollection(arg1:number,arg2:Array<number>):Promise<void>;

export function AnalyzeImportDatabase(arg1:string):Promise<Record<string, any>>;

export function CancelImport():Promise<void>;

export function CheckDatabaseVersion():Promise<string>;

export function CheckMatchExists(arg1:string):Promise<number>;

export function CheckVersion(arg1:string):Promise<void>;

export function ClearCommandHistory():Promise<void>;

export function ClearSessionState():Promise<void>;

export function CommitImportDatabase(arg1:string):Promise<Record<string, any>>;

export function CopyPositionToCollection(arg1:number,arg2:number):Promise<void>;

export function CreateCollection(arg1:string,arg2:string):Promise<number>;

export function CreateTournament(arg1:string,arg2:string,arg3:string):Promise<number>;

export function DeleteAnalysis(arg1:number):Promise<void>;

export function DeleteCollection(arg1:number):Promise<void>;

export function DeleteComment(arg1:number):Promise<void>;

export function DeleteFilter(arg1:number):Promise<void>;

export function DeleteMatch(arg1:number):Promise<void>;

export function DeletePosition(arg1:number):Promise<void>;

export function DeleteSearchHistoryEntry(arg1:number):Promise<void>;

export function DeleteTournament(arg1:number):Promise<void>;

export function ExportCollections(arg1:string,arg2:Array<number>,arg3:Record<string, string>,arg4:boolean,arg5:boolean):Promise<void>;

export function ExportDatabase(arg1:string,arg2:Array<main.Position>,arg3:Record<string, string>,arg4:boolean,arg5:boolean,arg6:boolean,arg7:boolean,arg8:boolean,arg9:boolean,arg10:Array<number>,arg11:Array<number>,arg12:Array<number>):Promise<void>;

export function ExportTournaments(arg1:string,arg2:Array<number>,arg3:Record<string, string>,arg4:boolean,arg5:boolean):Promise<void>;

export function GetAllCollections():Promise<Array<main.Collection>>;

export function GetAllMatches():Promise<Array<main.Match>>;

export function GetAllTournaments():Promise<Array<main.Tournament>>;

export function GetCollectionByID(arg1:number):Promise<main.Collection>;

export function GetCollectionPositions(arg1:number):Promise<Array<main.Position>>;

export function GetDatabaseStats():Promise<Record<string, any>>;

export function GetDatabaseVersion():Promise<string>;

export function GetGamesByMatch(arg1:number):Promise<Array<main.Game>>;

export function GetMatchByID(arg1:number):Promise<main.Match>;

export function GetMatchMovePositions(arg1:number):Promise<Array<main.MatchMovePosition>>;

export function GetMatchTournament(arg1:number):Promise<main.Tournament>;

export function GetMovesByGame(arg1:number):Promise<Array<main.Move>>;

export function GetPositionCollections(arg1:number):Promise<Array<main.Collection>>;

export function GetPositionIndexMap():Promise<Record<number, number>>;

export function GetTournamentMatches(arg1:number):Promise<Array<main.Match>>;

export function ImportDatabase(arg1:string):Promise<Record<string, any>>;

export function ImportGnuBGMatch(arg1:string):Promise<number>;

export function ImportXGMatch(arg1:string):Promise<number>;

export function LoadAllPositions():Promise<Array<main.Position>>;

export function LoadAnalysis(arg1:number):Promise<main.PositionAnalysis>;

export function LoadCommandHistory():Promise<Array<string>>;

export function LoadComment(arg1:number):Promise<string>;

export function LoadEditPosition(arg1:string):Promise<string>;

export function LoadFilters():Promise<Array<Record<string, any>>>;

export function LoadMetadata():Promise<Record<string, string>>;

export function LoadPosition(arg1:number):Promise<main.Position>;

export function LoadPositionsByFilters(arg1:main.Position,arg2:boolean,arg3:boolean,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string,arg12:string,arg13:string,arg14:string,arg15:string,arg16:string,arg17:string,arg18:string,arg19:string,arg20:boolean,arg21:boolean,arg22:string,arg23:string,arg24:string,arg25:string,arg26:string,arg27:string,arg28:boolean,arg29:boolean,arg30:string):Promise<Array<main.Position>>;

export function LoadSearchHistory():Promise<Array<main.SearchHistory>>;

export function LoadSessionState():Promise<main.SessionState>;

export function Migrate_1_0_0_to_1_1_0():Promise<void>;

export function Migrate_1_1_0_to_1_2_0():Promise<void>;

export function Migrate_1_2_0_to_1_3_0():Promise<void>;

export function MovePositionBetweenCollections(arg1:number,arg2:number,arg3:number):Promise<void>;

export function OpenDatabase(arg1:string):Promise<void>;

export function PositionExists(arg1:main.Position):Promise<Record<string, any>>;

export function RemoveMatchFromTournament(arg1:number):Promise<void>;

export function RemovePositionFromCollection(arg1:number,arg2:number):Promise<void>;

export function RemovePositionsFromCollection(arg1:number,arg2:Array<number>):Promise<void>;

export function ReorderCollectionPositions(arg1:number,arg2:Array<number>):Promise<void>;

export function ReorderCollections(arg1:Array<number>):Promise<void>;

export function SaveAnalysis(arg1:number,arg2:main.PositionAnalysis):Promise<void>;

export function SaveCommand(arg1:string):Promise<void>;

export function SaveComment(arg1:number,arg2:string):Promise<void>;

export function SaveEditPosition(arg1:string,arg2:string):Promise<void>;

export function SaveFilter(arg1:string,arg2:string):Promise<void>;

export function SaveMetadata(arg1:Record<string, string>):Promise<void>;

export function SavePosition(arg1:main.Position):Promise<number>;

export function SaveSearchHistory(arg1:string,arg2:string):Promise<void>;

export function SaveSessionState(arg1:main.SessionState):Promise<void>;

export function SetMatchTournamentByName(arg1:number,arg2:string):Promise<void>;

export function SetupDatabase(arg1:string):Promise<void>;

export function UpdateCollection(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateFilter(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdatePosition(arg1:main.Position):Promise<void>;

export function UpdateTournament(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;
