// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeImportDatabase(arg1) {
  return window['go']['main']['Database']['AnalyzeImportDatabase'](arg1);
}

export function CancelImport() {
  return window['go']['main']['Database']['CancelImport']();
}

export function CheckDatabaseVersion() {
  return window['go']['main']['Database']['CheckDatabaseVersion']();
}

export function CheckMatchExists(arg1) {
  return window['go']['main']['Database']['CheckMatchExists'](arg1);
}

export function CheckVersion(arg1) {
  return window['go']['main']['Database']['CheckVersion'](arg1);
}

export function ClearCommandHistory() {
  return window['go']['main']['Database']['ClearCommandHistory']();
}

export function CommitImportDatabase(arg1) {
  return window['go']['main']['Database']['CommitImportDatabase'](arg1);
}

export function DeleteAnalysis(arg1) {
  return window['go']['main']['Database']['DeleteAnalysis'](arg1);
}

export function DeleteComment(arg1) {
  return window['go']['main']['Database']['DeleteComment'](arg1);
}

export function DeleteFilter(arg1) {
  return window['go']['main']['Database']['DeleteFilter'](arg1);
}

export function DeleteMatch(arg1) {
  return window['go']['main']['Database']['DeleteMatch'](arg1);
}

export function DeletePosition(arg1) {
  return window['go']['main']['Database']['DeletePosition'](arg1);
}

export function DeleteSearchHistoryEntry(arg1) {
  return window['go']['main']['Database']['DeleteSearchHistoryEntry'](arg1);
}

export function ExportDatabase(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['Database']['ExportDatabase'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetAllMatches() {
  return window['go']['main']['Database']['GetAllMatches']();
}

export function GetDatabaseStats() {
  return window['go']['main']['Database']['GetDatabaseStats']();
}

export function GetDatabaseVersion() {
  return window['go']['main']['Database']['GetDatabaseVersion']();
}

export function GetGamesByMatch(arg1) {
  return window['go']['main']['Database']['GetGamesByMatch'](arg1);
}

export function GetMatchByID(arg1) {
  return window['go']['main']['Database']['GetMatchByID'](arg1);
}

export function GetMatchMovePositions(arg1) {
  return window['go']['main']['Database']['GetMatchMovePositions'](arg1);
}

export function GetMovesByGame(arg1) {
  return window['go']['main']['Database']['GetMovesByGame'](arg1);
}

export function ImportDatabase(arg1) {
  return window['go']['main']['Database']['ImportDatabase'](arg1);
}

export function ImportXGMatch(arg1) {
  return window['go']['main']['Database']['ImportXGMatch'](arg1);
}

export function LoadAllPositions() {
  return window['go']['main']['Database']['LoadAllPositions']();
}

export function LoadAnalysis(arg1) {
  return window['go']['main']['Database']['LoadAnalysis'](arg1);
}

export function LoadCommandHistory() {
  return window['go']['main']['Database']['LoadCommandHistory']();
}

export function LoadComment(arg1) {
  return window['go']['main']['Database']['LoadComment'](arg1);
}

export function LoadEditPosition(arg1) {
  return window['go']['main']['Database']['LoadEditPosition'](arg1);
}

export function LoadFilters() {
  return window['go']['main']['Database']['LoadFilters']();
}

export function LoadMetadata() {
  return window['go']['main']['Database']['LoadMetadata']();
}

export function LoadPosition(arg1) {
  return window['go']['main']['Database']['LoadPosition'](arg1);
}

export function LoadPositionsByFilters(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21, arg22, arg23, arg24, arg25, arg26, arg27, arg28, arg29) {
  return window['go']['main']['Database']['LoadPositionsByFilters'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21, arg22, arg23, arg24, arg25, arg26, arg27, arg28, arg29);
}

export function LoadSearchHistory() {
  return window['go']['main']['Database']['LoadSearchHistory']();
}

export function Migrate_1_0_0_to_1_1_0() {
  return window['go']['main']['Database']['Migrate_1_0_0_to_1_1_0']();
}

export function Migrate_1_1_0_to_1_2_0() {
  return window['go']['main']['Database']['Migrate_1_1_0_to_1_2_0']();
}

export function Migrate_1_2_0_to_1_3_0() {
  return window['go']['main']['Database']['Migrate_1_2_0_to_1_3_0']();
}

export function OpenDatabase(arg1) {
  return window['go']['main']['Database']['OpenDatabase'](arg1);
}

export function PositionExists(arg1) {
  return window['go']['main']['Database']['PositionExists'](arg1);
}

export function SaveAnalysis(arg1, arg2) {
  return window['go']['main']['Database']['SaveAnalysis'](arg1, arg2);
}

export function SaveCommand(arg1) {
  return window['go']['main']['Database']['SaveCommand'](arg1);
}

export function SaveComment(arg1, arg2) {
  return window['go']['main']['Database']['SaveComment'](arg1, arg2);
}

export function SaveEditPosition(arg1, arg2) {
  return window['go']['main']['Database']['SaveEditPosition'](arg1, arg2);
}

export function SaveFilter(arg1, arg2) {
  return window['go']['main']['Database']['SaveFilter'](arg1, arg2);
}

export function SaveMetadata(arg1) {
  return window['go']['main']['Database']['SaveMetadata'](arg1);
}

export function SavePosition(arg1) {
  return window['go']['main']['Database']['SavePosition'](arg1);
}

export function SaveSearchHistory(arg1, arg2) {
  return window['go']['main']['Database']['SaveSearchHistory'](arg1, arg2);
}

export function SetupDatabase(arg1) {
  return window['go']['main']['Database']['SetupDatabase'](arg1);
}

export function UpdateFilter(arg1, arg2, arg3) {
  return window['go']['main']['Database']['UpdateFilter'](arg1, arg2, arg3);
}

export function UpdatePosition(arg1) {
  return window['go']['main']['Database']['UpdatePosition'](arg1);
}
