// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDatabaseVersion() {
  return window['go']['main']['Database']['CheckDatabaseVersion']();
}

export function CheckVersion(arg1) {
  return window['go']['main']['Database']['CheckVersion'](arg1);
}

export function DeleteAnalysis(arg1) {
  return window['go']['main']['Database']['DeleteAnalysis'](arg1);
}

export function DeleteComment(arg1) {
  return window['go']['main']['Database']['DeleteComment'](arg1);
}

export function DeletePosition(arg1) {
  return window['go']['main']['Database']['DeletePosition'](arg1);
}

export function GetDatabaseVersion() {
  return window['go']['main']['Database']['GetDatabaseVersion']();
}

export function LoadAllPositions() {
  return window['go']['main']['Database']['LoadAllPositions']();
}

export function LoadAnalysis(arg1) {
  return window['go']['main']['Database']['LoadAnalysis'](arg1);
}

export function LoadComment(arg1) {
  return window['go']['main']['Database']['LoadComment'](arg1);
}

export function LoadMetadata() {
  return window['go']['main']['Database']['LoadMetadata']();
}

export function LoadPosition(arg1) {
  return window['go']['main']['Database']['LoadPosition'](arg1);
}

export function LoadPositionsByFilters(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21) {
  return window['go']['main']['Database']['LoadPositionsByFilters'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21);
}

export function OpenDatabase(arg1) {
  return window['go']['main']['Database']['OpenDatabase'](arg1);
}

export function PositionExists(arg1) {
  return window['go']['main']['Database']['PositionExists'](arg1);
}

export function SaveAnalysis(arg1, arg2) {
  return window['go']['main']['Database']['SaveAnalysis'](arg1, arg2);
}

export function SaveComment(arg1, arg2) {
  return window['go']['main']['Database']['SaveComment'](arg1, arg2);
}

export function SaveMetadata(arg1) {
  return window['go']['main']['Database']['SaveMetadata'](arg1);
}

export function SavePosition(arg1) {
  return window['go']['main']['Database']['SavePosition'](arg1);
}

export function SetupDatabase(arg1) {
  return window['go']['main']['Database']['SetupDatabase'](arg1);
}

export function UpdatePosition(arg1, arg2) {
  return window['go']['main']['Database']['UpdatePosition'](arg1, arg2);
}
